# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pl_gpio_uart_constrain.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_versal_cips_0_0/design_1_versal_cips_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_versal_cips_0_0 || ORIG_REF_NAME==design_1_versal_cips_0_0} -quiet] -quiet

# Block Designs: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_versal_cips_0_0/bd_0/bd_70da.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_70da || ORIG_REF_NAME==bd_70da} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_versal_cips_0_0/bd_0/ip/ip_0/bd_70da_pspmc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_70da_pspmc_0_0 || ORIG_REF_NAME==bd_70da_pspmc_0_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_versal_cips_0_0/bd_0/ip/ip_0/ip_0/versal_cips_ps_vip_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_cips_ps_vip_0 || ORIG_REF_NAME==versal_cips_ps_vip_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_noc_0_0/design_1_axi_noc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_noc_0_0 || ORIG_REF_NAME==design_1_axi_noc_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_1_0 || ORIG_REF_NAME==design_1_axi_gpio_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_uartlite_0_0 || ORIG_REF_NAME==design_1_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_smc_0/design_1_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_smc_0 || ORIG_REF_NAME==design_1_axi_smc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_versal_cips_0_295M_0/design_1_rst_versal_cips_0_295M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_versal_cips_0_295M_0 || ORIG_REF_NAME==design_1_rst_versal_cips_0_295M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_0/design_1_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_0 || ORIG_REF_NAME==design_1_xlslice_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_1_0/design_1_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_1_0 || ORIG_REF_NAME==design_1_xlslice_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_2_0/design_1_xlslice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_2_0 || ORIG_REF_NAME==design_1_xlslice_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_3_0/design_1_xlslice_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_3_0 || ORIG_REF_NAME==design_1_xlslice_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wizard_0_0/design_1_clk_wizard_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wizard_0_0 || ORIG_REF_NAME==design_1_clk_wizard_0_0} -quiet] -quiet

# XDC: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_versal_cips_0_0/bd_0/ip/ip_0/bd_70da_pspmc_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_70da_pspmc_0_0 || ORIG_REF_NAME==bd_70da_pspmc_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_versal_cips_0_0/bd_0/ip/ip_0/pspmc_v1_2/constraints/usr_constraints.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_70da_pspmc_0_0 || ORIG_REF_NAME==bd_70da_pspmc_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_versal_cips_0_0/bd_0/bd_70da_ooc.xdc

# XDC: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/design_1_ooc.xdc
