vlib work
vlib riviera

vlib riviera/xilinx_vip
vlib riviera/xpm
vlib riviera/smartconnect_v1_0
vlib riviera/axi_infrastructure_v1_1_0
vlib riviera/axi_register_slice_v2_1_26
vlib riviera/axi_vip_v1_1_12
vlib riviera/lib_cdc_v1_0_2
vlib riviera/proc_sys_reset_v5_0_13
vlib riviera/xlconstant_v1_1_7
vlib riviera/versal_cips_ps_vip_v1_0_4
vlib riviera/xil_defaultlib
vlib riviera/cpm4_v1_0_7
vlib riviera/cpm5_v1_0_7
vlib riviera/axi_lite_ipif_v3_0_4
vlib riviera/interrupt_control_v3_1_4
vlib riviera/axi_gpio_v2_0_28
vlib riviera/lib_pkg_v1_0_2
vlib riviera/lib_srl_fifo_v1_0_2
vlib riviera/axi_uartlite_v2_0_30
vlib riviera/xlslice_v1_0_2

vmap xilinx_vip riviera/xilinx_vip
vmap xpm riviera/xpm
vmap smartconnect_v1_0 riviera/smartconnect_v1_0
vmap axi_infrastructure_v1_1_0 riviera/axi_infrastructure_v1_1_0
vmap axi_register_slice_v2_1_26 riviera/axi_register_slice_v2_1_26
vmap axi_vip_v1_1_12 riviera/axi_vip_v1_1_12
vmap lib_cdc_v1_0_2 riviera/lib_cdc_v1_0_2
vmap proc_sys_reset_v5_0_13 riviera/proc_sys_reset_v5_0_13
vmap xlconstant_v1_1_7 riviera/xlconstant_v1_1_7
vmap versal_cips_ps_vip_v1_0_4 riviera/versal_cips_ps_vip_v1_0_4
vmap xil_defaultlib riviera/xil_defaultlib
vmap cpm4_v1_0_7 riviera/cpm4_v1_0_7
vmap cpm5_v1_0_7 riviera/cpm5_v1_0_7
vmap axi_lite_ipif_v3_0_4 riviera/axi_lite_ipif_v3_0_4
vmap interrupt_control_v3_1_4 riviera/interrupt_control_v3_1_4
vmap axi_gpio_v2_0_28 riviera/axi_gpio_v2_0_28
vmap lib_pkg_v1_0_2 riviera/lib_pkg_v1_0_2
vmap lib_srl_fifo_v1_0_2 riviera/lib_srl_fifo_v1_0_2
vmap axi_uartlite_v2_0_30 riviera/axi_uartlite_v2_0_30
vmap xlslice_v1_0_2 riviera/xlslice_v1_0_2

vlog -work xilinx_vip  -sv2k12 "+incdir+/media/dewsjoe/Data/Vitis_2022_1/Vivado/2022.1/data/xilinx_vip/include" \
"/media/dewsjoe/Data/Vitis_2022_1/Vivado/2022.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
"/media/dewsjoe/Data/Vitis_2022_1/Vivado/2022.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
"/media/dewsjoe/Data/Vitis_2022_1/Vivado/2022.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
"/media/dewsjoe/Data/Vitis_2022_1/Vivado/2022.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
"/media/dewsjoe/Data/Vitis_2022_1/Vivado/2022.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
"/media/dewsjoe/Data/Vitis_2022_1/Vivado/2022.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
"/media/dewsjoe/Data/Vitis_2022_1/Vivado/2022.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
"/media/dewsjoe/Data/Vitis_2022_1/Vivado/2022.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
"/media/dewsjoe/Data/Vitis_2022_1/Vivado/2022.1/data/xilinx_vip/hdl/rst_vip_if.sv" \

vlog -work xpm  -sv2k12 "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/6eab/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/9af9/ttcl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f8e8/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/cc35/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_3/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_4/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_5/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_6/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_8/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ef1d/hdl/rtl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+/media/dewsjoe/Data/Vitis_2022_1/Vivado/2022.1/data/xilinx_vip/include" \
"/media/dewsjoe/Data/Vitis_2022_1/Vivado/2022.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"/media/dewsjoe/Data/Vitis_2022_1/Vivado/2022.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"/media/dewsjoe/Data/Vitis_2022_1/Vivado/2022.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm -93 \
"/media/dewsjoe/Data/Vitis_2022_1/Vivado/2022.1/data/ip/xpm/xpm_VCOMP.vhd" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/6eab/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/9af9/ttcl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f8e8/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/cc35/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_3/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_4/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_5/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_6/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_8/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ef1d/hdl/rtl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+/media/dewsjoe/Data/Vitis_2022_1/Vivado/2022.1/data/xilinx_vip/include" \
"../../../../project_3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
"../../../../project_3.gen/sources_1/bd/design_1/ipshared/ea34/hdl/sc_mmu_v1_0_vl_rfs.sv" \
"../../../../project_3.gen/sources_1/bd/design_1/ipshared/4fd2/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
"../../../../project_3.gen/sources_1/bd/design_1/ipshared/8047/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
"../../../../project_3.gen/sources_1/bd/design_1/ipshared/66be/hdl/sc_node_v1_0_vl_rfs.sv" \
"../../../../project_3.gen/sources_1/bd/design_1/ipshared/c012/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
"../../../../project_3.gen/sources_1/bd/design_1/ipshared/f38e/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
"../../../../project_3.gen/sources_1/bd/design_1/ipshared/9cc5/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
"../../../../project_3.gen/sources_1/bd/design_1/ipshared/6bba/hdl/sc_exit_v1_0_vl_rfs.sv" \

vlog -work axi_infrastructure_v1_1_0  -v2k5 "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/6eab/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/9af9/ttcl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f8e8/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/cc35/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_3/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_4/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_5/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_6/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_8/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ef1d/hdl/rtl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+/media/dewsjoe/Data/Vitis_2022_1/Vivado/2022.1/data/xilinx_vip/include" \
"../../../../project_3.gen/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work axi_register_slice_v2_1_26  -v2k5 "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/6eab/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/9af9/ttcl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f8e8/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/cc35/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_3/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_4/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_5/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_6/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_8/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ef1d/hdl/rtl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+/media/dewsjoe/Data/Vitis_2022_1/Vivado/2022.1/data/xilinx_vip/include" \
"../../../../project_3.gen/sources_1/bd/design_1/ipshared/0a3f/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work axi_vip_v1_1_12  -sv2k12 "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/6eab/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/9af9/ttcl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f8e8/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/cc35/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_3/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_4/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_5/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_6/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_8/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ef1d/hdl/rtl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+/media/dewsjoe/Data/Vitis_2022_1/Vivado/2022.1/data/xilinx_vip/include" \
"../../../../project_3.gen/sources_1/bd/design_1/ipshared/1033/hdl/axi_vip_v1_1_vl_rfs.sv" \

vcom -work lib_cdc_v1_0_2 -93 \
"../../../../project_3.gen/sources_1/bd/design_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \

vcom -work proc_sys_reset_v5_0_13 -93 \
"../../../../project_3.gen/sources_1/bd/design_1/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vlog -work xlconstant_v1_1_7  -v2k5 "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/6eab/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/9af9/ttcl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f8e8/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/cc35/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_3/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_4/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_5/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_6/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_8/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ef1d/hdl/rtl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+/media/dewsjoe/Data/Vitis_2022_1/Vivado/2022.1/data/xilinx_vip/include" \
"../../../../project_3.gen/sources_1/bd/design_1/ipshared/fcfc/hdl/xlconstant_v1_1_vl_rfs.v" \

vlog -work versal_cips_ps_vip_v1_0_4  -sv2k12 "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/6eab/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/9af9/ttcl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f8e8/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/cc35/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_3/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_4/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_5/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_6/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_8/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ef1d/hdl/rtl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+/media/dewsjoe/Data/Vitis_2022_1/Vivado/2022.1/data/xilinx_vip/include" \
"../../../../project_3.gen/sources_1/bd/design_1/ipshared/6eab/hdl/versal_cips_ps_vip_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/6eab/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/9af9/ttcl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f8e8/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/cc35/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_3/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_4/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_5/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_6/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_8/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ef1d/hdl/rtl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+/media/dewsjoe/Data/Vitis_2022_1/Vivado/2022.1/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_versal_cips_0_0/bd_0/ip/ip_0/ip_0/sim/versal_cips_ps_vip_0.sv" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/6eab/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/9af9/ttcl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f8e8/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/cc35/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_3/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_4/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_5/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_6/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_8/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ef1d/hdl/rtl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+/media/dewsjoe/Data/Vitis_2022_1/Vivado/2022.1/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_versal_cips_0_0/bd_0/ip/ip_0/hdl/pspmc_v1_2_0_sim.v" \
"../../../bd/design_1/ip/design_1_versal_cips_0_0/bd_0/ip/ip_0/sim/bd_70da_pspmc_0_0.v" \
"../../../bd/design_1/ip/design_1_versal_cips_0_0/bd_0/sim/bd_70da.v" \

vlog -work cpm4_v1_0_7  -sv2k12 "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/6eab/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/9af9/ttcl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f8e8/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/cc35/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_3/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_4/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_5/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_6/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_8/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ef1d/hdl/rtl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+/media/dewsjoe/Data/Vitis_2022_1/Vivado/2022.1/data/xilinx_vip/include" \
"../../../../project_3.gen/sources_1/bd/design_1/ipshared/f8e8/hdl/cpm4_v1_0_vl_rfs.sv" \

vlog -work cpm5_v1_0_7  -sv2k12 "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/6eab/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/9af9/ttcl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f8e8/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/cc35/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_3/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_4/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_5/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_6/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_8/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ef1d/hdl/rtl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+/media/dewsjoe/Data/Vitis_2022_1/Vivado/2022.1/data/xilinx_vip/include" \
"../../../../project_3.gen/sources_1/bd/design_1/ipshared/cc35/hdl/cpm5_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/6eab/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/9af9/ttcl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f8e8/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/cc35/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_3/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_4/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_5/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_6/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_8/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ef1d/hdl/rtl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+/media/dewsjoe/Data/Vitis_2022_1/Vivado/2022.1/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_versal_cips_0_0/sim/design_1_versal_cips_0_0.sv" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/6eab/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/9af9/ttcl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f8e8/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/cc35/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_3/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_4/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_5/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_6/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_8/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ef1d/hdl/rtl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+/media/dewsjoe/Data/Vitis_2022_1/Vivado/2022.1/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/sim/bd_8be5.v" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/6eab/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/9af9/ttcl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f8e8/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/cc35/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_3/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_4/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_5/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_6/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_8/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ef1d/hdl/rtl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+/media/dewsjoe/Data/Vitis_2022_1/Vivado/2022.1/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/noc_nmu_v1_0_vl_rfs.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm/bd_8be5_S01_AXI_nmu_0_top.sv" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/6eab/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/9af9/ttcl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f8e8/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/cc35/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_3/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_4/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_5/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_6/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_8/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ef1d/hdl/rtl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+/media/dewsjoe/Data/Vitis_2022_1/Vivado/2022.1/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm/NOC_NMU512_SPP.v" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/6eab/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/9af9/ttcl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f8e8/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/cc35/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_3/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_4/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_5/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_6/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_8/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ef1d/hdl/rtl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+/media/dewsjoe/Data/Vitis_2022_1/Vivado/2022.1/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm/bd_8be5_S01_AXI_nmu_0.sv" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/6eab/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/9af9/ttcl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f8e8/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/cc35/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_3/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_4/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_5/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_6/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_8/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ef1d/hdl/rtl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+/media/dewsjoe/Data/Vitis_2022_1/Vivado/2022.1/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_1/sim/bd_8be5_const_0_0.v" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/6eab/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/9af9/ttcl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f8e8/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/cc35/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_3/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_4/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_5/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_6/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_8/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ef1d/hdl/rtl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+/media/dewsjoe/Data/Vitis_2022_1/Vivado/2022.1/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/bfm/bd_8be5_S06_AXI_nmu_0_top.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/bfm/bd_8be5_S06_AXI_nmu_0.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_3/hdl/bfm/bd_8be5_S00_AXI_nmu_0_top.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_3/hdl/bfm/bd_8be5_S00_AXI_nmu_0.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_4/hdl/bfm/bd_8be5_S02_AXI_nmu_0_top.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_4/hdl/bfm/bd_8be5_S02_AXI_nmu_0.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_5/hdl/bfm/bd_8be5_S07_AXI_nmu_0_top.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_5/hdl/bfm/bd_8be5_S07_AXI_nmu_0.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_6/hdl/bfm/bd_8be5_S03_AXI_nmu_0_top.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_6/hdl/bfm/bd_8be5_S03_AXI_nmu_0.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/hdl/bfm/bd_8be5_S05_AXI_nmu_0_top.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/hdl/bfm/bd_8be5_S05_AXI_nmu_0.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_8/hdl/bfm/bd_8be5_S04_AXI_rpu_0_top.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_8/hdl/bfm/bd_8be5_S04_AXI_rpu_0.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/rtl/bd_8be5_MC0_ddrc_0_phy_wrapper.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/bd_8be5_MC0_ddrc_0_phy_ddr_responder.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/noc_mc_ddr4_v1_0_phy_xiphy_behav.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/noc_mc_ddr4_v1_0_dc.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/noc_mc_ddr4_v1_0_ddrmc_wdb.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/ddr4mc_top.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model/ddr_model.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model/ddr_model_wrapper.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na/noc_na_v1_0_vl_rfs.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/bfm/bd_8be5_MC0_ddrc_0_phy.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/hdl/rtl/bd_8be5_MC0_ddrc_0_wrapper.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/hdl/rtl/bd_8be5_MC0_ddrc_0.sv" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/6eab/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/9af9/ttcl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f8e8/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/cc35/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_3/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_4/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_5/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_6/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_8/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ef1d/hdl/rtl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+/media/dewsjoe/Data/Vitis_2022_1/Vivado/2022.1/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/sim/design_1_axi_noc_0_0.v" \
"../../../bd/design_1/sim/design_1.v" \

vcom -work axi_lite_ipif_v3_0_4 -93 \
"../../../../project_3.gen/sources_1/bd/design_1/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \

vcom -work interrupt_control_v3_1_4 -93 \
"../../../../project_3.gen/sources_1/bd/design_1/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \

vcom -work axi_gpio_v2_0_28 -93 \
"../../../../project_3.gen/sources_1/bd/design_1/ipshared/3ed9/hdl/axi_gpio_v2_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93 \
"../../../bd/design_1/ip/design_1_axi_gpio_0_0/sim/design_1_axi_gpio_0_0.vhd" \
"../../../bd/design_1/ip/design_1_axi_gpio_1_0/sim/design_1_axi_gpio_1_0.vhd" \

vcom -work lib_pkg_v1_0_2 -93 \
"../../../../project_3.gen/sources_1/bd/design_1/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \

vcom -work lib_srl_fifo_v1_0_2 -93 \
"../../../../project_3.gen/sources_1/bd/design_1/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \

vcom -work axi_uartlite_v2_0_30 -93 \
"../../../../project_3.gen/sources_1/bd/design_1/ipshared/5d2b/hdl/axi_uartlite_v2_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93 \
"../../../bd/design_1/ip/design_1_axi_uartlite_0_0/sim/design_1_axi_uartlite_0_0.vhd" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/6eab/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/9af9/ttcl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f8e8/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/cc35/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_3/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_4/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_5/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_6/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_8/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ef1d/hdl/rtl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+/media/dewsjoe/Data/Vitis_2022_1/Vivado/2022.1/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_0/sim/bd_afc3_one_0.v" \

vcom -work xil_defaultlib -93 \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_1/sim/bd_afc3_psr_aclk_0.vhd" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/6eab/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/9af9/ttcl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f8e8/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/cc35/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_3/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_4/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_5/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_6/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_8/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ef1d/hdl/rtl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+/media/dewsjoe/Data/Vitis_2022_1/Vivado/2022.1/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_2/sim/bd_afc3_arinsw_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_3/sim/bd_afc3_rinsw_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_4/sim/bd_afc3_awinsw_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_5/sim/bd_afc3_winsw_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_6/sim/bd_afc3_binsw_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_7/sim/bd_afc3_aroutsw_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_8/sim/bd_afc3_routsw_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_9/sim/bd_afc3_awoutsw_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_10/sim/bd_afc3_woutsw_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_11/sim/bd_afc3_boutsw_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_12/sim/bd_afc3_arni_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_13/sim/bd_afc3_rni_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_14/sim/bd_afc3_awni_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_15/sim/bd_afc3_wni_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_16/sim/bd_afc3_bni_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_17/sim/bd_afc3_s00mmu_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_18/sim/bd_afc3_s00tr_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_19/sim/bd_afc3_s00sic_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_20/sim/bd_afc3_s00a2s_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_21/sim/bd_afc3_sarn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_22/sim/bd_afc3_srn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_23/sim/bd_afc3_sawn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_24/sim/bd_afc3_swn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_25/sim/bd_afc3_sbn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_26/sim/bd_afc3_m00s2a_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_27/sim/bd_afc3_m00arn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_28/sim/bd_afc3_m00rn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_29/sim/bd_afc3_m00awn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_30/sim/bd_afc3_m00wn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_31/sim/bd_afc3_m00bn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_32/sim/bd_afc3_m00e_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_33/sim/bd_afc3_m01s2a_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_34/sim/bd_afc3_m01arn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_35/sim/bd_afc3_m01rn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_36/sim/bd_afc3_m01awn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_37/sim/bd_afc3_m01wn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_38/sim/bd_afc3_m01bn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_39/sim/bd_afc3_m01e_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_40/sim/bd_afc3_m02s2a_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_41/sim/bd_afc3_m02arn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_42/sim/bd_afc3_m02rn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_43/sim/bd_afc3_m02awn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_44/sim/bd_afc3_m02wn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_45/sim/bd_afc3_m02bn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_46/sim/bd_afc3_m02e_0.sv" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/6eab/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/9af9/ttcl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f8e8/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/cc35/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_3/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_4/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_5/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_6/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_8/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ef1d/hdl/rtl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+/media/dewsjoe/Data/Vitis_2022_1/Vivado/2022.1/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/sim/bd_afc3.v" \
"../../../bd/design_1/ip/design_1_axi_smc_0/sim/design_1_axi_smc_0.v" \

vcom -work xil_defaultlib -93 \
"../../../bd/design_1/ip/design_1_rst_versal_cips_0_295M_0/sim/design_1_rst_versal_cips_0_295M_0.vhd" \

vlog -work xlslice_v1_0_2  -v2k5 "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/6eab/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/9af9/ttcl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f8e8/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/cc35/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_3/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_4/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_5/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_6/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_8/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ef1d/hdl/rtl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+/media/dewsjoe/Data/Vitis_2022_1/Vivado/2022.1/data/xilinx_vip/include" \
"../../../../project_3.gen/sources_1/bd/design_1/ipshared/11d0/hdl/xlslice_v1_0_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/6eab/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/9af9/ttcl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f8e8/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/cc35/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_3/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_4/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_5/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_6/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_8/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ef1d/hdl/rtl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+/media/dewsjoe/Data/Vitis_2022_1/Vivado/2022.1/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_xlslice_0_0/sim/design_1_xlslice_0_0.v" \
"../../../bd/design_1/ip/design_1_xlslice_1_0/sim/design_1_xlslice_1_0.v" \
"../../../bd/design_1/ip/design_1_xlslice_2_0/sim/design_1_xlslice_2_0.v" \
"../../../bd/design_1/ip/design_1_xlslice_3_0/sim/design_1_xlslice_3_0.v" \
"../../../bd/design_1/ip/design_1_clk_wizard_0_0/design_1_clk_wizard_0_0_clocking_structure.v" \
"../../../bd/design_1/ip/design_1_clk_wizard_0_0/design_1_clk_wizard_0_0_clocking_MBUFGCE_CE_DLY.v" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/6eab/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/9af9/ttcl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f8e8/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/cc35/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_3/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_4/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_5/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_6/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_8/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ef1d/hdl/rtl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+/media/dewsjoe/Data/Vitis_2022_1/Vivado/2022.1/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_clk_wizard_0_0/design_1_clk_wizard_0_0_clocking_cmt_dpll_fd_cal.sv" \
"../../../bd/design_1/ip/design_1_clk_wizard_0_0/design_1_clk_wizard_0_0_clocking_Synchronizer3.sv" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/6eab/hdl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/9af9/ttcl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/f8e8/hdl/verilog" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/cc35/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_3/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_4/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_5/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_6/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_8/hdl/bfm" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/ddr4" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/hdl/noc_na" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ipshared/ef1d/hdl/rtl" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/h_files" "+incdir+../../../../project_3.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0" "+incdir+/media/dewsjoe/Data/Vitis_2022_1/Vivado/2022.1/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_clk_wizard_0_0/design_1_clk_wizard_0_0_clk_wiz_top.v" \
"../../../bd/design_1/ip/design_1_clk_wizard_0_0/sim/design_1_clk_wizard_0_0.v" \

vlog -work xil_defaultlib \
"glbl.v"

