-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2022.2 (lin64) Build 3671981 Fri Oct 14 04:59:54 MDT 2022
-- Date        : Wed Mar 27 13:00:34 2024
-- Host        : epics-X9DAi running 64-bit Ubuntu 22.04.2 LTS
-- Command     : write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix
--               decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ system_gt_bridge_ip_0_0_stub.vhdl
-- Design      : system_gt_bridge_ip_0_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xcvc1902-vsva2197-2MP-e-S
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  Port ( 
    gt_ilo_reset : out STD_LOGIC;
    gt_pll_reset : out STD_LOGIC;
    ch0_txdata : out STD_LOGIC_VECTOR ( 127 downto 0 );
    ch0_txbufstatus : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_txpmaresetmask : out STD_LOGIC_VECTOR ( 2 downto 0 );
    ch0_txpostcursor : out STD_LOGIC_VECTOR ( 4 downto 0 );
    ch0_txprecursor : out STD_LOGIC_VECTOR ( 4 downto 0 );
    ch0_txheader : out STD_LOGIC_VECTOR ( 5 downto 0 );
    ch0_txsequence : out STD_LOGIC_VECTOR ( 6 downto 0 );
    ch0_gttxreset : out STD_LOGIC;
    ch0_txprogdivreset : out STD_LOGIC;
    ch0_txuserrdy : out STD_LOGIC;
    ch0_txphalignresetmask : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_txcominit : out STD_LOGIC;
    ch0_txcomsas : out STD_LOGIC;
    ch0_txcomwake : out STD_LOGIC;
    ch0_txdapicodeovrden : out STD_LOGIC;
    ch0_txdapicodereset : out STD_LOGIC;
    ch0_txdetectrx : out STD_LOGIC;
    ch0_txdlyalignreq : out STD_LOGIC;
    ch0_txelecidle : out STD_LOGIC;
    ch0_txinhibit : out STD_LOGIC;
    ch0_txmldchaindone : out STD_LOGIC;
    ch0_txmldchainreq : out STD_LOGIC;
    ch0_txoneszeros : out STD_LOGIC;
    ch0_txpausedelayalign : out STD_LOGIC;
    ch0_txpcsresetmask : out STD_LOGIC;
    ch0_txphalignreq : out STD_LOGIC;
    ch0_txphdlypd : out STD_LOGIC;
    ch0_txphdlyreset : out STD_LOGIC;
    ch0_txphsetinitreq : out STD_LOGIC;
    ch0_txphshift180 : out STD_LOGIC;
    ch0_txpicodeovrden : out STD_LOGIC;
    ch0_txpicodereset : out STD_LOGIC;
    ch0_txpippmen : out STD_LOGIC;
    ch0_txpisopd : out STD_LOGIC;
    ch0_txpolarity : out STD_LOGIC;
    ch0_txprbsforceerr : out STD_LOGIC;
    ch0_txswing : out STD_LOGIC;
    ch0_txsyncallin : out STD_LOGIC;
    ch0_tx10gstat : in STD_LOGIC;
    ch0_txcomfinish : in STD_LOGIC;
    ch0_txdccdone : in STD_LOGIC;
    ch0_txdlyalignerr : in STD_LOGIC;
    ch0_txdlyalignprog : in STD_LOGIC;
    ch0_txphaligndone : in STD_LOGIC;
    ch0_txphalignerr : in STD_LOGIC;
    ch0_txphalignoutrsvd : in STD_LOGIC;
    ch0_txphdlyresetdone : in STD_LOGIC;
    ch0_txphsetinitdone : in STD_LOGIC;
    ch0_txphshift180done : in STD_LOGIC;
    ch0_txsyncdone : in STD_LOGIC;
    ch0_txctrl0 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    ch0_txctrl1 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    ch0_txdeemph : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_txpd : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_txresetmode : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_txmstreset : out STD_LOGIC;
    ch0_txmstdatapathreset : out STD_LOGIC;
    ch0_txmstresetdone : in STD_LOGIC;
    ch0_txmargin : out STD_LOGIC_VECTOR ( 2 downto 0 );
    ch0_txprbssel : out STD_LOGIC_VECTOR ( 3 downto 0 );
    ch0_txdiffctrl : out STD_LOGIC_VECTOR ( 4 downto 0 );
    ch0_txpippmstepsize : out STD_LOGIC_VECTOR ( 4 downto 0 );
    ch0_txmaincursor : out STD_LOGIC_VECTOR ( 6 downto 0 );
    ch0_txctrl2 : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch0_txdataextendrsvd : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch0_txrate : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch0_txprogdivresetdone : in STD_LOGIC;
    ch0_txpmaresetdone : in STD_LOGIC;
    ch0_txresetdone : in STD_LOGIC;
    ch0_txdata_ext : in STD_LOGIC_VECTOR ( 127 downto 0 );
    ch0_txbufstatus_ext : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_txpmaresetmask_ext : in STD_LOGIC_VECTOR ( 2 downto 0 );
    ch0_txpostcursor_ext : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch0_txprecursor_ext : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch0_txheader_ext : in STD_LOGIC_VECTOR ( 5 downto 0 );
    ch0_txsequence_ext : in STD_LOGIC_VECTOR ( 6 downto 0 );
    ch0_txphalignresetmask_ext : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_txcominit_ext : in STD_LOGIC;
    ch0_txcomsas_ext : in STD_LOGIC;
    ch0_txcomwake_ext : in STD_LOGIC;
    ch0_txdapicodeovrden_ext : in STD_LOGIC;
    ch0_txdapicodereset_ext : in STD_LOGIC;
    ch0_txdetectrx_ext : in STD_LOGIC;
    ch0_txdlyalignreq_ext : in STD_LOGIC;
    ch0_txelecidle_ext : in STD_LOGIC;
    ch0_txinhibit_ext : in STD_LOGIC;
    ch0_txmldchaindone_ext : in STD_LOGIC;
    ch0_txmldchainreq_ext : in STD_LOGIC;
    ch0_txoneszeros_ext : in STD_LOGIC;
    ch0_txpausedelayalign_ext : in STD_LOGIC;
    ch0_txpcsresetmask_ext : in STD_LOGIC;
    ch0_txphalignreq_ext : in STD_LOGIC;
    ch0_txphdlypd_ext : in STD_LOGIC;
    ch0_txphdlyreset_ext : in STD_LOGIC;
    ch0_txphsetinitreq_ext : in STD_LOGIC;
    ch0_txphshift180_ext : in STD_LOGIC;
    ch0_txpicodeovrden_ext : in STD_LOGIC;
    ch0_txpicodereset_ext : in STD_LOGIC;
    ch0_txpippmen_ext : in STD_LOGIC;
    ch0_txpisopd_ext : in STD_LOGIC;
    ch0_txpolarity_ext : in STD_LOGIC;
    ch0_txprbsforceerr_ext : in STD_LOGIC;
    ch0_txswing_ext : in STD_LOGIC;
    ch0_txsyncallin_ext : in STD_LOGIC;
    ch0_tx10gstat_ext : out STD_LOGIC;
    ch0_txcomfinish_ext : out STD_LOGIC;
    ch0_txdccdone_ext : out STD_LOGIC;
    ch0_txdlyalignerr_ext : out STD_LOGIC;
    ch0_txdlyalignprog_ext : out STD_LOGIC;
    ch0_txphaligndone_ext : out STD_LOGIC;
    ch0_txphalignerr_ext : out STD_LOGIC;
    ch0_txphalignoutrsvd_ext : out STD_LOGIC;
    ch0_txphdlyresetdone_ext : out STD_LOGIC;
    ch0_txphsetinitdone_ext : out STD_LOGIC;
    ch0_txphshift180done_ext : out STD_LOGIC;
    ch0_txsyncdone_ext : out STD_LOGIC;
    ch0_txctrl0_ext : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ch0_txctrl1_ext : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ch0_txdeemph_ext : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_txpd_ext : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_txresetmode_ext : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_txmstresetdone_ext : out STD_LOGIC;
    ch0_txmargin_ext : in STD_LOGIC_VECTOR ( 2 downto 0 );
    ch0_txprbssel_ext : in STD_LOGIC_VECTOR ( 3 downto 0 );
    ch0_txdiffctrl_ext : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch0_txpippmstepsize_ext : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch0_txmaincursor_ext : in STD_LOGIC_VECTOR ( 6 downto 0 );
    ch0_txctrl2_ext : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch0_txdataextendrsvd_ext : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch0_txprogdivresetdone_ext : out STD_LOGIC;
    ch0_txpmaresetdone_ext : out STD_LOGIC;
    ch0_txresetdone_ext : out STD_LOGIC;
    ch1_txdata : out STD_LOGIC_VECTOR ( 127 downto 0 );
    ch1_txbufstatus : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_txpmaresetmask : out STD_LOGIC_VECTOR ( 2 downto 0 );
    ch1_txpostcursor : out STD_LOGIC_VECTOR ( 4 downto 0 );
    ch1_txprecursor : out STD_LOGIC_VECTOR ( 4 downto 0 );
    ch1_txheader : out STD_LOGIC_VECTOR ( 5 downto 0 );
    ch1_txsequence : out STD_LOGIC_VECTOR ( 6 downto 0 );
    ch1_gttxreset : out STD_LOGIC;
    ch1_txprogdivreset : out STD_LOGIC;
    ch1_txuserrdy : out STD_LOGIC;
    ch1_txphalignresetmask : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_txcominit : out STD_LOGIC;
    ch1_txcomsas : out STD_LOGIC;
    ch1_txcomwake : out STD_LOGIC;
    ch1_txdapicodeovrden : out STD_LOGIC;
    ch1_txdapicodereset : out STD_LOGIC;
    ch1_txdetectrx : out STD_LOGIC;
    ch1_txdlyalignreq : out STD_LOGIC;
    ch1_txelecidle : out STD_LOGIC;
    ch1_txinhibit : out STD_LOGIC;
    ch1_txmldchaindone : out STD_LOGIC;
    ch1_txmldchainreq : out STD_LOGIC;
    ch1_txoneszeros : out STD_LOGIC;
    ch1_txpausedelayalign : out STD_LOGIC;
    ch1_txpcsresetmask : out STD_LOGIC;
    ch1_txphalignreq : out STD_LOGIC;
    ch1_txphdlypd : out STD_LOGIC;
    ch1_txphdlyreset : out STD_LOGIC;
    ch1_txphsetinitreq : out STD_LOGIC;
    ch1_txphshift180 : out STD_LOGIC;
    ch1_txpicodeovrden : out STD_LOGIC;
    ch1_txpicodereset : out STD_LOGIC;
    ch1_txpippmen : out STD_LOGIC;
    ch1_txpisopd : out STD_LOGIC;
    ch1_txpolarity : out STD_LOGIC;
    ch1_txprbsforceerr : out STD_LOGIC;
    ch1_txswing : out STD_LOGIC;
    ch1_txsyncallin : out STD_LOGIC;
    ch1_tx10gstat : in STD_LOGIC;
    ch1_txcomfinish : in STD_LOGIC;
    ch1_txdccdone : in STD_LOGIC;
    ch1_txdlyalignerr : in STD_LOGIC;
    ch1_txdlyalignprog : in STD_LOGIC;
    ch1_txphaligndone : in STD_LOGIC;
    ch1_txphalignerr : in STD_LOGIC;
    ch1_txphalignoutrsvd : in STD_LOGIC;
    ch1_txphdlyresetdone : in STD_LOGIC;
    ch1_txphsetinitdone : in STD_LOGIC;
    ch1_txphshift180done : in STD_LOGIC;
    ch1_txsyncdone : in STD_LOGIC;
    ch1_txctrl0 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    ch1_txctrl1 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    ch1_txdeemph : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_txpd : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_txresetmode : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_txmstreset : out STD_LOGIC;
    ch1_txmstdatapathreset : out STD_LOGIC;
    ch1_txmstresetdone : in STD_LOGIC;
    ch1_txmargin : out STD_LOGIC_VECTOR ( 2 downto 0 );
    ch1_txprbssel : out STD_LOGIC_VECTOR ( 3 downto 0 );
    ch1_txdiffctrl : out STD_LOGIC_VECTOR ( 4 downto 0 );
    ch1_txpippmstepsize : out STD_LOGIC_VECTOR ( 4 downto 0 );
    ch1_txmaincursor : out STD_LOGIC_VECTOR ( 6 downto 0 );
    ch1_txctrl2 : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch1_txdataextendrsvd : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch1_txrate : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch1_txprogdivresetdone : in STD_LOGIC;
    ch1_txpmaresetdone : in STD_LOGIC;
    ch1_txresetdone : in STD_LOGIC;
    ch1_txdata_ext : in STD_LOGIC_VECTOR ( 127 downto 0 );
    ch1_txbufstatus_ext : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_txpmaresetmask_ext : in STD_LOGIC_VECTOR ( 2 downto 0 );
    ch1_txpostcursor_ext : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch1_txprecursor_ext : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch1_txheader_ext : in STD_LOGIC_VECTOR ( 5 downto 0 );
    ch1_txsequence_ext : in STD_LOGIC_VECTOR ( 6 downto 0 );
    ch1_txphalignresetmask_ext : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_txcominit_ext : in STD_LOGIC;
    ch1_txcomsas_ext : in STD_LOGIC;
    ch1_txcomwake_ext : in STD_LOGIC;
    ch1_txdapicodeovrden_ext : in STD_LOGIC;
    ch1_txdapicodereset_ext : in STD_LOGIC;
    ch1_txdetectrx_ext : in STD_LOGIC;
    ch1_txdlyalignreq_ext : in STD_LOGIC;
    ch1_txelecidle_ext : in STD_LOGIC;
    ch1_txinhibit_ext : in STD_LOGIC;
    ch1_txmldchaindone_ext : in STD_LOGIC;
    ch1_txmldchainreq_ext : in STD_LOGIC;
    ch1_txoneszeros_ext : in STD_LOGIC;
    ch1_txpausedelayalign_ext : in STD_LOGIC;
    ch1_txpcsresetmask_ext : in STD_LOGIC;
    ch1_txphalignreq_ext : in STD_LOGIC;
    ch1_txphdlypd_ext : in STD_LOGIC;
    ch1_txphdlyreset_ext : in STD_LOGIC;
    ch1_txphsetinitreq_ext : in STD_LOGIC;
    ch1_txphshift180_ext : in STD_LOGIC;
    ch1_txpicodeovrden_ext : in STD_LOGIC;
    ch1_txpicodereset_ext : in STD_LOGIC;
    ch1_txpippmen_ext : in STD_LOGIC;
    ch1_txpisopd_ext : in STD_LOGIC;
    ch1_txpolarity_ext : in STD_LOGIC;
    ch1_txprbsforceerr_ext : in STD_LOGIC;
    ch1_txswing_ext : in STD_LOGIC;
    ch1_txsyncallin_ext : in STD_LOGIC;
    ch1_tx10gstat_ext : out STD_LOGIC;
    ch1_txcomfinish_ext : out STD_LOGIC;
    ch1_txdccdone_ext : out STD_LOGIC;
    ch1_txdlyalignerr_ext : out STD_LOGIC;
    ch1_txdlyalignprog_ext : out STD_LOGIC;
    ch1_txphaligndone_ext : out STD_LOGIC;
    ch1_txphalignerr_ext : out STD_LOGIC;
    ch1_txphalignoutrsvd_ext : out STD_LOGIC;
    ch1_txphdlyresetdone_ext : out STD_LOGIC;
    ch1_txphsetinitdone_ext : out STD_LOGIC;
    ch1_txphshift180done_ext : out STD_LOGIC;
    ch1_txsyncdone_ext : out STD_LOGIC;
    ch1_txctrl0_ext : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ch1_txctrl1_ext : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ch1_txdeemph_ext : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_txpd_ext : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_txresetmode_ext : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_txmstresetdone_ext : out STD_LOGIC;
    ch1_txmargin_ext : in STD_LOGIC_VECTOR ( 2 downto 0 );
    ch1_txprbssel_ext : in STD_LOGIC_VECTOR ( 3 downto 0 );
    ch1_txdiffctrl_ext : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch1_txpippmstepsize_ext : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch1_txmaincursor_ext : in STD_LOGIC_VECTOR ( 6 downto 0 );
    ch1_txctrl2_ext : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch1_txdataextendrsvd_ext : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch1_txprogdivresetdone_ext : out STD_LOGIC;
    ch1_txpmaresetdone_ext : out STD_LOGIC;
    ch1_txresetdone_ext : out STD_LOGIC;
    ch0_rxdata : in STD_LOGIC_VECTOR ( 127 downto 0 );
    ch0_rxpcsresetmask : out STD_LOGIC_VECTOR ( 4 downto 0 );
    ch0_rxpmaresetmask : out STD_LOGIC_VECTOR ( 6 downto 0 );
    ch0_rxdatavalid : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_rxheader : in STD_LOGIC_VECTOR ( 5 downto 0 );
    ch0_rxgearboxslip : out STD_LOGIC;
    ch0_gtrxreset : out STD_LOGIC;
    ch0_rxprogdivreset : out STD_LOGIC;
    ch0_rxuserrdy : out STD_LOGIC;
    ch0_rxprogdivresetdone : in STD_LOGIC;
    ch0_rxpmaresetdone : in STD_LOGIC;
    ch0_rxresetdone : in STD_LOGIC;
    ch0_rx10gstat : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch0_rxbufstatus : in STD_LOGIC_VECTOR ( 2 downto 0 );
    ch0_rxbyteisaligned : in STD_LOGIC;
    ch0_rxbyterealign : in STD_LOGIC;
    ch0_rxcdrhold : out STD_LOGIC;
    ch0_rxcdrlock : in STD_LOGIC;
    ch0_rxcdrovrden : out STD_LOGIC;
    ch0_rxcdrphdone : in STD_LOGIC;
    ch0_rxcdrreset : out STD_LOGIC;
    ch0_rxchanbondseq : in STD_LOGIC;
    ch0_rxchanisaligned : in STD_LOGIC;
    ch0_rxchanrealign : in STD_LOGIC;
    ch0_rxchbondi : out STD_LOGIC_VECTOR ( 4 downto 0 );
    ch0_rxchbondo : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch0_rxclkcorcnt : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_rxcominitdet : in STD_LOGIC;
    ch0_rxcommadet : in STD_LOGIC;
    ch0_rxcomsasdet : in STD_LOGIC;
    ch0_rxcomwakedet : in STD_LOGIC;
    ch0_rxctrl0 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ch0_rxctrl1 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ch0_rxctrl2 : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch0_rxctrl3 : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch0_rxdapicodeovrden : out STD_LOGIC;
    ch0_rxdapicodereset : out STD_LOGIC;
    ch0_rxdataextendrsvd : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch0_rxdccdone : in STD_LOGIC;
    ch0_rxdlyalignerr : in STD_LOGIC;
    ch0_rxdlyalignprog : in STD_LOGIC;
    ch0_rxdlyalignreq : out STD_LOGIC;
    ch0_rxelecidle : in STD_LOGIC;
    ch0_rxeqtraining : out STD_LOGIC;
    ch0_rxfinealigndone : in STD_LOGIC;
    ch0_rxheadervalid : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_rxlpmen : out STD_LOGIC;
    ch0_rxmldchaindone : out STD_LOGIC;
    ch0_rxmldchainreq : out STD_LOGIC;
    ch0_rxmlfinealignreq : out STD_LOGIC;
    ch0_rxoobreset : out STD_LOGIC;
    ch0_rxosintdone : in STD_LOGIC;
    ch0_rxosintstarted : in STD_LOGIC;
    ch0_rxosintstrobedone : in STD_LOGIC;
    ch0_rxosintstrobestarted : in STD_LOGIC;
    ch0_rxpd : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_rxphaligndone : in STD_LOGIC;
    ch0_rxphalignerr : in STD_LOGIC;
    ch0_rxphalignreq : out STD_LOGIC;
    ch0_rxphalignresetmask : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_rxphdlypd : out STD_LOGIC;
    ch0_rxphdlyreset : out STD_LOGIC;
    ch0_rxphdlyresetdone : in STD_LOGIC;
    ch0_rxphsetinitdone : in STD_LOGIC;
    ch0_rxphsetinitreq : out STD_LOGIC;
    ch0_rxphshift180 : out STD_LOGIC;
    ch0_rxphshift180done : in STD_LOGIC;
    ch0_rxpolarity : out STD_LOGIC;
    ch0_rxprbscntreset : out STD_LOGIC;
    ch0_rxprbserr : in STD_LOGIC;
    ch0_rxprbslocked : in STD_LOGIC;
    ch0_rxprbssel : out STD_LOGIC_VECTOR ( 3 downto 0 );
    ch0_rxrate : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch0_rxresetmode : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_rxmstreset : out STD_LOGIC;
    ch0_rxmstdatapathreset : out STD_LOGIC;
    ch0_rxmstresetdone : in STD_LOGIC;
    ch0_rxslide : out STD_LOGIC;
    ch0_rxsliderdy : in STD_LOGIC;
    ch0_rxstartofseq : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_rxstatus : in STD_LOGIC_VECTOR ( 2 downto 0 );
    ch0_rxsyncallin : out STD_LOGIC;
    ch0_rxsyncdone : in STD_LOGIC;
    ch0_rxtermination : out STD_LOGIC;
    ch0_rxvalid : in STD_LOGIC;
    ch0_cdrbmcdrreq : out STD_LOGIC;
    ch0_cdrfreqos : out STD_LOGIC;
    ch0_cdrincpctrl : out STD_LOGIC;
    ch0_cdrstepdir : out STD_LOGIC;
    ch0_cdrstepsq : out STD_LOGIC;
    ch0_cdrstepsx : out STD_LOGIC;
    ch0_cfokovrdfinish : out STD_LOGIC;
    ch0_cfokovrdpulse : out STD_LOGIC;
    ch0_cfokovrdstart : out STD_LOGIC;
    ch0_eyescanreset : out STD_LOGIC;
    ch0_eyescantrigger : out STD_LOGIC;
    ch0_eyescandataerror : in STD_LOGIC;
    ch0_cfokovrdrdy0 : in STD_LOGIC;
    ch0_cfokovrdrdy1 : in STD_LOGIC;
    ch0_rxdata_ext : out STD_LOGIC_VECTOR ( 127 downto 0 );
    ch0_rxpcsresetmask_ext : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch0_rxpmaresetmask_ext : in STD_LOGIC_VECTOR ( 6 downto 0 );
    ch0_rxdatavalid_ext : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_rxheader_ext : out STD_LOGIC_VECTOR ( 5 downto 0 );
    ch0_rxgearboxslip_ext : in STD_LOGIC;
    ch0_rxprogdivresetdone_ext : out STD_LOGIC;
    ch0_rxpmaresetdone_ext : out STD_LOGIC;
    ch0_rxresetdone_ext : out STD_LOGIC;
    ch0_rx10gstat_ext : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch0_rxbufstatus_ext : out STD_LOGIC_VECTOR ( 2 downto 0 );
    ch0_rxbyteisaligned_ext : out STD_LOGIC;
    ch0_rxbyterealign_ext : out STD_LOGIC;
    ch0_rxcdrhold_ext : in STD_LOGIC;
    ch0_rxcdrlock_ext : out STD_LOGIC;
    ch0_rxcdrovrden_ext : in STD_LOGIC;
    ch0_rxcdrphdone_ext : out STD_LOGIC;
    ch0_rxcdrreset_ext : in STD_LOGIC;
    ch0_rxchanbondseq_ext : out STD_LOGIC;
    ch0_rxchanisaligned_ext : out STD_LOGIC;
    ch0_rxchanrealign_ext : out STD_LOGIC;
    ch0_rxchbondi_ext : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch0_rxchbondo_ext : out STD_LOGIC_VECTOR ( 4 downto 0 );
    ch0_rxclkcorcnt_ext : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_rxcominitdet_ext : out STD_LOGIC;
    ch0_rxcommadet_ext : out STD_LOGIC;
    ch0_rxcomsasdet_ext : out STD_LOGIC;
    ch0_rxcomwakedet_ext : out STD_LOGIC;
    ch0_rxctrl0_ext : out STD_LOGIC_VECTOR ( 15 downto 0 );
    ch0_rxctrl1_ext : out STD_LOGIC_VECTOR ( 15 downto 0 );
    ch0_rxctrl2_ext : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch0_rxctrl3_ext : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch0_rxdapicodeovrden_ext : in STD_LOGIC;
    ch0_rxdapicodereset_ext : in STD_LOGIC;
    ch0_rxdataextendrsvd_ext : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch0_rxdccdone_ext : out STD_LOGIC;
    ch0_rxdlyalignerr_ext : out STD_LOGIC;
    ch0_rxdlyalignprog_ext : out STD_LOGIC;
    ch0_rxdlyalignreq_ext : in STD_LOGIC;
    ch0_rxelecidle_ext : out STD_LOGIC;
    ch0_rxeqtraining_ext : in STD_LOGIC;
    ch0_rxfinealigndone_ext : out STD_LOGIC;
    ch0_rxheadervalid_ext : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_rxlpmen_ext : in STD_LOGIC;
    ch0_rxmldchaindone_ext : in STD_LOGIC;
    ch0_rxmldchainreq_ext : in STD_LOGIC;
    ch0_rxmlfinealignreq_ext : in STD_LOGIC;
    ch0_rxoobreset_ext : in STD_LOGIC;
    ch0_rxosintdone_ext : out STD_LOGIC;
    ch0_rxosintstarted_ext : out STD_LOGIC;
    ch0_rxosintstrobedone_ext : out STD_LOGIC;
    ch0_rxosintstrobestarted_ext : out STD_LOGIC;
    ch0_rxpd_ext : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_rxphaligndone_ext : out STD_LOGIC;
    ch0_rxphalignerr_ext : out STD_LOGIC;
    ch0_rxphalignreq_ext : in STD_LOGIC;
    ch0_rxphalignresetmask_ext : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_rxphdlypd_ext : in STD_LOGIC;
    ch0_rxphdlyreset_ext : in STD_LOGIC;
    ch0_rxphdlyresetdone_ext : out STD_LOGIC;
    ch0_rxphsetinitdone_ext : out STD_LOGIC;
    ch0_rxphsetinitreq_ext : in STD_LOGIC;
    ch0_rxphshift180_ext : in STD_LOGIC;
    ch0_rxphshift180done_ext : out STD_LOGIC;
    ch0_rxpolarity_ext : in STD_LOGIC;
    ch0_rxprbscntreset_ext : in STD_LOGIC;
    ch0_rxprbserr_ext : out STD_LOGIC;
    ch0_rxprbslocked_ext : out STD_LOGIC;
    ch0_rxprbssel_ext : in STD_LOGIC_VECTOR ( 3 downto 0 );
    ch0_rxresetmode_ext : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_rxmstresetdone_ext : out STD_LOGIC;
    ch0_rxslide_ext : in STD_LOGIC;
    ch0_rxsliderdy_ext : out STD_LOGIC;
    ch0_rxstartofseq_ext : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_rxstatus_ext : out STD_LOGIC_VECTOR ( 2 downto 0 );
    ch0_rxsyncallin_ext : in STD_LOGIC;
    ch0_rxsyncdone_ext : out STD_LOGIC;
    ch0_rxtermination_ext : in STD_LOGIC;
    ch0_rxvalid_ext : out STD_LOGIC;
    ch0_cdrbmcdrreq_ext : in STD_LOGIC;
    ch0_cdrfreqos_ext : in STD_LOGIC;
    ch0_cdrincpctrl_ext : in STD_LOGIC;
    ch0_cdrstepdir_ext : in STD_LOGIC;
    ch0_cdrstepsq_ext : in STD_LOGIC;
    ch0_cdrstepsx_ext : in STD_LOGIC;
    ch0_cfokovrdfinish_ext : in STD_LOGIC;
    ch0_cfokovrdpulse_ext : in STD_LOGIC;
    ch0_cfokovrdstart_ext : in STD_LOGIC;
    ch0_eyescanreset_ext : in STD_LOGIC;
    ch0_eyescantrigger_ext : in STD_LOGIC;
    ch0_eyescandataerror_ext : out STD_LOGIC;
    ch0_cfokovrdrdy0_ext : out STD_LOGIC;
    ch0_cfokovrdrdy1_ext : out STD_LOGIC;
    ch1_rxdata : in STD_LOGIC_VECTOR ( 127 downto 0 );
    ch1_rxpcsresetmask : out STD_LOGIC_VECTOR ( 4 downto 0 );
    ch1_rxpmaresetmask : out STD_LOGIC_VECTOR ( 6 downto 0 );
    ch1_rxdatavalid : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_rxheader : in STD_LOGIC_VECTOR ( 5 downto 0 );
    ch1_rxgearboxslip : out STD_LOGIC;
    ch1_gtrxreset : out STD_LOGIC;
    ch1_rxprogdivreset : out STD_LOGIC;
    ch1_rxuserrdy : out STD_LOGIC;
    ch1_rxprogdivresetdone : in STD_LOGIC;
    ch1_rxpmaresetdone : in STD_LOGIC;
    ch1_rxresetdone : in STD_LOGIC;
    ch1_rx10gstat : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch1_rxbufstatus : in STD_LOGIC_VECTOR ( 2 downto 0 );
    ch1_rxbyteisaligned : in STD_LOGIC;
    ch1_rxbyterealign : in STD_LOGIC;
    ch1_rxcdrhold : out STD_LOGIC;
    ch1_rxcdrlock : in STD_LOGIC;
    ch1_rxcdrovrden : out STD_LOGIC;
    ch1_rxcdrphdone : in STD_LOGIC;
    ch1_rxcdrreset : out STD_LOGIC;
    ch1_rxchanbondseq : in STD_LOGIC;
    ch1_rxchanisaligned : in STD_LOGIC;
    ch1_rxchanrealign : in STD_LOGIC;
    ch1_rxchbondi : out STD_LOGIC_VECTOR ( 4 downto 0 );
    ch1_rxchbondo : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch1_rxclkcorcnt : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_rxcominitdet : in STD_LOGIC;
    ch1_rxcommadet : in STD_LOGIC;
    ch1_rxcomsasdet : in STD_LOGIC;
    ch1_rxcomwakedet : in STD_LOGIC;
    ch1_rxctrl0 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ch1_rxctrl1 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ch1_rxctrl2 : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch1_rxctrl3 : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch1_rxdapicodeovrden : out STD_LOGIC;
    ch1_rxdapicodereset : out STD_LOGIC;
    ch1_rxdataextendrsvd : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch1_rxdccdone : in STD_LOGIC;
    ch1_rxdlyalignerr : in STD_LOGIC;
    ch1_rxdlyalignprog : in STD_LOGIC;
    ch1_rxdlyalignreq : out STD_LOGIC;
    ch1_rxelecidle : in STD_LOGIC;
    ch1_rxeqtraining : out STD_LOGIC;
    ch1_rxfinealigndone : in STD_LOGIC;
    ch1_rxheadervalid : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_rxlpmen : out STD_LOGIC;
    ch1_rxmldchaindone : out STD_LOGIC;
    ch1_rxmldchainreq : out STD_LOGIC;
    ch1_rxmlfinealignreq : out STD_LOGIC;
    ch1_rxoobreset : out STD_LOGIC;
    ch1_rxosintdone : in STD_LOGIC;
    ch1_rxosintstarted : in STD_LOGIC;
    ch1_rxosintstrobedone : in STD_LOGIC;
    ch1_rxosintstrobestarted : in STD_LOGIC;
    ch1_rxpd : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_rxphaligndone : in STD_LOGIC;
    ch1_rxphalignerr : in STD_LOGIC;
    ch1_rxphalignreq : out STD_LOGIC;
    ch1_rxphalignresetmask : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_rxphdlypd : out STD_LOGIC;
    ch1_rxphdlyreset : out STD_LOGIC;
    ch1_rxphdlyresetdone : in STD_LOGIC;
    ch1_rxphsetinitdone : in STD_LOGIC;
    ch1_rxphsetinitreq : out STD_LOGIC;
    ch1_rxphshift180 : out STD_LOGIC;
    ch1_rxphshift180done : in STD_LOGIC;
    ch1_rxpolarity : out STD_LOGIC;
    ch1_rxprbscntreset : out STD_LOGIC;
    ch1_rxprbserr : in STD_LOGIC;
    ch1_rxprbslocked : in STD_LOGIC;
    ch1_rxprbssel : out STD_LOGIC_VECTOR ( 3 downto 0 );
    ch1_rxrate : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch1_rxresetmode : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_rxmstreset : out STD_LOGIC;
    ch1_rxmstdatapathreset : out STD_LOGIC;
    ch1_rxmstresetdone : in STD_LOGIC;
    ch1_rxslide : out STD_LOGIC;
    ch1_rxsliderdy : in STD_LOGIC;
    ch1_rxstartofseq : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_rxstatus : in STD_LOGIC_VECTOR ( 2 downto 0 );
    ch1_rxsyncallin : out STD_LOGIC;
    ch1_rxsyncdone : in STD_LOGIC;
    ch1_rxtermination : out STD_LOGIC;
    ch1_rxvalid : in STD_LOGIC;
    ch1_cdrbmcdrreq : out STD_LOGIC;
    ch1_cdrfreqos : out STD_LOGIC;
    ch1_cdrincpctrl : out STD_LOGIC;
    ch1_cdrstepdir : out STD_LOGIC;
    ch1_cdrstepsq : out STD_LOGIC;
    ch1_cdrstepsx : out STD_LOGIC;
    ch1_cfokovrdfinish : out STD_LOGIC;
    ch1_cfokovrdpulse : out STD_LOGIC;
    ch1_cfokovrdstart : out STD_LOGIC;
    ch1_eyescanreset : out STD_LOGIC;
    ch1_eyescantrigger : out STD_LOGIC;
    ch1_eyescandataerror : in STD_LOGIC;
    ch1_cfokovrdrdy0 : in STD_LOGIC;
    ch1_cfokovrdrdy1 : in STD_LOGIC;
    ch1_rxdata_ext : out STD_LOGIC_VECTOR ( 127 downto 0 );
    ch1_rxpcsresetmask_ext : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch1_rxpmaresetmask_ext : in STD_LOGIC_VECTOR ( 6 downto 0 );
    ch1_rxdatavalid_ext : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_rxheader_ext : out STD_LOGIC_VECTOR ( 5 downto 0 );
    ch1_rxgearboxslip_ext : in STD_LOGIC;
    ch1_rxprogdivresetdone_ext : out STD_LOGIC;
    ch1_rxpmaresetdone_ext : out STD_LOGIC;
    ch1_rxresetdone_ext : out STD_LOGIC;
    ch1_rx10gstat_ext : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch1_rxbufstatus_ext : out STD_LOGIC_VECTOR ( 2 downto 0 );
    ch1_rxbyteisaligned_ext : out STD_LOGIC;
    ch1_rxbyterealign_ext : out STD_LOGIC;
    ch1_rxcdrhold_ext : in STD_LOGIC;
    ch1_rxcdrlock_ext : out STD_LOGIC;
    ch1_rxcdrovrden_ext : in STD_LOGIC;
    ch1_rxcdrphdone_ext : out STD_LOGIC;
    ch1_rxcdrreset_ext : in STD_LOGIC;
    ch1_rxchanbondseq_ext : out STD_LOGIC;
    ch1_rxchanisaligned_ext : out STD_LOGIC;
    ch1_rxchanrealign_ext : out STD_LOGIC;
    ch1_rxchbondi_ext : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch1_rxchbondo_ext : out STD_LOGIC_VECTOR ( 4 downto 0 );
    ch1_rxclkcorcnt_ext : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_rxcominitdet_ext : out STD_LOGIC;
    ch1_rxcommadet_ext : out STD_LOGIC;
    ch1_rxcomsasdet_ext : out STD_LOGIC;
    ch1_rxcomwakedet_ext : out STD_LOGIC;
    ch1_rxctrl0_ext : out STD_LOGIC_VECTOR ( 15 downto 0 );
    ch1_rxctrl1_ext : out STD_LOGIC_VECTOR ( 15 downto 0 );
    ch1_rxctrl2_ext : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch1_rxctrl3_ext : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch1_rxdapicodeovrden_ext : in STD_LOGIC;
    ch1_rxdapicodereset_ext : in STD_LOGIC;
    ch1_rxdataextendrsvd_ext : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch1_rxdccdone_ext : out STD_LOGIC;
    ch1_rxdlyalignerr_ext : out STD_LOGIC;
    ch1_rxdlyalignprog_ext : out STD_LOGIC;
    ch1_rxdlyalignreq_ext : in STD_LOGIC;
    ch1_rxelecidle_ext : out STD_LOGIC;
    ch1_rxeqtraining_ext : in STD_LOGIC;
    ch1_rxfinealigndone_ext : out STD_LOGIC;
    ch1_rxheadervalid_ext : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_rxlpmen_ext : in STD_LOGIC;
    ch1_rxmldchaindone_ext : in STD_LOGIC;
    ch1_rxmldchainreq_ext : in STD_LOGIC;
    ch1_rxmlfinealignreq_ext : in STD_LOGIC;
    ch1_rxoobreset_ext : in STD_LOGIC;
    ch1_rxosintdone_ext : out STD_LOGIC;
    ch1_rxosintstarted_ext : out STD_LOGIC;
    ch1_rxosintstrobedone_ext : out STD_LOGIC;
    ch1_rxosintstrobestarted_ext : out STD_LOGIC;
    ch1_rxpd_ext : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_rxphaligndone_ext : out STD_LOGIC;
    ch1_rxphalignerr_ext : out STD_LOGIC;
    ch1_rxphalignreq_ext : in STD_LOGIC;
    ch1_rxphalignresetmask_ext : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_rxphdlypd_ext : in STD_LOGIC;
    ch1_rxphdlyreset_ext : in STD_LOGIC;
    ch1_rxphdlyresetdone_ext : out STD_LOGIC;
    ch1_rxphsetinitdone_ext : out STD_LOGIC;
    ch1_rxphsetinitreq_ext : in STD_LOGIC;
    ch1_rxphshift180_ext : in STD_LOGIC;
    ch1_rxphshift180done_ext : out STD_LOGIC;
    ch1_rxpolarity_ext : in STD_LOGIC;
    ch1_rxprbscntreset_ext : in STD_LOGIC;
    ch1_rxprbserr_ext : out STD_LOGIC;
    ch1_rxprbslocked_ext : out STD_LOGIC;
    ch1_rxprbssel_ext : in STD_LOGIC_VECTOR ( 3 downto 0 );
    ch1_rxresetmode_ext : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_rxmstresetdone_ext : out STD_LOGIC;
    ch1_rxslide_ext : in STD_LOGIC;
    ch1_rxsliderdy_ext : out STD_LOGIC;
    ch1_rxstartofseq_ext : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_rxstatus_ext : out STD_LOGIC_VECTOR ( 2 downto 0 );
    ch1_rxsyncallin_ext : in STD_LOGIC;
    ch1_rxsyncdone_ext : out STD_LOGIC;
    ch1_rxtermination_ext : in STD_LOGIC;
    ch1_rxvalid_ext : out STD_LOGIC;
    ch1_cdrbmcdrreq_ext : in STD_LOGIC;
    ch1_cdrfreqos_ext : in STD_LOGIC;
    ch1_cdrincpctrl_ext : in STD_LOGIC;
    ch1_cdrstepdir_ext : in STD_LOGIC;
    ch1_cdrstepsq_ext : in STD_LOGIC;
    ch1_cdrstepsx_ext : in STD_LOGIC;
    ch1_cfokovrdfinish_ext : in STD_LOGIC;
    ch1_cfokovrdpulse_ext : in STD_LOGIC;
    ch1_cfokovrdstart_ext : in STD_LOGIC;
    ch1_eyescanreset_ext : in STD_LOGIC;
    ch1_eyescantrigger_ext : in STD_LOGIC;
    ch1_eyescandataerror_ext : out STD_LOGIC;
    ch1_cfokovrdrdy0_ext : out STD_LOGIC;
    ch1_cfokovrdrdy1_ext : out STD_LOGIC;
    gt_txusrclk : in STD_LOGIC;
    gt_rxusrclk : in STD_LOGIC;
    apb3clk : in STD_LOGIC;
    gtpowergood : in STD_LOGIC;
    gt_lcpll_lock : in STD_LOGIC;
    gt_rpll_lock : in STD_LOGIC;
    ch_phystatus_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ilo_resetdone : in STD_LOGIC;
    rx_clr_out : out STD_LOGIC;
    rx_clrb_leaf_out : out STD_LOGIC;
    tx_clr_out : out STD_LOGIC;
    tx_clrb_leaf_out : out STD_LOGIC;
    link_status_out : out STD_LOGIC;
    gpio_enable : in STD_LOGIC;
    tx_resetdone_out : out STD_LOGIC;
    rx_resetdone_out : out STD_LOGIC;
    txusrclk_out : out STD_LOGIC;
    rxusrclk_out : out STD_LOGIC;
    rpll_lock_out : out STD_LOGIC;
    lcpll_lock_out : out STD_LOGIC;
    pcie_rstb : out STD_LOGIC;
    gpi_out : out STD_LOGIC;
    gpo_in : in STD_LOGIC;
    gtreset_in : in STD_LOGIC;
    rate_sel : in STD_LOGIC_VECTOR ( 3 downto 0 );
    reset_mask : out STD_LOGIC_VECTOR ( 1 downto 0 );
    reset_tx_pll_and_datapath_in : in STD_LOGIC;
    reset_tx_datapath_in : in STD_LOGIC;
    reset_rx_pll_and_datapath_in : in STD_LOGIC;
    reset_rx_datapath_in : in STD_LOGIC
  );

end decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix;

architecture stub of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
attribute syn_black_box : boolean;
attribute black_box_pad_pin : string;
attribute syn_black_box of stub : architecture is true;
attribute black_box_pad_pin of stub : architecture is "gt_ilo_reset,gt_pll_reset,ch0_txdata[127:0],ch0_txbufstatus[1:0],ch0_txpmaresetmask[2:0],ch0_txpostcursor[4:0],ch0_txprecursor[4:0],ch0_txheader[5:0],ch0_txsequence[6:0],ch0_gttxreset,ch0_txprogdivreset,ch0_txuserrdy,ch0_txphalignresetmask[1:0],ch0_txcominit,ch0_txcomsas,ch0_txcomwake,ch0_txdapicodeovrden,ch0_txdapicodereset,ch0_txdetectrx,ch0_txdlyalignreq,ch0_txelecidle,ch0_txinhibit,ch0_txmldchaindone,ch0_txmldchainreq,ch0_txoneszeros,ch0_txpausedelayalign,ch0_txpcsresetmask,ch0_txphalignreq,ch0_txphdlypd,ch0_txphdlyreset,ch0_txphsetinitreq,ch0_txphshift180,ch0_txpicodeovrden,ch0_txpicodereset,ch0_txpippmen,ch0_txpisopd,ch0_txpolarity,ch0_txprbsforceerr,ch0_txswing,ch0_txsyncallin,ch0_tx10gstat,ch0_txcomfinish,ch0_txdccdone,ch0_txdlyalignerr,ch0_txdlyalignprog,ch0_txphaligndone,ch0_txphalignerr,ch0_txphalignoutrsvd,ch0_txphdlyresetdone,ch0_txphsetinitdone,ch0_txphshift180done,ch0_txsyncdone,ch0_txctrl0[15:0],ch0_txctrl1[15:0],ch0_txdeemph[1:0],ch0_txpd[1:0],ch0_txresetmode[1:0],ch0_txmstreset,ch0_txmstdatapathreset,ch0_txmstresetdone,ch0_txmargin[2:0],ch0_txprbssel[3:0],ch0_txdiffctrl[4:0],ch0_txpippmstepsize[4:0],ch0_txmaincursor[6:0],ch0_txctrl2[7:0],ch0_txdataextendrsvd[7:0],ch0_txrate[7:0],ch0_txprogdivresetdone,ch0_txpmaresetdone,ch0_txresetdone,ch0_txdata_ext[127:0],ch0_txbufstatus_ext[1:0],ch0_txpmaresetmask_ext[2:0],ch0_txpostcursor_ext[4:0],ch0_txprecursor_ext[4:0],ch0_txheader_ext[5:0],ch0_txsequence_ext[6:0],ch0_txphalignresetmask_ext[1:0],ch0_txcominit_ext,ch0_txcomsas_ext,ch0_txcomwake_ext,ch0_txdapicodeovrden_ext,ch0_txdapicodereset_ext,ch0_txdetectrx_ext,ch0_txdlyalignreq_ext,ch0_txelecidle_ext,ch0_txinhibit_ext,ch0_txmldchaindone_ext,ch0_txmldchainreq_ext,ch0_txoneszeros_ext,ch0_txpausedelayalign_ext,ch0_txpcsresetmask_ext,ch0_txphalignreq_ext,ch0_txphdlypd_ext,ch0_txphdlyreset_ext,ch0_txphsetinitreq_ext,ch0_txphshift180_ext,ch0_txpicodeovrden_ext,ch0_txpicodereset_ext,ch0_txpippmen_ext,ch0_txpisopd_ext,ch0_txpolarity_ext,ch0_txprbsforceerr_ext,ch0_txswing_ext,ch0_txsyncallin_ext,ch0_tx10gstat_ext,ch0_txcomfinish_ext,ch0_txdccdone_ext,ch0_txdlyalignerr_ext,ch0_txdlyalignprog_ext,ch0_txphaligndone_ext,ch0_txphalignerr_ext,ch0_txphalignoutrsvd_ext,ch0_txphdlyresetdone_ext,ch0_txphsetinitdone_ext,ch0_txphshift180done_ext,ch0_txsyncdone_ext,ch0_txctrl0_ext[15:0],ch0_txctrl1_ext[15:0],ch0_txdeemph_ext[1:0],ch0_txpd_ext[1:0],ch0_txresetmode_ext[1:0],ch0_txmstresetdone_ext,ch0_txmargin_ext[2:0],ch0_txprbssel_ext[3:0],ch0_txdiffctrl_ext[4:0],ch0_txpippmstepsize_ext[4:0],ch0_txmaincursor_ext[6:0],ch0_txctrl2_ext[7:0],ch0_txdataextendrsvd_ext[7:0],ch0_txprogdivresetdone_ext,ch0_txpmaresetdone_ext,ch0_txresetdone_ext,ch1_txdata[127:0],ch1_txbufstatus[1:0],ch1_txpmaresetmask[2:0],ch1_txpostcursor[4:0],ch1_txprecursor[4:0],ch1_txheader[5:0],ch1_txsequence[6:0],ch1_gttxreset,ch1_txprogdivreset,ch1_txuserrdy,ch1_txphalignresetmask[1:0],ch1_txcominit,ch1_txcomsas,ch1_txcomwake,ch1_txdapicodeovrden,ch1_txdapicodereset,ch1_txdetectrx,ch1_txdlyalignreq,ch1_txelecidle,ch1_txinhibit,ch1_txmldchaindone,ch1_txmldchainreq,ch1_txoneszeros,ch1_txpausedelayalign,ch1_txpcsresetmask,ch1_txphalignreq,ch1_txphdlypd,ch1_txphdlyreset,ch1_txphsetinitreq,ch1_txphshift180,ch1_txpicodeovrden,ch1_txpicodereset,ch1_txpippmen,ch1_txpisopd,ch1_txpolarity,ch1_txprbsforceerr,ch1_txswing,ch1_txsyncallin,ch1_tx10gstat,ch1_txcomfinish,ch1_txdccdone,ch1_txdlyalignerr,ch1_txdlyalignprog,ch1_txphaligndone,ch1_txphalignerr,ch1_txphalignoutrsvd,ch1_txphdlyresetdone,ch1_txphsetinitdone,ch1_txphshift180done,ch1_txsyncdone,ch1_txctrl0[15:0],ch1_txctrl1[15:0],ch1_txdeemph[1:0],ch1_txpd[1:0],ch1_txresetmode[1:0],ch1_txmstreset,ch1_txmstdatapathreset,ch1_txmstresetdone,ch1_txmargin[2:0],ch1_txprbssel[3:0],ch1_txdiffctrl[4:0],ch1_txpippmstepsize[4:0],ch1_txmaincursor[6:0],ch1_txctrl2[7:0],ch1_txdataextendrsvd[7:0],ch1_txrate[7:0],ch1_txprogdivresetdone,ch1_txpmaresetdone,ch1_txresetdone,ch1_txdata_ext[127:0],ch1_txbufstatus_ext[1:0],ch1_txpmaresetmask_ext[2:0],ch1_txpostcursor_ext[4:0],ch1_txprecursor_ext[4:0],ch1_txheader_ext[5:0],ch1_txsequence_ext[6:0],ch1_txphalignresetmask_ext[1:0],ch1_txcominit_ext,ch1_txcomsas_ext,ch1_txcomwake_ext,ch1_txdapicodeovrden_ext,ch1_txdapicodereset_ext,ch1_txdetectrx_ext,ch1_txdlyalignreq_ext,ch1_txelecidle_ext,ch1_txinhibit_ext,ch1_txmldchaindone_ext,ch1_txmldchainreq_ext,ch1_txoneszeros_ext,ch1_txpausedelayalign_ext,ch1_txpcsresetmask_ext,ch1_txphalignreq_ext,ch1_txphdlypd_ext,ch1_txphdlyreset_ext,ch1_txphsetinitreq_ext,ch1_txphshift180_ext,ch1_txpicodeovrden_ext,ch1_txpicodereset_ext,ch1_txpippmen_ext,ch1_txpisopd_ext,ch1_txpolarity_ext,ch1_txprbsforceerr_ext,ch1_txswing_ext,ch1_txsyncallin_ext,ch1_tx10gstat_ext,ch1_txcomfinish_ext,ch1_txdccdone_ext,ch1_txdlyalignerr_ext,ch1_txdlyalignprog_ext,ch1_txphaligndone_ext,ch1_txphalignerr_ext,ch1_txphalignoutrsvd_ext,ch1_txphdlyresetdone_ext,ch1_txphsetinitdone_ext,ch1_txphshift180done_ext,ch1_txsyncdone_ext,ch1_txctrl0_ext[15:0],ch1_txctrl1_ext[15:0],ch1_txdeemph_ext[1:0],ch1_txpd_ext[1:0],ch1_txresetmode_ext[1:0],ch1_txmstresetdone_ext,ch1_txmargin_ext[2:0],ch1_txprbssel_ext[3:0],ch1_txdiffctrl_ext[4:0],ch1_txpippmstepsize_ext[4:0],ch1_txmaincursor_ext[6:0],ch1_txctrl2_ext[7:0],ch1_txdataextendrsvd_ext[7:0],ch1_txprogdivresetdone_ext,ch1_txpmaresetdone_ext,ch1_txresetdone_ext,ch0_rxdata[127:0],ch0_rxpcsresetmask[4:0],ch0_rxpmaresetmask[6:0],ch0_rxdatavalid[1:0],ch0_rxheader[5:0],ch0_rxgearboxslip,ch0_gtrxreset,ch0_rxprogdivreset,ch0_rxuserrdy,ch0_rxprogdivresetdone,ch0_rxpmaresetdone,ch0_rxresetdone,ch0_rx10gstat[7:0],ch0_rxbufstatus[2:0],ch0_rxbyteisaligned,ch0_rxbyterealign,ch0_rxcdrhold,ch0_rxcdrlock,ch0_rxcdrovrden,ch0_rxcdrphdone,ch0_rxcdrreset,ch0_rxchanbondseq,ch0_rxchanisaligned,ch0_rxchanrealign,ch0_rxchbondi[4:0],ch0_rxchbondo[4:0],ch0_rxclkcorcnt[1:0],ch0_rxcominitdet,ch0_rxcommadet,ch0_rxcomsasdet,ch0_rxcomwakedet,ch0_rxctrl0[15:0],ch0_rxctrl1[15:0],ch0_rxctrl2[7:0],ch0_rxctrl3[7:0],ch0_rxdapicodeovrden,ch0_rxdapicodereset,ch0_rxdataextendrsvd[7:0],ch0_rxdccdone,ch0_rxdlyalignerr,ch0_rxdlyalignprog,ch0_rxdlyalignreq,ch0_rxelecidle,ch0_rxeqtraining,ch0_rxfinealigndone,ch0_rxheadervalid[1:0],ch0_rxlpmen,ch0_rxmldchaindone,ch0_rxmldchainreq,ch0_rxmlfinealignreq,ch0_rxoobreset,ch0_rxosintdone,ch0_rxosintstarted,ch0_rxosintstrobedone,ch0_rxosintstrobestarted,ch0_rxpd[1:0],ch0_rxphaligndone,ch0_rxphalignerr,ch0_rxphalignreq,ch0_rxphalignresetmask[1:0],ch0_rxphdlypd,ch0_rxphdlyreset,ch0_rxphdlyresetdone,ch0_rxphsetinitdone,ch0_rxphsetinitreq,ch0_rxphshift180,ch0_rxphshift180done,ch0_rxpolarity,ch0_rxprbscntreset,ch0_rxprbserr,ch0_rxprbslocked,ch0_rxprbssel[3:0],ch0_rxrate[7:0],ch0_rxresetmode[1:0],ch0_rxmstreset,ch0_rxmstdatapathreset,ch0_rxmstresetdone,ch0_rxslide,ch0_rxsliderdy,ch0_rxstartofseq[1:0],ch0_rxstatus[2:0],ch0_rxsyncallin,ch0_rxsyncdone,ch0_rxtermination,ch0_rxvalid,ch0_cdrbmcdrreq,ch0_cdrfreqos,ch0_cdrincpctrl,ch0_cdrstepdir,ch0_cdrstepsq,ch0_cdrstepsx,ch0_cfokovrdfinish,ch0_cfokovrdpulse,ch0_cfokovrdstart,ch0_eyescanreset,ch0_eyescantrigger,ch0_eyescandataerror,ch0_cfokovrdrdy0,ch0_cfokovrdrdy1,ch0_rxdata_ext[127:0],ch0_rxpcsresetmask_ext[4:0],ch0_rxpmaresetmask_ext[6:0],ch0_rxdatavalid_ext[1:0],ch0_rxheader_ext[5:0],ch0_rxgearboxslip_ext,ch0_rxprogdivresetdone_ext,ch0_rxpmaresetdone_ext,ch0_rxresetdone_ext,ch0_rx10gstat_ext[7:0],ch0_rxbufstatus_ext[2:0],ch0_rxbyteisaligned_ext,ch0_rxbyterealign_ext,ch0_rxcdrhold_ext,ch0_rxcdrlock_ext,ch0_rxcdrovrden_ext,ch0_rxcdrphdone_ext,ch0_rxcdrreset_ext,ch0_rxchanbondseq_ext,ch0_rxchanisaligned_ext,ch0_rxchanrealign_ext,ch0_rxchbondi_ext[4:0],ch0_rxchbondo_ext[4:0],ch0_rxclkcorcnt_ext[1:0],ch0_rxcominitdet_ext,ch0_rxcommadet_ext,ch0_rxcomsasdet_ext,ch0_rxcomwakedet_ext,ch0_rxctrl0_ext[15:0],ch0_rxctrl1_ext[15:0],ch0_rxctrl2_ext[7:0],ch0_rxctrl3_ext[7:0],ch0_rxdapicodeovrden_ext,ch0_rxdapicodereset_ext,ch0_rxdataextendrsvd_ext[7:0],ch0_rxdccdone_ext,ch0_rxdlyalignerr_ext,ch0_rxdlyalignprog_ext,ch0_rxdlyalignreq_ext,ch0_rxelecidle_ext,ch0_rxeqtraining_ext,ch0_rxfinealigndone_ext,ch0_rxheadervalid_ext[1:0],ch0_rxlpmen_ext,ch0_rxmldchaindone_ext,ch0_rxmldchainreq_ext,ch0_rxmlfinealignreq_ext,ch0_rxoobreset_ext,ch0_rxosintdone_ext,ch0_rxosintstarted_ext,ch0_rxosintstrobedone_ext,ch0_rxosintstrobestarted_ext,ch0_rxpd_ext[1:0],ch0_rxphaligndone_ext,ch0_rxphalignerr_ext,ch0_rxphalignreq_ext,ch0_rxphalignresetmask_ext[1:0],ch0_rxphdlypd_ext,ch0_rxphdlyreset_ext,ch0_rxphdlyresetdone_ext,ch0_rxphsetinitdone_ext,ch0_rxphsetinitreq_ext,ch0_rxphshift180_ext,ch0_rxphshift180done_ext,ch0_rxpolarity_ext,ch0_rxprbscntreset_ext,ch0_rxprbserr_ext,ch0_rxprbslocked_ext,ch0_rxprbssel_ext[3:0],ch0_rxresetmode_ext[1:0],ch0_rxmstresetdone_ext,ch0_rxslide_ext,ch0_rxsliderdy_ext,ch0_rxstartofseq_ext[1:0],ch0_rxstatus_ext[2:0],ch0_rxsyncallin_ext,ch0_rxsyncdone_ext,ch0_rxtermination_ext,ch0_rxvalid_ext,ch0_cdrbmcdrreq_ext,ch0_cdrfreqos_ext,ch0_cdrincpctrl_ext,ch0_cdrstepdir_ext,ch0_cdrstepsq_ext,ch0_cdrstepsx_ext,ch0_cfokovrdfinish_ext,ch0_cfokovrdpulse_ext,ch0_cfokovrdstart_ext,ch0_eyescanreset_ext,ch0_eyescantrigger_ext,ch0_eyescandataerror_ext,ch0_cfokovrdrdy0_ext,ch0_cfokovrdrdy1_ext,ch1_rxdata[127:0],ch1_rxpcsresetmask[4:0],ch1_rxpmaresetmask[6:0],ch1_rxdatavalid[1:0],ch1_rxheader[5:0],ch1_rxgearboxslip,ch1_gtrxreset,ch1_rxprogdivreset,ch1_rxuserrdy,ch1_rxprogdivresetdone,ch1_rxpmaresetdone,ch1_rxresetdone,ch1_rx10gstat[7:0],ch1_rxbufstatus[2:0],ch1_rxbyteisaligned,ch1_rxbyterealign,ch1_rxcdrhold,ch1_rxcdrlock,ch1_rxcdrovrden,ch1_rxcdrphdone,ch1_rxcdrreset,ch1_rxchanbondseq,ch1_rxchanisaligned,ch1_rxchanrealign,ch1_rxchbondi[4:0],ch1_rxchbondo[4:0],ch1_rxclkcorcnt[1:0],ch1_rxcominitdet,ch1_rxcommadet,ch1_rxcomsasdet,ch1_rxcomwakedet,ch1_rxctrl0[15:0],ch1_rxctrl1[15:0],ch1_rxctrl2[7:0],ch1_rxctrl3[7:0],ch1_rxdapicodeovrden,ch1_rxdapicodereset,ch1_rxdataextendrsvd[7:0],ch1_rxdccdone,ch1_rxdlyalignerr,ch1_rxdlyalignprog,ch1_rxdlyalignreq,ch1_rxelecidle,ch1_rxeqtraining,ch1_rxfinealigndone,ch1_rxheadervalid[1:0],ch1_rxlpmen,ch1_rxmldchaindone,ch1_rxmldchainreq,ch1_rxmlfinealignreq,ch1_rxoobreset,ch1_rxosintdone,ch1_rxosintstarted,ch1_rxosintstrobedone,ch1_rxosintstrobestarted,ch1_rxpd[1:0],ch1_rxphaligndone,ch1_rxphalignerr,ch1_rxphalignreq,ch1_rxphalignresetmask[1:0],ch1_rxphdlypd,ch1_rxphdlyreset,ch1_rxphdlyresetdone,ch1_rxphsetinitdone,ch1_rxphsetinitreq,ch1_rxphshift180,ch1_rxphshift180done,ch1_rxpolarity,ch1_rxprbscntreset,ch1_rxprbserr,ch1_rxprbslocked,ch1_rxprbssel[3:0],ch1_rxrate[7:0],ch1_rxresetmode[1:0],ch1_rxmstreset,ch1_rxmstdatapathreset,ch1_rxmstresetdone,ch1_rxslide,ch1_rxsliderdy,ch1_rxstartofseq[1:0],ch1_rxstatus[2:0],ch1_rxsyncallin,ch1_rxsyncdone,ch1_rxtermination,ch1_rxvalid,ch1_cdrbmcdrreq,ch1_cdrfreqos,ch1_cdrincpctrl,ch1_cdrstepdir,ch1_cdrstepsq,ch1_cdrstepsx,ch1_cfokovrdfinish,ch1_cfokovrdpulse,ch1_cfokovrdstart,ch1_eyescanreset,ch1_eyescantrigger,ch1_eyescandataerror,ch1_cfokovrdrdy0,ch1_cfokovrdrdy1,ch1_rxdata_ext[127:0],ch1_rxpcsresetmask_ext[4:0],ch1_rxpmaresetmask_ext[6:0],ch1_rxdatavalid_ext[1:0],ch1_rxheader_ext[5:0],ch1_rxgearboxslip_ext,ch1_rxprogdivresetdone_ext,ch1_rxpmaresetdone_ext,ch1_rxresetdone_ext,ch1_rx10gstat_ext[7:0],ch1_rxbufstatus_ext[2:0],ch1_rxbyteisaligned_ext,ch1_rxbyterealign_ext,ch1_rxcdrhold_ext,ch1_rxcdrlock_ext,ch1_rxcdrovrden_ext,ch1_rxcdrphdone_ext,ch1_rxcdrreset_ext,ch1_rxchanbondseq_ext,ch1_rxchanisaligned_ext,ch1_rxchanrealign_ext,ch1_rxchbondi_ext[4:0],ch1_rxchbondo_ext[4:0],ch1_rxclkcorcnt_ext[1:0],ch1_rxcominitdet_ext,ch1_rxcommadet_ext,ch1_rxcomsasdet_ext,ch1_rxcomwakedet_ext,ch1_rxctrl0_ext[15:0],ch1_rxctrl1_ext[15:0],ch1_rxctrl2_ext[7:0],ch1_rxctrl3_ext[7:0],ch1_rxdapicodeovrden_ext,ch1_rxdapicodereset_ext,ch1_rxdataextendrsvd_ext[7:0],ch1_rxdccdone_ext,ch1_rxdlyalignerr_ext,ch1_rxdlyalignprog_ext,ch1_rxdlyalignreq_ext,ch1_rxelecidle_ext,ch1_rxeqtraining_ext,ch1_rxfinealigndone_ext,ch1_rxheadervalid_ext[1:0],ch1_rxlpmen_ext,ch1_rxmldchaindone_ext,ch1_rxmldchainreq_ext,ch1_rxmlfinealignreq_ext,ch1_rxoobreset_ext,ch1_rxosintdone_ext,ch1_rxosintstarted_ext,ch1_rxosintstrobedone_ext,ch1_rxosintstrobestarted_ext,ch1_rxpd_ext[1:0],ch1_rxphaligndone_ext,ch1_rxphalignerr_ext,ch1_rxphalignreq_ext,ch1_rxphalignresetmask_ext[1:0],ch1_rxphdlypd_ext,ch1_rxphdlyreset_ext,ch1_rxphdlyresetdone_ext,ch1_rxphsetinitdone_ext,ch1_rxphsetinitreq_ext,ch1_rxphshift180_ext,ch1_rxphshift180done_ext,ch1_rxpolarity_ext,ch1_rxprbscntreset_ext,ch1_rxprbserr_ext,ch1_rxprbslocked_ext,ch1_rxprbssel_ext[3:0],ch1_rxresetmode_ext[1:0],ch1_rxmstresetdone_ext,ch1_rxslide_ext,ch1_rxsliderdy_ext,ch1_rxstartofseq_ext[1:0],ch1_rxstatus_ext[2:0],ch1_rxsyncallin_ext,ch1_rxsyncdone_ext,ch1_rxtermination_ext,ch1_rxvalid_ext,ch1_cdrbmcdrreq_ext,ch1_cdrfreqos_ext,ch1_cdrincpctrl_ext,ch1_cdrstepdir_ext,ch1_cdrstepsq_ext,ch1_cdrstepsx_ext,ch1_cfokovrdfinish_ext,ch1_cfokovrdpulse_ext,ch1_cfokovrdstart_ext,ch1_eyescanreset_ext,ch1_eyescantrigger_ext,ch1_eyescandataerror_ext,ch1_cfokovrdrdy0_ext,ch1_cfokovrdrdy1_ext,gt_txusrclk,gt_rxusrclk,apb3clk,gtpowergood,gt_lcpll_lock,gt_rpll_lock,ch_phystatus_in[1:0],ilo_resetdone,rx_clr_out,rx_clrb_leaf_out,tx_clr_out,tx_clrb_leaf_out,link_status_out,gpio_enable,tx_resetdone_out,rx_resetdone_out,txusrclk_out,rxusrclk_out,rpll_lock_out,lcpll_lock_out,pcie_rstb,gpi_out,gpo_in,gtreset_in,rate_sel[3:0],reset_mask[1:0],reset_tx_pll_and_datapath_in,reset_tx_datapath_in,reset_rx_pll_and_datapath_in,reset_rx_datapath_in";
attribute X_CORE_INFO : string;
attribute X_CORE_INFO of stub : architecture is "system_gt_bridge_ip_0_0_inst,Vivado 2022.2";
begin
end;
