-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2022.2 (lin64) Build 3671981 Fri Oct 14 04:59:54 MDT 2022
-- Date        : Wed Mar 27 13:01:00 2024
-- Host        : epics-X9DAi running 64-bit Ubuntu 22.04.2 LTS
-- Command     : write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix
--               decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ system_gt_quad_base_0_0_stub.vhdl
-- Design      : system_gt_quad_base_0_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xcvc1902-vsva2197-2MP-e-S
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  Port ( 
    rxmarginclk : in STD_LOGIC;
    hsclk0_lcpllreset : in STD_LOGIC;
    hsclk0_rpllreset : in STD_LOGIC;
    hsclk1_lcpllreset : in STD_LOGIC;
    hsclk1_rpllreset : in STD_LOGIC;
    hsclk0_lcplllock : out STD_LOGIC;
    hsclk1_lcplllock : out STD_LOGIC;
    hsclk0_rplllock : out STD_LOGIC;
    hsclk1_rplllock : out STD_LOGIC;
    gtpowergood : out STD_LOGIC;
    ch0_pcierstb : in STD_LOGIC;
    ch1_pcierstb : in STD_LOGIC;
    ch2_pcierstb : in STD_LOGIC;
    ch3_pcierstb : in STD_LOGIC;
    pcielinkreachtarget : in STD_LOGIC;
    pcieltssm : in STD_LOGIC_VECTOR ( 5 downto 0 );
    rxmarginreqack : out STD_LOGIC;
    rxmarginrescmd : out STD_LOGIC_VECTOR ( 3 downto 0 );
    rxmarginreslanenum : out STD_LOGIC_VECTOR ( 1 downto 0 );
    rxmarginrespayld : out STD_LOGIC_VECTOR ( 7 downto 0 );
    rxmarginresreq : out STD_LOGIC;
    rxmarginreqcmd : in STD_LOGIC_VECTOR ( 3 downto 0 );
    rxmarginreqlanenum : in STD_LOGIC_VECTOR ( 1 downto 0 );
    rxmarginreqpayld : in STD_LOGIC_VECTOR ( 7 downto 0 );
    rxmarginreqreq : in STD_LOGIC;
    rxmarginresack : in STD_LOGIC;
    ch0_iloreset : in STD_LOGIC;
    ch1_iloreset : in STD_LOGIC;
    ch2_iloreset : in STD_LOGIC;
    ch3_iloreset : in STD_LOGIC;
    ch0_iloresetdone : out STD_LOGIC;
    ch1_iloresetdone : out STD_LOGIC;
    ch2_iloresetdone : out STD_LOGIC;
    ch3_iloresetdone : out STD_LOGIC;
    ch0_phystatus : out STD_LOGIC;
    ch1_phystatus : out STD_LOGIC;
    ch2_phystatus : out STD_LOGIC;
    ch3_phystatus : out STD_LOGIC;
    hsclk0_lcpllfbclklost : out STD_LOGIC;
    hsclk0_lcpllrefclklost : out STD_LOGIC;
    hsclk0_lcpllrefclkmonitor : out STD_LOGIC;
    hsclk0_rpllfbclklost : out STD_LOGIC;
    hsclk0_rpllrefclklost : out STD_LOGIC;
    hsclk0_rpllrefclkmonitor : out STD_LOGIC;
    hsclk1_lcpllfbclklost : out STD_LOGIC;
    hsclk1_lcpllrefclklost : out STD_LOGIC;
    hsclk1_lcpllrefclkmonitor : out STD_LOGIC;
    hsclk1_rpllfbclklost : out STD_LOGIC;
    hsclk1_rpllrefclklost : out STD_LOGIC;
    hsclk1_rpllrefclkmonitor : out STD_LOGIC;
    hsclk0_lcpllpd : in STD_LOGIC;
    hsclk0_rpllpd : in STD_LOGIC;
    hsclk0_lcpllresetbypassmode : in STD_LOGIC;
    hsclk0_lcpllsdmtoggle : in STD_LOGIC;
    hsclk0_rpllresetbypassmode : in STD_LOGIC;
    hsclk0_rpllsdmtoggle : in STD_LOGIC;
    hsclk1_lcpllpd : in STD_LOGIC;
    hsclk1_lcpllresetbypassmode : in STD_LOGIC;
    hsclk1_lcpllsdmtoggle : in STD_LOGIC;
    hsclk1_rpllpd : in STD_LOGIC;
    hsclk1_rpllresetbypassmode : in STD_LOGIC;
    hsclk1_rpllsdmtoggle : in STD_LOGIC;
    refclk0_gtrefclkpd : in STD_LOGIC;
    refclk1_gtrefclkpd : in STD_LOGIC;
    hsclk0_lcpllrefclksel : in STD_LOGIC_VECTOR ( 2 downto 0 );
    hsclk1_lcpllrefclksel : in STD_LOGIC_VECTOR ( 2 downto 0 );
    hsclk0_rpllrefclksel : in STD_LOGIC_VECTOR ( 2 downto 0 );
    hsclk1_rpllrefclksel : in STD_LOGIC_VECTOR ( 2 downto 0 );
    hsclk0_lcpllfbdiv : in STD_LOGIC_VECTOR ( 7 downto 0 );
    hsclk0_rpllfbdiv : in STD_LOGIC_VECTOR ( 7 downto 0 );
    hsclk1_lcpllfbdiv : in STD_LOGIC_VECTOR ( 7 downto 0 );
    hsclk1_rpllfbdiv : in STD_LOGIC_VECTOR ( 7 downto 0 );
    hsclk0_rxrecclkout0 : out STD_LOGIC;
    hsclk0_rxrecclkout1 : out STD_LOGIC;
    hsclk1_rxrecclkout0 : out STD_LOGIC;
    hsclk1_rxrecclkout1 : out STD_LOGIC;
    hsclk0_lcpllsdmdata : in STD_LOGIC_VECTOR ( 25 downto 0 );
    hsclk1_lcpllsdmdata : in STD_LOGIC_VECTOR ( 25 downto 0 );
    hsclk0_rpllsdmdata : in STD_LOGIC_VECTOR ( 25 downto 0 );
    hsclk1_rpllsdmdata : in STD_LOGIC_VECTOR ( 25 downto 0 );
    hsclk0_lcpllresetmask : in STD_LOGIC_VECTOR ( 1 downto 0 );
    hsclk1_lcpllresetmask : in STD_LOGIC_VECTOR ( 1 downto 0 );
    hsclk0_rpllresetmask : in STD_LOGIC_VECTOR ( 1 downto 0 );
    hsclk1_rpllresetmask : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_txdata : in STD_LOGIC_VECTOR ( 127 downto 0 );
    ch0_txheader : in STD_LOGIC_VECTOR ( 5 downto 0 );
    ch0_txsequence : in STD_LOGIC_VECTOR ( 6 downto 0 );
    ch0_gttxreset : in STD_LOGIC;
    ch0_txprogdivreset : in STD_LOGIC;
    ch0_txuserrdy : in STD_LOGIC;
    ch0_txphalignresetmask : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_txcominit : in STD_LOGIC;
    ch0_txcomsas : in STD_LOGIC;
    ch0_txcomwake : in STD_LOGIC;
    ch0_txdapicodeovrden : in STD_LOGIC;
    ch0_txdapicodereset : in STD_LOGIC;
    ch0_txdetectrx : in STD_LOGIC;
    ch0_txlatclk : in STD_LOGIC;
    ch0_txphdlytstclk : in STD_LOGIC;
    ch0_txdlyalignreq : in STD_LOGIC;
    ch0_txelecidle : in STD_LOGIC;
    ch0_txinhibit : in STD_LOGIC;
    ch0_txmldchaindone : in STD_LOGIC;
    ch0_txmldchainreq : in STD_LOGIC;
    ch0_txoneszeros : in STD_LOGIC;
    ch0_txpausedelayalign : in STD_LOGIC;
    ch0_txpcsresetmask : in STD_LOGIC;
    ch0_txphalignreq : in STD_LOGIC;
    ch0_txphdlypd : in STD_LOGIC;
    ch0_txphdlyreset : in STD_LOGIC;
    ch0_txphsetinitreq : in STD_LOGIC;
    ch0_txphshift180 : in STD_LOGIC;
    ch0_txpicodeovrden : in STD_LOGIC;
    ch0_txpicodereset : in STD_LOGIC;
    ch0_txpippmen : in STD_LOGIC;
    ch0_txpisopd : in STD_LOGIC;
    ch0_txpolarity : in STD_LOGIC;
    ch0_txprbsforceerr : in STD_LOGIC;
    ch0_txswing : in STD_LOGIC;
    ch0_txsyncallin : in STD_LOGIC;
    ch0_tx10gstat : out STD_LOGIC;
    ch0_txcomfinish : out STD_LOGIC;
    ch0_txdccdone : out STD_LOGIC;
    ch0_txdlyalignerr : out STD_LOGIC;
    ch0_txdlyalignprog : out STD_LOGIC;
    ch0_txphaligndone : out STD_LOGIC;
    ch0_txphalignerr : out STD_LOGIC;
    ch0_txphalignoutrsvd : out STD_LOGIC;
    ch0_txphdlyresetdone : out STD_LOGIC;
    ch0_txphsetinitdone : out STD_LOGIC;
    ch0_txphshift180done : out STD_LOGIC;
    ch0_txsyncdone : out STD_LOGIC;
    ch0_txbufstatus : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_txctrl0 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ch0_txctrl1 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ch0_txdeemph : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_txpd : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_txresetmode : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_txmstreset : in STD_LOGIC;
    ch0_txmstdatapathreset : in STD_LOGIC;
    ch0_txmstresetdone : out STD_LOGIC;
    ch0_txmargin : in STD_LOGIC_VECTOR ( 2 downto 0 );
    ch0_txpmaresetmask : in STD_LOGIC_VECTOR ( 2 downto 0 );
    ch0_txprbssel : in STD_LOGIC_VECTOR ( 3 downto 0 );
    ch0_txdiffctrl : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch0_txpippmstepsize : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch0_txpostcursor : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch0_txprecursor : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch0_txmaincursor : in STD_LOGIC_VECTOR ( 6 downto 0 );
    ch0_txctrl2 : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch0_txrate : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch0_txprogdivresetdone : out STD_LOGIC;
    ch0_txpmaresetdone : out STD_LOGIC;
    ch0_txresetdone : out STD_LOGIC;
    ch0_txdataextendrsvd : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch0_txoutclk : out STD_LOGIC;
    ch0_txusrclk : in STD_LOGIC;
    ch1_txdata : in STD_LOGIC_VECTOR ( 127 downto 0 );
    ch1_txheader : in STD_LOGIC_VECTOR ( 5 downto 0 );
    ch1_txsequence : in STD_LOGIC_VECTOR ( 6 downto 0 );
    ch1_gttxreset : in STD_LOGIC;
    ch1_txprogdivreset : in STD_LOGIC;
    ch1_txuserrdy : in STD_LOGIC;
    ch1_txphalignresetmask : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_txcominit : in STD_LOGIC;
    ch1_txcomsas : in STD_LOGIC;
    ch1_txcomwake : in STD_LOGIC;
    ch1_txdapicodeovrden : in STD_LOGIC;
    ch1_txdapicodereset : in STD_LOGIC;
    ch1_txdetectrx : in STD_LOGIC;
    ch1_txlatclk : in STD_LOGIC;
    ch1_txphdlytstclk : in STD_LOGIC;
    ch1_txdlyalignreq : in STD_LOGIC;
    ch1_txelecidle : in STD_LOGIC;
    ch1_txinhibit : in STD_LOGIC;
    ch1_txmldchaindone : in STD_LOGIC;
    ch1_txmldchainreq : in STD_LOGIC;
    ch1_txoneszeros : in STD_LOGIC;
    ch1_txpausedelayalign : in STD_LOGIC;
    ch1_txpcsresetmask : in STD_LOGIC;
    ch1_txphalignreq : in STD_LOGIC;
    ch1_txphdlypd : in STD_LOGIC;
    ch1_txphdlyreset : in STD_LOGIC;
    ch1_txphsetinitreq : in STD_LOGIC;
    ch1_txphshift180 : in STD_LOGIC;
    ch1_txpicodeovrden : in STD_LOGIC;
    ch1_txpicodereset : in STD_LOGIC;
    ch1_txpippmen : in STD_LOGIC;
    ch1_txpisopd : in STD_LOGIC;
    ch1_txpolarity : in STD_LOGIC;
    ch1_txprbsforceerr : in STD_LOGIC;
    ch1_txswing : in STD_LOGIC;
    ch1_txsyncallin : in STD_LOGIC;
    ch1_tx10gstat : out STD_LOGIC;
    ch1_txcomfinish : out STD_LOGIC;
    ch1_txdccdone : out STD_LOGIC;
    ch1_txdlyalignerr : out STD_LOGIC;
    ch1_txdlyalignprog : out STD_LOGIC;
    ch1_txphaligndone : out STD_LOGIC;
    ch1_txphalignerr : out STD_LOGIC;
    ch1_txphalignoutrsvd : out STD_LOGIC;
    ch1_txphdlyresetdone : out STD_LOGIC;
    ch1_txphsetinitdone : out STD_LOGIC;
    ch1_txphshift180done : out STD_LOGIC;
    ch1_txsyncdone : out STD_LOGIC;
    ch1_txbufstatus : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_txctrl0 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ch1_txctrl1 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ch1_txdeemph : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_txpd : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_txresetmode : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_txmstreset : in STD_LOGIC;
    ch1_txmstdatapathreset : in STD_LOGIC;
    ch1_txmstresetdone : out STD_LOGIC;
    ch1_txmargin : in STD_LOGIC_VECTOR ( 2 downto 0 );
    ch1_txpmaresetmask : in STD_LOGIC_VECTOR ( 2 downto 0 );
    ch1_txprbssel : in STD_LOGIC_VECTOR ( 3 downto 0 );
    ch1_txdiffctrl : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch1_txpippmstepsize : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch1_txpostcursor : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch1_txprecursor : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch1_txmaincursor : in STD_LOGIC_VECTOR ( 6 downto 0 );
    ch1_txctrl2 : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch1_txrate : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch1_txprogdivresetdone : out STD_LOGIC;
    ch1_txpmaresetdone : out STD_LOGIC;
    ch1_txresetdone : out STD_LOGIC;
    ch1_txdataextendrsvd : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch1_txoutclk : out STD_LOGIC;
    ch1_txusrclk : in STD_LOGIC;
    ch2_txdata : in STD_LOGIC_VECTOR ( 127 downto 0 );
    ch2_txheader : in STD_LOGIC_VECTOR ( 5 downto 0 );
    ch2_txsequence : in STD_LOGIC_VECTOR ( 6 downto 0 );
    ch2_gttxreset : in STD_LOGIC;
    ch2_txprogdivreset : in STD_LOGIC;
    ch2_txuserrdy : in STD_LOGIC;
    ch2_txphalignresetmask : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch2_txcominit : in STD_LOGIC;
    ch2_txcomsas : in STD_LOGIC;
    ch2_txcomwake : in STD_LOGIC;
    ch2_txdapicodeovrden : in STD_LOGIC;
    ch2_txdapicodereset : in STD_LOGIC;
    ch2_txdetectrx : in STD_LOGIC;
    ch2_txlatclk : in STD_LOGIC;
    ch2_txphdlytstclk : in STD_LOGIC;
    ch2_txdlyalignreq : in STD_LOGIC;
    ch2_txelecidle : in STD_LOGIC;
    ch2_txinhibit : in STD_LOGIC;
    ch2_txmldchaindone : in STD_LOGIC;
    ch2_txmldchainreq : in STD_LOGIC;
    ch2_txoneszeros : in STD_LOGIC;
    ch2_txpausedelayalign : in STD_LOGIC;
    ch2_txpcsresetmask : in STD_LOGIC;
    ch2_txphalignreq : in STD_LOGIC;
    ch2_txphdlypd : in STD_LOGIC;
    ch2_txphdlyreset : in STD_LOGIC;
    ch2_txphsetinitreq : in STD_LOGIC;
    ch2_txphshift180 : in STD_LOGIC;
    ch2_txpicodeovrden : in STD_LOGIC;
    ch2_txpicodereset : in STD_LOGIC;
    ch2_txpippmen : in STD_LOGIC;
    ch2_txpisopd : in STD_LOGIC;
    ch2_txpolarity : in STD_LOGIC;
    ch2_txprbsforceerr : in STD_LOGIC;
    ch2_txswing : in STD_LOGIC;
    ch2_txsyncallin : in STD_LOGIC;
    ch2_tx10gstat : out STD_LOGIC;
    ch2_txcomfinish : out STD_LOGIC;
    ch2_txdccdone : out STD_LOGIC;
    ch2_txdlyalignerr : out STD_LOGIC;
    ch2_txdlyalignprog : out STD_LOGIC;
    ch2_txphaligndone : out STD_LOGIC;
    ch2_txphalignerr : out STD_LOGIC;
    ch2_txphalignoutrsvd : out STD_LOGIC;
    ch2_txphdlyresetdone : out STD_LOGIC;
    ch2_txphsetinitdone : out STD_LOGIC;
    ch2_txphshift180done : out STD_LOGIC;
    ch2_txsyncdone : out STD_LOGIC;
    ch2_txbufstatus : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch2_txctrl0 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ch2_txctrl1 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ch2_txdeemph : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch2_txpd : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch2_txresetmode : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch2_txmstreset : in STD_LOGIC;
    ch2_txmstdatapathreset : in STD_LOGIC;
    ch2_txmstresetdone : out STD_LOGIC;
    ch2_txmargin : in STD_LOGIC_VECTOR ( 2 downto 0 );
    ch2_txpmaresetmask : in STD_LOGIC_VECTOR ( 2 downto 0 );
    ch2_txprbssel : in STD_LOGIC_VECTOR ( 3 downto 0 );
    ch2_txdiffctrl : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch2_txpippmstepsize : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch2_txpostcursor : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch2_txprecursor : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch2_txmaincursor : in STD_LOGIC_VECTOR ( 6 downto 0 );
    ch2_txctrl2 : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch2_txrate : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch2_txprogdivresetdone : out STD_LOGIC;
    ch2_txpmaresetdone : out STD_LOGIC;
    ch2_txresetdone : out STD_LOGIC;
    ch2_txdataextendrsvd : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch2_txoutclk : out STD_LOGIC;
    ch2_txusrclk : in STD_LOGIC;
    ch3_txdata : in STD_LOGIC_VECTOR ( 127 downto 0 );
    ch3_txheader : in STD_LOGIC_VECTOR ( 5 downto 0 );
    ch3_txsequence : in STD_LOGIC_VECTOR ( 6 downto 0 );
    ch3_gttxreset : in STD_LOGIC;
    ch3_txprogdivreset : in STD_LOGIC;
    ch3_txuserrdy : in STD_LOGIC;
    ch3_txphalignresetmask : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch3_txcominit : in STD_LOGIC;
    ch3_txcomsas : in STD_LOGIC;
    ch3_txcomwake : in STD_LOGIC;
    ch3_txdapicodeovrden : in STD_LOGIC;
    ch3_txdapicodereset : in STD_LOGIC;
    ch3_txdetectrx : in STD_LOGIC;
    ch3_txlatclk : in STD_LOGIC;
    ch3_txphdlytstclk : in STD_LOGIC;
    ch3_txdlyalignreq : in STD_LOGIC;
    ch3_txelecidle : in STD_LOGIC;
    ch3_txinhibit : in STD_LOGIC;
    ch3_txmldchaindone : in STD_LOGIC;
    ch3_txmldchainreq : in STD_LOGIC;
    ch3_txoneszeros : in STD_LOGIC;
    ch3_txpausedelayalign : in STD_LOGIC;
    ch3_txpcsresetmask : in STD_LOGIC;
    ch3_txphalignreq : in STD_LOGIC;
    ch3_txphdlypd : in STD_LOGIC;
    ch3_txphdlyreset : in STD_LOGIC;
    ch3_txphsetinitreq : in STD_LOGIC;
    ch3_txphshift180 : in STD_LOGIC;
    ch3_txpicodeovrden : in STD_LOGIC;
    ch3_txpicodereset : in STD_LOGIC;
    ch3_txpippmen : in STD_LOGIC;
    ch3_txpisopd : in STD_LOGIC;
    ch3_txpolarity : in STD_LOGIC;
    ch3_txprbsforceerr : in STD_LOGIC;
    ch3_txswing : in STD_LOGIC;
    ch3_txsyncallin : in STD_LOGIC;
    ch3_tx10gstat : out STD_LOGIC;
    ch3_txcomfinish : out STD_LOGIC;
    ch3_txdccdone : out STD_LOGIC;
    ch3_txdlyalignerr : out STD_LOGIC;
    ch3_txdlyalignprog : out STD_LOGIC;
    ch3_txphaligndone : out STD_LOGIC;
    ch3_txphalignerr : out STD_LOGIC;
    ch3_txphalignoutrsvd : out STD_LOGIC;
    ch3_txphdlyresetdone : out STD_LOGIC;
    ch3_txphsetinitdone : out STD_LOGIC;
    ch3_txphshift180done : out STD_LOGIC;
    ch3_txsyncdone : out STD_LOGIC;
    ch3_txbufstatus : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch3_txctrl0 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ch3_txctrl1 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ch3_txdeemph : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch3_txpd : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch3_txresetmode : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch3_txmstreset : in STD_LOGIC;
    ch3_txmstdatapathreset : in STD_LOGIC;
    ch3_txmstresetdone : out STD_LOGIC;
    ch3_txmargin : in STD_LOGIC_VECTOR ( 2 downto 0 );
    ch3_txpmaresetmask : in STD_LOGIC_VECTOR ( 2 downto 0 );
    ch3_txprbssel : in STD_LOGIC_VECTOR ( 3 downto 0 );
    ch3_txdiffctrl : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch3_txpippmstepsize : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch3_txpostcursor : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch3_txprecursor : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch3_txmaincursor : in STD_LOGIC_VECTOR ( 6 downto 0 );
    ch3_txctrl2 : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch3_txrate : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch3_txprogdivresetdone : out STD_LOGIC;
    ch3_txpmaresetdone : out STD_LOGIC;
    ch3_txresetdone : out STD_LOGIC;
    ch3_txdataextendrsvd : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch3_txoutclk : out STD_LOGIC;
    ch3_txusrclk : in STD_LOGIC;
    ch0_rxdata : out STD_LOGIC_VECTOR ( 127 downto 0 );
    ch0_rxdatavalid : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_rxheader : out STD_LOGIC_VECTOR ( 5 downto 0 );
    ch0_rxgearboxslip : in STD_LOGIC;
    ch0_rxlatclk : in STD_LOGIC;
    ch0_gtrxreset : in STD_LOGIC;
    ch0_rxprogdivreset : in STD_LOGIC;
    ch0_rxuserrdy : in STD_LOGIC;
    ch0_rxprogdivresetdone : out STD_LOGIC;
    ch0_rxpmaresetdone : out STD_LOGIC;
    ch0_rxresetdone : out STD_LOGIC;
    ch0_rx10gstat : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch0_rxbufstatus : out STD_LOGIC_VECTOR ( 2 downto 0 );
    ch0_rxbyteisaligned : out STD_LOGIC;
    ch0_rxbyterealign : out STD_LOGIC;
    ch0_rxcdrhold : in STD_LOGIC;
    ch0_rxcdrlock : out STD_LOGIC;
    ch0_rxcdrovrden : in STD_LOGIC;
    ch0_rxcdrphdone : out STD_LOGIC;
    ch0_rxcdrreset : in STD_LOGIC;
    ch0_rxchanbondseq : out STD_LOGIC;
    ch0_rxchanisaligned : out STD_LOGIC;
    ch0_rxchanrealign : out STD_LOGIC;
    ch0_rxchbondi : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch0_rxchbondo : out STD_LOGIC_VECTOR ( 4 downto 0 );
    ch0_rxclkcorcnt : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_rxcominitdet : out STD_LOGIC;
    ch0_rxcommadet : out STD_LOGIC;
    ch0_rxcomsasdet : out STD_LOGIC;
    ch0_rxcomwakedet : out STD_LOGIC;
    ch0_rxctrl0 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    ch0_rxctrl1 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    ch0_rxctrl2 : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch0_rxctrl3 : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch0_rxdapicodeovrden : in STD_LOGIC;
    ch0_rxdapicodereset : in STD_LOGIC;
    ch0_rxdlyalignerr : out STD_LOGIC;
    ch0_rxdlyalignprog : out STD_LOGIC;
    ch0_rxdlyalignreq : in STD_LOGIC;
    ch0_rxelecidle : out STD_LOGIC;
    ch0_rxeqtraining : in STD_LOGIC;
    ch0_rxfinealigndone : out STD_LOGIC;
    ch0_rxheadervalid : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_rxlpmen : in STD_LOGIC;
    ch0_rxmldchaindone : in STD_LOGIC;
    ch0_rxmldchainreq : in STD_LOGIC;
    ch0_rxmlfinealignreq : in STD_LOGIC;
    ch0_rxoobreset : in STD_LOGIC;
    ch0_rxosintdone : out STD_LOGIC;
    ch0_rxpcsresetmask : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch0_rxpd : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_rxphaligndone : out STD_LOGIC;
    ch0_rxphalignerr : out STD_LOGIC;
    ch0_rxphalignreq : in STD_LOGIC;
    ch0_rxphalignresetmask : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_rxphdlypd : in STD_LOGIC;
    ch0_rxphdlyreset : in STD_LOGIC;
    ch0_rxphdlyresetdone : out STD_LOGIC;
    ch0_rxphsetinitdone : out STD_LOGIC;
    ch0_rxphsetinitreq : in STD_LOGIC;
    ch0_rxphshift180 : in STD_LOGIC;
    ch0_rxphshift180done : out STD_LOGIC;
    ch0_rxpmaresetmask : in STD_LOGIC_VECTOR ( 6 downto 0 );
    ch0_rxpolarity : in STD_LOGIC;
    ch0_rxprbscntreset : in STD_LOGIC;
    ch0_rxprbserr : out STD_LOGIC;
    ch0_rxprbslocked : out STD_LOGIC;
    ch0_rxprbssel : in STD_LOGIC_VECTOR ( 3 downto 0 );
    ch0_rxrate : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch0_rxresetmode : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_rxmstreset : in STD_LOGIC;
    ch0_rxmstdatapathreset : in STD_LOGIC;
    ch0_rxmstresetdone : out STD_LOGIC;
    ch0_rxslide : in STD_LOGIC;
    ch0_rxsliderdy : out STD_LOGIC;
    ch0_rxstartofseq : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_rxstatus : out STD_LOGIC_VECTOR ( 2 downto 0 );
    ch0_rxsyncallin : in STD_LOGIC;
    ch0_rxsyncdone : out STD_LOGIC;
    ch0_rxtermination : in STD_LOGIC;
    ch0_rxvalid : out STD_LOGIC;
    ch0_cdrbmcdrreq : in STD_LOGIC;
    ch0_cdrfreqos : in STD_LOGIC;
    ch0_cdrincpctrl : in STD_LOGIC;
    ch0_cdrstepdir : in STD_LOGIC;
    ch0_cdrstepsq : in STD_LOGIC;
    ch0_cdrstepsx : in STD_LOGIC;
    ch0_eyescanreset : in STD_LOGIC;
    ch0_eyescantrigger : in STD_LOGIC;
    ch0_eyescandataerror : out STD_LOGIC;
    ch0_cfokovrdrdy0 : out STD_LOGIC;
    ch0_cfokovrdrdy1 : out STD_LOGIC;
    ch0_rxdataextendrsvd : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch0_rxdccdone : out STD_LOGIC;
    ch0_rxosintstarted : out STD_LOGIC;
    ch0_rxosintstrobedone : out STD_LOGIC;
    ch0_rxosintstrobestarted : out STD_LOGIC;
    ch0_cfokovrdfinish : in STD_LOGIC;
    ch0_cfokovrdpulse : in STD_LOGIC;
    ch0_cfokovrdstart : in STD_LOGIC;
    ch0_rxoutclk : out STD_LOGIC;
    ch0_rxusrclk : in STD_LOGIC;
    ch1_rxdata : out STD_LOGIC_VECTOR ( 127 downto 0 );
    ch1_rxdatavalid : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_rxheader : out STD_LOGIC_VECTOR ( 5 downto 0 );
    ch1_rxgearboxslip : in STD_LOGIC;
    ch1_rxlatclk : in STD_LOGIC;
    ch1_gtrxreset : in STD_LOGIC;
    ch1_rxprogdivreset : in STD_LOGIC;
    ch1_rxuserrdy : in STD_LOGIC;
    ch1_rxprogdivresetdone : out STD_LOGIC;
    ch1_rxpmaresetdone : out STD_LOGIC;
    ch1_rxresetdone : out STD_LOGIC;
    ch1_rx10gstat : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch1_rxbufstatus : out STD_LOGIC_VECTOR ( 2 downto 0 );
    ch1_rxbyteisaligned : out STD_LOGIC;
    ch1_rxbyterealign : out STD_LOGIC;
    ch1_rxcdrhold : in STD_LOGIC;
    ch1_rxcdrlock : out STD_LOGIC;
    ch1_rxcdrovrden : in STD_LOGIC;
    ch1_rxcdrphdone : out STD_LOGIC;
    ch1_rxcdrreset : in STD_LOGIC;
    ch1_rxchanbondseq : out STD_LOGIC;
    ch1_rxchanisaligned : out STD_LOGIC;
    ch1_rxchanrealign : out STD_LOGIC;
    ch1_rxchbondi : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch1_rxchbondo : out STD_LOGIC_VECTOR ( 4 downto 0 );
    ch1_rxclkcorcnt : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_rxcominitdet : out STD_LOGIC;
    ch1_rxcommadet : out STD_LOGIC;
    ch1_rxcomsasdet : out STD_LOGIC;
    ch1_rxcomwakedet : out STD_LOGIC;
    ch1_rxctrl0 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    ch1_rxctrl1 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    ch1_rxctrl2 : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch1_rxctrl3 : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch1_rxdapicodeovrden : in STD_LOGIC;
    ch1_rxdapicodereset : in STD_LOGIC;
    ch1_rxdlyalignerr : out STD_LOGIC;
    ch1_rxdlyalignprog : out STD_LOGIC;
    ch1_rxdlyalignreq : in STD_LOGIC;
    ch1_rxelecidle : out STD_LOGIC;
    ch1_rxeqtraining : in STD_LOGIC;
    ch1_rxfinealigndone : out STD_LOGIC;
    ch1_rxheadervalid : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_rxlpmen : in STD_LOGIC;
    ch1_rxmldchaindone : in STD_LOGIC;
    ch1_rxmldchainreq : in STD_LOGIC;
    ch1_rxmlfinealignreq : in STD_LOGIC;
    ch1_rxoobreset : in STD_LOGIC;
    ch1_rxosintdone : out STD_LOGIC;
    ch1_rxpcsresetmask : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch1_rxpd : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_rxphaligndone : out STD_LOGIC;
    ch1_rxphalignerr : out STD_LOGIC;
    ch1_rxphalignreq : in STD_LOGIC;
    ch1_rxphalignresetmask : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_rxphdlypd : in STD_LOGIC;
    ch1_rxphdlyreset : in STD_LOGIC;
    ch1_rxphdlyresetdone : out STD_LOGIC;
    ch1_rxphsetinitdone : out STD_LOGIC;
    ch1_rxphsetinitreq : in STD_LOGIC;
    ch1_rxphshift180 : in STD_LOGIC;
    ch1_rxphshift180done : out STD_LOGIC;
    ch1_rxpmaresetmask : in STD_LOGIC_VECTOR ( 6 downto 0 );
    ch1_rxpolarity : in STD_LOGIC;
    ch1_rxprbscntreset : in STD_LOGIC;
    ch1_rxprbserr : out STD_LOGIC;
    ch1_rxprbslocked : out STD_LOGIC;
    ch1_rxprbssel : in STD_LOGIC_VECTOR ( 3 downto 0 );
    ch1_rxrate : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch1_rxresetmode : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_rxmstreset : in STD_LOGIC;
    ch1_rxmstdatapathreset : in STD_LOGIC;
    ch1_rxmstresetdone : out STD_LOGIC;
    ch1_rxslide : in STD_LOGIC;
    ch1_rxsliderdy : out STD_LOGIC;
    ch1_rxstartofseq : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_rxstatus : out STD_LOGIC_VECTOR ( 2 downto 0 );
    ch1_rxsyncallin : in STD_LOGIC;
    ch1_rxsyncdone : out STD_LOGIC;
    ch1_rxtermination : in STD_LOGIC;
    ch1_rxvalid : out STD_LOGIC;
    ch1_cdrbmcdrreq : in STD_LOGIC;
    ch1_cdrfreqos : in STD_LOGIC;
    ch1_cdrincpctrl : in STD_LOGIC;
    ch1_cdrstepdir : in STD_LOGIC;
    ch1_cdrstepsq : in STD_LOGIC;
    ch1_cdrstepsx : in STD_LOGIC;
    ch1_eyescanreset : in STD_LOGIC;
    ch1_eyescantrigger : in STD_LOGIC;
    ch1_eyescandataerror : out STD_LOGIC;
    ch1_cfokovrdrdy0 : out STD_LOGIC;
    ch1_cfokovrdrdy1 : out STD_LOGIC;
    ch1_rxdataextendrsvd : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch1_rxdccdone : out STD_LOGIC;
    ch1_rxosintstarted : out STD_LOGIC;
    ch1_rxosintstrobedone : out STD_LOGIC;
    ch1_rxosintstrobestarted : out STD_LOGIC;
    ch1_cfokovrdfinish : in STD_LOGIC;
    ch1_cfokovrdpulse : in STD_LOGIC;
    ch1_cfokovrdstart : in STD_LOGIC;
    ch1_rxoutclk : out STD_LOGIC;
    ch1_rxusrclk : in STD_LOGIC;
    ch2_rxdata : out STD_LOGIC_VECTOR ( 127 downto 0 );
    ch2_rxdatavalid : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch2_rxheader : out STD_LOGIC_VECTOR ( 5 downto 0 );
    ch2_rxgearboxslip : in STD_LOGIC;
    ch2_rxlatclk : in STD_LOGIC;
    ch2_gtrxreset : in STD_LOGIC;
    ch2_rxprogdivreset : in STD_LOGIC;
    ch2_rxuserrdy : in STD_LOGIC;
    ch2_rxprogdivresetdone : out STD_LOGIC;
    ch2_rxpmaresetdone : out STD_LOGIC;
    ch2_rxresetdone : out STD_LOGIC;
    ch2_rx10gstat : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch2_rxbufstatus : out STD_LOGIC_VECTOR ( 2 downto 0 );
    ch2_rxbyteisaligned : out STD_LOGIC;
    ch2_rxbyterealign : out STD_LOGIC;
    ch2_rxcdrhold : in STD_LOGIC;
    ch2_rxcdrlock : out STD_LOGIC;
    ch2_rxcdrovrden : in STD_LOGIC;
    ch2_rxcdrphdone : out STD_LOGIC;
    ch2_rxcdrreset : in STD_LOGIC;
    ch2_rxchanbondseq : out STD_LOGIC;
    ch2_rxchanisaligned : out STD_LOGIC;
    ch2_rxchanrealign : out STD_LOGIC;
    ch2_rxchbondi : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch2_rxchbondo : out STD_LOGIC_VECTOR ( 4 downto 0 );
    ch2_rxclkcorcnt : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch2_rxcominitdet : out STD_LOGIC;
    ch2_rxcommadet : out STD_LOGIC;
    ch2_rxcomsasdet : out STD_LOGIC;
    ch2_rxcomwakedet : out STD_LOGIC;
    ch2_rxctrl0 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    ch2_rxctrl1 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    ch2_rxctrl2 : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch2_rxctrl3 : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch2_rxdapicodeovrden : in STD_LOGIC;
    ch2_rxdapicodereset : in STD_LOGIC;
    ch2_rxdlyalignerr : out STD_LOGIC;
    ch2_rxdlyalignprog : out STD_LOGIC;
    ch2_rxdlyalignreq : in STD_LOGIC;
    ch2_rxelecidle : out STD_LOGIC;
    ch2_rxeqtraining : in STD_LOGIC;
    ch2_rxfinealigndone : out STD_LOGIC;
    ch2_rxheadervalid : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch2_rxlpmen : in STD_LOGIC;
    ch2_rxmldchaindone : in STD_LOGIC;
    ch2_rxmldchainreq : in STD_LOGIC;
    ch2_rxmlfinealignreq : in STD_LOGIC;
    ch2_rxoobreset : in STD_LOGIC;
    ch2_rxosintdone : out STD_LOGIC;
    ch2_rxpcsresetmask : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch2_rxpd : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch2_rxphaligndone : out STD_LOGIC;
    ch2_rxphalignerr : out STD_LOGIC;
    ch2_rxphalignreq : in STD_LOGIC;
    ch2_rxphalignresetmask : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch2_rxphdlypd : in STD_LOGIC;
    ch2_rxphdlyreset : in STD_LOGIC;
    ch2_rxphdlyresetdone : out STD_LOGIC;
    ch2_rxphsetinitdone : out STD_LOGIC;
    ch2_rxphsetinitreq : in STD_LOGIC;
    ch2_rxphshift180 : in STD_LOGIC;
    ch2_rxphshift180done : out STD_LOGIC;
    ch2_rxpmaresetmask : in STD_LOGIC_VECTOR ( 6 downto 0 );
    ch2_rxpolarity : in STD_LOGIC;
    ch2_rxprbscntreset : in STD_LOGIC;
    ch2_rxprbserr : out STD_LOGIC;
    ch2_rxprbslocked : out STD_LOGIC;
    ch2_rxprbssel : in STD_LOGIC_VECTOR ( 3 downto 0 );
    ch2_rxrate : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch2_rxresetmode : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch2_rxmstreset : in STD_LOGIC;
    ch2_rxmstdatapathreset : in STD_LOGIC;
    ch2_rxmstresetdone : out STD_LOGIC;
    ch2_rxslide : in STD_LOGIC;
    ch2_rxsliderdy : out STD_LOGIC;
    ch2_rxstartofseq : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch2_rxstatus : out STD_LOGIC_VECTOR ( 2 downto 0 );
    ch2_rxsyncallin : in STD_LOGIC;
    ch2_rxsyncdone : out STD_LOGIC;
    ch2_rxtermination : in STD_LOGIC;
    ch2_rxvalid : out STD_LOGIC;
    ch2_cdrbmcdrreq : in STD_LOGIC;
    ch2_cdrfreqos : in STD_LOGIC;
    ch2_cdrincpctrl : in STD_LOGIC;
    ch2_cdrstepdir : in STD_LOGIC;
    ch2_cdrstepsq : in STD_LOGIC;
    ch2_cdrstepsx : in STD_LOGIC;
    ch2_eyescanreset : in STD_LOGIC;
    ch2_eyescantrigger : in STD_LOGIC;
    ch2_eyescandataerror : out STD_LOGIC;
    ch2_cfokovrdrdy0 : out STD_LOGIC;
    ch2_cfokovrdrdy1 : out STD_LOGIC;
    ch2_rxdataextendrsvd : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch2_rxdccdone : out STD_LOGIC;
    ch2_rxosintstarted : out STD_LOGIC;
    ch2_rxosintstrobedone : out STD_LOGIC;
    ch2_rxosintstrobestarted : out STD_LOGIC;
    ch2_cfokovrdfinish : in STD_LOGIC;
    ch2_cfokovrdpulse : in STD_LOGIC;
    ch2_cfokovrdstart : in STD_LOGIC;
    ch2_rxoutclk : out STD_LOGIC;
    ch2_rxusrclk : in STD_LOGIC;
    ch3_rxdata : out STD_LOGIC_VECTOR ( 127 downto 0 );
    ch3_rxdatavalid : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch3_rxheader : out STD_LOGIC_VECTOR ( 5 downto 0 );
    ch3_rxgearboxslip : in STD_LOGIC;
    ch3_rxlatclk : in STD_LOGIC;
    ch3_gtrxreset : in STD_LOGIC;
    ch3_rxprogdivreset : in STD_LOGIC;
    ch3_rxuserrdy : in STD_LOGIC;
    ch3_rxprogdivresetdone : out STD_LOGIC;
    ch3_rxpmaresetdone : out STD_LOGIC;
    ch3_rxresetdone : out STD_LOGIC;
    ch3_rx10gstat : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch3_rxbufstatus : out STD_LOGIC_VECTOR ( 2 downto 0 );
    ch3_rxbyteisaligned : out STD_LOGIC;
    ch3_rxbyterealign : out STD_LOGIC;
    ch3_rxcdrhold : in STD_LOGIC;
    ch3_rxcdrlock : out STD_LOGIC;
    ch3_rxcdrovrden : in STD_LOGIC;
    ch3_rxcdrphdone : out STD_LOGIC;
    ch3_rxcdrreset : in STD_LOGIC;
    ch3_rxchanbondseq : out STD_LOGIC;
    ch3_rxchanisaligned : out STD_LOGIC;
    ch3_rxchanrealign : out STD_LOGIC;
    ch3_rxchbondi : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch3_rxchbondo : out STD_LOGIC_VECTOR ( 4 downto 0 );
    ch3_rxclkcorcnt : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch3_rxcominitdet : out STD_LOGIC;
    ch3_rxcommadet : out STD_LOGIC;
    ch3_rxcomsasdet : out STD_LOGIC;
    ch3_rxcomwakedet : out STD_LOGIC;
    ch3_rxctrl0 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    ch3_rxctrl1 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    ch3_rxctrl2 : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch3_rxctrl3 : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch3_rxdapicodeovrden : in STD_LOGIC;
    ch3_rxdapicodereset : in STD_LOGIC;
    ch3_rxdlyalignerr : out STD_LOGIC;
    ch3_rxdlyalignprog : out STD_LOGIC;
    ch3_rxdlyalignreq : in STD_LOGIC;
    ch3_rxelecidle : out STD_LOGIC;
    ch3_rxeqtraining : in STD_LOGIC;
    ch3_rxfinealigndone : out STD_LOGIC;
    ch3_rxheadervalid : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch3_rxlpmen : in STD_LOGIC;
    ch3_rxmldchaindone : in STD_LOGIC;
    ch3_rxmldchainreq : in STD_LOGIC;
    ch3_rxmlfinealignreq : in STD_LOGIC;
    ch3_rxoobreset : in STD_LOGIC;
    ch3_rxosintdone : out STD_LOGIC;
    ch3_rxpcsresetmask : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch3_rxpd : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch3_rxphaligndone : out STD_LOGIC;
    ch3_rxphalignerr : out STD_LOGIC;
    ch3_rxphalignreq : in STD_LOGIC;
    ch3_rxphalignresetmask : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch3_rxphdlypd : in STD_LOGIC;
    ch3_rxphdlyreset : in STD_LOGIC;
    ch3_rxphdlyresetdone : out STD_LOGIC;
    ch3_rxphsetinitdone : out STD_LOGIC;
    ch3_rxphsetinitreq : in STD_LOGIC;
    ch3_rxphshift180 : in STD_LOGIC;
    ch3_rxphshift180done : out STD_LOGIC;
    ch3_rxpmaresetmask : in STD_LOGIC_VECTOR ( 6 downto 0 );
    ch3_rxpolarity : in STD_LOGIC;
    ch3_rxprbscntreset : in STD_LOGIC;
    ch3_rxprbserr : out STD_LOGIC;
    ch3_rxprbslocked : out STD_LOGIC;
    ch3_rxprbssel : in STD_LOGIC_VECTOR ( 3 downto 0 );
    ch3_rxrate : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch3_rxresetmode : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch3_rxmstreset : in STD_LOGIC;
    ch3_rxmstdatapathreset : in STD_LOGIC;
    ch3_rxmstresetdone : out STD_LOGIC;
    ch3_rxslide : in STD_LOGIC;
    ch3_rxsliderdy : out STD_LOGIC;
    ch3_rxstartofseq : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch3_rxstatus : out STD_LOGIC_VECTOR ( 2 downto 0 );
    ch3_rxsyncallin : in STD_LOGIC;
    ch3_rxsyncdone : out STD_LOGIC;
    ch3_rxtermination : in STD_LOGIC;
    ch3_rxvalid : out STD_LOGIC;
    ch3_cdrbmcdrreq : in STD_LOGIC;
    ch3_cdrfreqos : in STD_LOGIC;
    ch3_cdrincpctrl : in STD_LOGIC;
    ch3_cdrstepdir : in STD_LOGIC;
    ch3_cdrstepsq : in STD_LOGIC;
    ch3_cdrstepsx : in STD_LOGIC;
    ch3_eyescanreset : in STD_LOGIC;
    ch3_eyescantrigger : in STD_LOGIC;
    ch3_eyescandataerror : out STD_LOGIC;
    ch3_cfokovrdrdy0 : out STD_LOGIC;
    ch3_cfokovrdrdy1 : out STD_LOGIC;
    ch3_rxdataextendrsvd : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch3_rxdccdone : out STD_LOGIC;
    ch3_rxosintstarted : out STD_LOGIC;
    ch3_rxosintstrobedone : out STD_LOGIC;
    ch3_rxosintstrobestarted : out STD_LOGIC;
    ch3_cfokovrdfinish : in STD_LOGIC;
    ch3_cfokovrdpulse : in STD_LOGIC;
    ch3_cfokovrdstart : in STD_LOGIC;
    ch3_rxoutclk : out STD_LOGIC;
    ch3_rxusrclk : in STD_LOGIC;
    ch0_bufgtce : out STD_LOGIC;
    ch0_bufgtrst : out STD_LOGIC;
    ch0_bufgtcemask : out STD_LOGIC_VECTOR ( 3 downto 0 );
    ch0_bufgtrstmask : out STD_LOGIC_VECTOR ( 3 downto 0 );
    ch0_bufgtdiv : out STD_LOGIC_VECTOR ( 11 downto 0 );
    ch0_clkrsvd0 : in STD_LOGIC;
    ch0_clkrsvd1 : in STD_LOGIC;
    ch0_dmonitorclk : in STD_LOGIC;
    ch0_phyesmadaptsave : in STD_LOGIC;
    ch0_iloresetmask : in STD_LOGIC;
    ch0_loopback : in STD_LOGIC_VECTOR ( 2 downto 0 );
    ch0_dmonfiforeset : in STD_LOGIC;
    ch0_pcsrsvdin : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ch0_gtrsvd : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ch0_tstin : in STD_LOGIC_VECTOR ( 19 downto 0 );
    ch0_pcsrsvdout : out STD_LOGIC_VECTOR ( 15 downto 0 );
    ch0_pinrsvdas : out STD_LOGIC_VECTOR ( 15 downto 0 );
    ch0_dmonitoroutclk : out STD_LOGIC;
    ch0_resetexception : out STD_LOGIC;
    ch0_dmonitorout : out STD_LOGIC_VECTOR ( 31 downto 0 );
    ch0_phyready : out STD_LOGIC;
    ch0_hsdppcsreset : in STD_LOGIC;
    ch1_bufgtce : out STD_LOGIC;
    ch1_bufgtrst : out STD_LOGIC;
    ch1_bufgtcemask : out STD_LOGIC_VECTOR ( 3 downto 0 );
    ch1_bufgtrstmask : out STD_LOGIC_VECTOR ( 3 downto 0 );
    ch1_bufgtdiv : out STD_LOGIC_VECTOR ( 11 downto 0 );
    ch1_clkrsvd0 : in STD_LOGIC;
    ch1_clkrsvd1 : in STD_LOGIC;
    ch1_dmonitorclk : in STD_LOGIC;
    ch1_phyesmadaptsave : in STD_LOGIC;
    ch1_iloresetmask : in STD_LOGIC;
    ch1_loopback : in STD_LOGIC_VECTOR ( 2 downto 0 );
    ch1_dmonfiforeset : in STD_LOGIC;
    ch1_pcsrsvdin : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ch1_gtrsvd : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ch1_tstin : in STD_LOGIC_VECTOR ( 19 downto 0 );
    ch1_pcsrsvdout : out STD_LOGIC_VECTOR ( 15 downto 0 );
    ch1_pinrsvdas : out STD_LOGIC_VECTOR ( 15 downto 0 );
    ch1_dmonitoroutclk : out STD_LOGIC;
    ch1_resetexception : out STD_LOGIC;
    ch1_dmonitorout : out STD_LOGIC_VECTOR ( 31 downto 0 );
    ch1_phyready : out STD_LOGIC;
    ch1_hsdppcsreset : in STD_LOGIC;
    ch2_bufgtce : out STD_LOGIC;
    ch2_bufgtrst : out STD_LOGIC;
    ch2_bufgtcemask : out STD_LOGIC_VECTOR ( 3 downto 0 );
    ch2_bufgtrstmask : out STD_LOGIC_VECTOR ( 3 downto 0 );
    ch2_bufgtdiv : out STD_LOGIC_VECTOR ( 11 downto 0 );
    ch2_clkrsvd0 : in STD_LOGIC;
    ch2_clkrsvd1 : in STD_LOGIC;
    ch2_dmonitorclk : in STD_LOGIC;
    ch2_phyesmadaptsave : in STD_LOGIC;
    ch2_iloresetmask : in STD_LOGIC;
    ch2_loopback : in STD_LOGIC_VECTOR ( 2 downto 0 );
    ch2_dmonfiforeset : in STD_LOGIC;
    ch2_pcsrsvdin : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ch2_gtrsvd : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ch2_tstin : in STD_LOGIC_VECTOR ( 19 downto 0 );
    ch2_pcsrsvdout : out STD_LOGIC_VECTOR ( 15 downto 0 );
    ch2_pinrsvdas : out STD_LOGIC_VECTOR ( 15 downto 0 );
    ch2_dmonitoroutclk : out STD_LOGIC;
    ch2_resetexception : out STD_LOGIC;
    ch2_dmonitorout : out STD_LOGIC_VECTOR ( 31 downto 0 );
    ch2_phyready : out STD_LOGIC;
    ch2_hsdppcsreset : in STD_LOGIC;
    ch3_bufgtce : out STD_LOGIC;
    ch3_bufgtrst : out STD_LOGIC;
    ch3_bufgtcemask : out STD_LOGIC_VECTOR ( 3 downto 0 );
    ch3_bufgtrstmask : out STD_LOGIC_VECTOR ( 3 downto 0 );
    ch3_bufgtdiv : out STD_LOGIC_VECTOR ( 11 downto 0 );
    ch3_clkrsvd0 : in STD_LOGIC;
    ch3_clkrsvd1 : in STD_LOGIC;
    ch3_dmonitorclk : in STD_LOGIC;
    ch3_phyesmadaptsave : in STD_LOGIC;
    ch3_iloresetmask : in STD_LOGIC;
    ch3_loopback : in STD_LOGIC_VECTOR ( 2 downto 0 );
    ch3_dmonfiforeset : in STD_LOGIC;
    ch3_pcsrsvdin : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ch3_gtrsvd : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ch3_tstin : in STD_LOGIC_VECTOR ( 19 downto 0 );
    ch3_pcsrsvdout : out STD_LOGIC_VECTOR ( 15 downto 0 );
    ch3_pinrsvdas : out STD_LOGIC_VECTOR ( 15 downto 0 );
    ch3_dmonitoroutclk : out STD_LOGIC;
    ch3_resetexception : out STD_LOGIC;
    ch3_dmonitorout : out STD_LOGIC_VECTOR ( 31 downto 0 );
    ch3_phyready : out STD_LOGIC;
    ch3_hsdppcsreset : in STD_LOGIC;
    resetdone_northin : in STD_LOGIC_VECTOR ( 1 downto 0 );
    resetdone_southin : in STD_LOGIC_VECTOR ( 1 downto 0 );
    resetdone_northout : out STD_LOGIC_VECTOR ( 1 downto 0 );
    resetdone_southout : out STD_LOGIC_VECTOR ( 1 downto 0 );
    txpinorthin : in STD_LOGIC_VECTOR ( 3 downto 0 );
    rxpinorthin : in STD_LOGIC_VECTOR ( 3 downto 0 );
    txpisouthin : in STD_LOGIC_VECTOR ( 3 downto 0 );
    rxpisouthin : in STD_LOGIC_VECTOR ( 3 downto 0 );
    pipenorthin : in STD_LOGIC_VECTOR ( 5 downto 0 );
    pipesouthin : in STD_LOGIC_VECTOR ( 5 downto 0 );
    txpinorthout : out STD_LOGIC_VECTOR ( 3 downto 0 );
    txpisouthout : out STD_LOGIC_VECTOR ( 3 downto 0 );
    rxpinorthout : out STD_LOGIC_VECTOR ( 3 downto 0 );
    rxpisouthout : out STD_LOGIC_VECTOR ( 3 downto 0 );
    pipenorthout : out STD_LOGIC_VECTOR ( 5 downto 0 );
    pipesouthout : out STD_LOGIC_VECTOR ( 5 downto 0 );
    GT_REFCLK0 : in STD_LOGIC;
    bgbypassb : in STD_LOGIC;
    bgmonitorenb : in STD_LOGIC;
    bgpdb : in STD_LOGIC;
    bgrcalovrdenb : in STD_LOGIC;
    bgrcalovrd : in STD_LOGIC_VECTOR ( 4 downto 0 );
    debugtraceready : in STD_LOGIC;
    debugtraceclk : in STD_LOGIC;
    rcalenb : in STD_LOGIC;
    trigackout0 : in STD_LOGIC;
    trigin0 : in STD_LOGIC;
    ubenable : in STD_LOGIC;
    ubiolmbrst : in STD_LOGIC;
    ubmbrst : in STD_LOGIC;
    ubintr : in STD_LOGIC_VECTOR ( 11 downto 0 );
    ubrxuart : in STD_LOGIC;
    ctrlrsvdin0 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ctrlrsvdin1 : in STD_LOGIC_VECTOR ( 13 downto 0 );
    gpi : in STD_LOGIC_VECTOR ( 15 downto 0 );
    refclk0_clktestsig : in STD_LOGIC;
    refclk1_clktestsig : in STD_LOGIC;
    correcterr : out STD_LOGIC;
    debugtracetvalid : out STD_LOGIC;
    debugtracetdata : out STD_LOGIC_VECTOR ( 15 downto 0 );
    refclk0_gtrefclkpdint : out STD_LOGIC;
    refclk0_clktestsigint : out STD_LOGIC;
    refclk1_gtrefclkpdint : out STD_LOGIC;
    refclk1_clktestsigint : out STD_LOGIC;
    trigackin0 : out STD_LOGIC;
    trigout0 : out STD_LOGIC;
    ubinterrupt : out STD_LOGIC;
    ubtxuart : out STD_LOGIC;
    uncorrecterr : out STD_LOGIC;
    ctrlrsvdout : out STD_LOGIC_VECTOR ( 31 downto 0 );
    gpo : out STD_LOGIC_VECTOR ( 15 downto 0 );
    hsclk0_rxrecclksel : out STD_LOGIC_VECTOR ( 1 downto 0 );
    hsclk1_rxrecclksel : out STD_LOGIC_VECTOR ( 1 downto 0 );
    altclk : in STD_LOGIC;
    hsclk0_lcpllclkrsvd0 : in STD_LOGIC;
    hsclk0_lcpllclkrsvd1 : in STD_LOGIC;
    hsclk0_rpllclkrsvd0 : in STD_LOGIC;
    hsclk0_rpllclkrsvd1 : in STD_LOGIC;
    hsclk1_lcpllclkrsvd0 : in STD_LOGIC;
    hsclk1_lcpllclkrsvd1 : in STD_LOGIC;
    hsclk1_rpllclkrsvd0 : in STD_LOGIC;
    hsclk1_rpllclkrsvd1 : in STD_LOGIC;
    hsclk0_lcpllrsvd0 : in STD_LOGIC_VECTOR ( 7 downto 0 );
    hsclk0_lcpllrsvd1 : in STD_LOGIC_VECTOR ( 7 downto 0 );
    hsclk0_rpllrsvd0 : in STD_LOGIC_VECTOR ( 7 downto 0 );
    hsclk0_rpllrsvd1 : in STD_LOGIC_VECTOR ( 7 downto 0 );
    hsclk1_lcpllrsvd0 : in STD_LOGIC_VECTOR ( 7 downto 0 );
    hsclk1_lcpllrsvd1 : in STD_LOGIC_VECTOR ( 7 downto 0 );
    hsclk1_rpllrsvd0 : in STD_LOGIC_VECTOR ( 7 downto 0 );
    hsclk1_rpllrsvd1 : in STD_LOGIC_VECTOR ( 7 downto 0 );
    hsclk0_lcpllrsvdout : out STD_LOGIC_VECTOR ( 7 downto 0 );
    hsclk1_lcpllrsvdout : out STD_LOGIC_VECTOR ( 7 downto 0 );
    hsclk0_rpllrsvdout : out STD_LOGIC_VECTOR ( 7 downto 0 );
    hsclk1_rpllrsvdout : out STD_LOGIC_VECTOR ( 7 downto 0 );
    apb3clk : in STD_LOGIC;
    apb3paddr : in STD_LOGIC_VECTOR ( 15 downto 0 );
    apb3penable : in STD_LOGIC;
    apb3presetn : in STD_LOGIC;
    apb3prdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    apb3psel : in STD_LOGIC;
    apb3pslverr : out STD_LOGIC;
    apb3pready : out STD_LOGIC;
    apb3pwdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    apb3pwrite : in STD_LOGIC;
    rxp : in STD_LOGIC_VECTOR ( 3 downto 0 );
    rxn : in STD_LOGIC_VECTOR ( 3 downto 0 );
    txp : out STD_LOGIC_VECTOR ( 3 downto 0 );
    txn : out STD_LOGIC_VECTOR ( 3 downto 0 )
  );

end decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix;

architecture stub of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
attribute syn_black_box : boolean;
attribute black_box_pad_pin : string;
attribute syn_black_box of stub : architecture is true;
attribute black_box_pad_pin of stub : architecture is "rxmarginclk,hsclk0_lcpllreset,hsclk0_rpllreset,hsclk1_lcpllreset,hsclk1_rpllreset,hsclk0_lcplllock,hsclk1_lcplllock,hsclk0_rplllock,hsclk1_rplllock,gtpowergood,ch0_pcierstb,ch1_pcierstb,ch2_pcierstb,ch3_pcierstb,pcielinkreachtarget,pcieltssm[5:0],rxmarginreqack,rxmarginrescmd[3:0],rxmarginreslanenum[1:0],rxmarginrespayld[7:0],rxmarginresreq,rxmarginreqcmd[3:0],rxmarginreqlanenum[1:0],rxmarginreqpayld[7:0],rxmarginreqreq,rxmarginresack,ch0_iloreset,ch1_iloreset,ch2_iloreset,ch3_iloreset,ch0_iloresetdone,ch1_iloresetdone,ch2_iloresetdone,ch3_iloresetdone,ch0_phystatus,ch1_phystatus,ch2_phystatus,ch3_phystatus,hsclk0_lcpllfbclklost,hsclk0_lcpllrefclklost,hsclk0_lcpllrefclkmonitor,hsclk0_rpllfbclklost,hsclk0_rpllrefclklost,hsclk0_rpllrefclkmonitor,hsclk1_lcpllfbclklost,hsclk1_lcpllrefclklost,hsclk1_lcpllrefclkmonitor,hsclk1_rpllfbclklost,hsclk1_rpllrefclklost,hsclk1_rpllrefclkmonitor,hsclk0_lcpllpd,hsclk0_rpllpd,hsclk0_lcpllresetbypassmode,hsclk0_lcpllsdmtoggle,hsclk0_rpllresetbypassmode,hsclk0_rpllsdmtoggle,hsclk1_lcpllpd,hsclk1_lcpllresetbypassmode,hsclk1_lcpllsdmtoggle,hsclk1_rpllpd,hsclk1_rpllresetbypassmode,hsclk1_rpllsdmtoggle,refclk0_gtrefclkpd,refclk1_gtrefclkpd,hsclk0_lcpllrefclksel[2:0],hsclk1_lcpllrefclksel[2:0],hsclk0_rpllrefclksel[2:0],hsclk1_rpllrefclksel[2:0],hsclk0_lcpllfbdiv[7:0],hsclk0_rpllfbdiv[7:0],hsclk1_lcpllfbdiv[7:0],hsclk1_rpllfbdiv[7:0],hsclk0_rxrecclkout0,hsclk0_rxrecclkout1,hsclk1_rxrecclkout0,hsclk1_rxrecclkout1,hsclk0_lcpllsdmdata[25:0],hsclk1_lcpllsdmdata[25:0],hsclk0_rpllsdmdata[25:0],hsclk1_rpllsdmdata[25:0],hsclk0_lcpllresetmask[1:0],hsclk1_lcpllresetmask[1:0],hsclk0_rpllresetmask[1:0],hsclk1_rpllresetmask[1:0],ch0_txdata[127:0],ch0_txheader[5:0],ch0_txsequence[6:0],ch0_gttxreset,ch0_txprogdivreset,ch0_txuserrdy,ch0_txphalignresetmask[1:0],ch0_txcominit,ch0_txcomsas,ch0_txcomwake,ch0_txdapicodeovrden,ch0_txdapicodereset,ch0_txdetectrx,ch0_txlatclk,ch0_txphdlytstclk,ch0_txdlyalignreq,ch0_txelecidle,ch0_txinhibit,ch0_txmldchaindone,ch0_txmldchainreq,ch0_txoneszeros,ch0_txpausedelayalign,ch0_txpcsresetmask,ch0_txphalignreq,ch0_txphdlypd,ch0_txphdlyreset,ch0_txphsetinitreq,ch0_txphshift180,ch0_txpicodeovrden,ch0_txpicodereset,ch0_txpippmen,ch0_txpisopd,ch0_txpolarity,ch0_txprbsforceerr,ch0_txswing,ch0_txsyncallin,ch0_tx10gstat,ch0_txcomfinish,ch0_txdccdone,ch0_txdlyalignerr,ch0_txdlyalignprog,ch0_txphaligndone,ch0_txphalignerr,ch0_txphalignoutrsvd,ch0_txphdlyresetdone,ch0_txphsetinitdone,ch0_txphshift180done,ch0_txsyncdone,ch0_txbufstatus[1:0],ch0_txctrl0[15:0],ch0_txctrl1[15:0],ch0_txdeemph[1:0],ch0_txpd[1:0],ch0_txresetmode[1:0],ch0_txmstreset,ch0_txmstdatapathreset,ch0_txmstresetdone,ch0_txmargin[2:0],ch0_txpmaresetmask[2:0],ch0_txprbssel[3:0],ch0_txdiffctrl[4:0],ch0_txpippmstepsize[4:0],ch0_txpostcursor[4:0],ch0_txprecursor[4:0],ch0_txmaincursor[6:0],ch0_txctrl2[7:0],ch0_txrate[7:0],ch0_txprogdivresetdone,ch0_txpmaresetdone,ch0_txresetdone,ch0_txdataextendrsvd[7:0],ch0_txoutclk,ch0_txusrclk,ch1_txdata[127:0],ch1_txheader[5:0],ch1_txsequence[6:0],ch1_gttxreset,ch1_txprogdivreset,ch1_txuserrdy,ch1_txphalignresetmask[1:0],ch1_txcominit,ch1_txcomsas,ch1_txcomwake,ch1_txdapicodeovrden,ch1_txdapicodereset,ch1_txdetectrx,ch1_txlatclk,ch1_txphdlytstclk,ch1_txdlyalignreq,ch1_txelecidle,ch1_txinhibit,ch1_txmldchaindone,ch1_txmldchainreq,ch1_txoneszeros,ch1_txpausedelayalign,ch1_txpcsresetmask,ch1_txphalignreq,ch1_txphdlypd,ch1_txphdlyreset,ch1_txphsetinitreq,ch1_txphshift180,ch1_txpicodeovrden,ch1_txpicodereset,ch1_txpippmen,ch1_txpisopd,ch1_txpolarity,ch1_txprbsforceerr,ch1_txswing,ch1_txsyncallin,ch1_tx10gstat,ch1_txcomfinish,ch1_txdccdone,ch1_txdlyalignerr,ch1_txdlyalignprog,ch1_txphaligndone,ch1_txphalignerr,ch1_txphalignoutrsvd,ch1_txphdlyresetdone,ch1_txphsetinitdone,ch1_txphshift180done,ch1_txsyncdone,ch1_txbufstatus[1:0],ch1_txctrl0[15:0],ch1_txctrl1[15:0],ch1_txdeemph[1:0],ch1_txpd[1:0],ch1_txresetmode[1:0],ch1_txmstreset,ch1_txmstdatapathreset,ch1_txmstresetdone,ch1_txmargin[2:0],ch1_txpmaresetmask[2:0],ch1_txprbssel[3:0],ch1_txdiffctrl[4:0],ch1_txpippmstepsize[4:0],ch1_txpostcursor[4:0],ch1_txprecursor[4:0],ch1_txmaincursor[6:0],ch1_txctrl2[7:0],ch1_txrate[7:0],ch1_txprogdivresetdone,ch1_txpmaresetdone,ch1_txresetdone,ch1_txdataextendrsvd[7:0],ch1_txoutclk,ch1_txusrclk,ch2_txdata[127:0],ch2_txheader[5:0],ch2_txsequence[6:0],ch2_gttxreset,ch2_txprogdivreset,ch2_txuserrdy,ch2_txphalignresetmask[1:0],ch2_txcominit,ch2_txcomsas,ch2_txcomwake,ch2_txdapicodeovrden,ch2_txdapicodereset,ch2_txdetectrx,ch2_txlatclk,ch2_txphdlytstclk,ch2_txdlyalignreq,ch2_txelecidle,ch2_txinhibit,ch2_txmldchaindone,ch2_txmldchainreq,ch2_txoneszeros,ch2_txpausedelayalign,ch2_txpcsresetmask,ch2_txphalignreq,ch2_txphdlypd,ch2_txphdlyreset,ch2_txphsetinitreq,ch2_txphshift180,ch2_txpicodeovrden,ch2_txpicodereset,ch2_txpippmen,ch2_txpisopd,ch2_txpolarity,ch2_txprbsforceerr,ch2_txswing,ch2_txsyncallin,ch2_tx10gstat,ch2_txcomfinish,ch2_txdccdone,ch2_txdlyalignerr,ch2_txdlyalignprog,ch2_txphaligndone,ch2_txphalignerr,ch2_txphalignoutrsvd,ch2_txphdlyresetdone,ch2_txphsetinitdone,ch2_txphshift180done,ch2_txsyncdone,ch2_txbufstatus[1:0],ch2_txctrl0[15:0],ch2_txctrl1[15:0],ch2_txdeemph[1:0],ch2_txpd[1:0],ch2_txresetmode[1:0],ch2_txmstreset,ch2_txmstdatapathreset,ch2_txmstresetdone,ch2_txmargin[2:0],ch2_txpmaresetmask[2:0],ch2_txprbssel[3:0],ch2_txdiffctrl[4:0],ch2_txpippmstepsize[4:0],ch2_txpostcursor[4:0],ch2_txprecursor[4:0],ch2_txmaincursor[6:0],ch2_txctrl2[7:0],ch2_txrate[7:0],ch2_txprogdivresetdone,ch2_txpmaresetdone,ch2_txresetdone,ch2_txdataextendrsvd[7:0],ch2_txoutclk,ch2_txusrclk,ch3_txdata[127:0],ch3_txheader[5:0],ch3_txsequence[6:0],ch3_gttxreset,ch3_txprogdivreset,ch3_txuserrdy,ch3_txphalignresetmask[1:0],ch3_txcominit,ch3_txcomsas,ch3_txcomwake,ch3_txdapicodeovrden,ch3_txdapicodereset,ch3_txdetectrx,ch3_txlatclk,ch3_txphdlytstclk,ch3_txdlyalignreq,ch3_txelecidle,ch3_txinhibit,ch3_txmldchaindone,ch3_txmldchainreq,ch3_txoneszeros,ch3_txpausedelayalign,ch3_txpcsresetmask,ch3_txphalignreq,ch3_txphdlypd,ch3_txphdlyreset,ch3_txphsetinitreq,ch3_txphshift180,ch3_txpicodeovrden,ch3_txpicodereset,ch3_txpippmen,ch3_txpisopd,ch3_txpolarity,ch3_txprbsforceerr,ch3_txswing,ch3_txsyncallin,ch3_tx10gstat,ch3_txcomfinish,ch3_txdccdone,ch3_txdlyalignerr,ch3_txdlyalignprog,ch3_txphaligndone,ch3_txphalignerr,ch3_txphalignoutrsvd,ch3_txphdlyresetdone,ch3_txphsetinitdone,ch3_txphshift180done,ch3_txsyncdone,ch3_txbufstatus[1:0],ch3_txctrl0[15:0],ch3_txctrl1[15:0],ch3_txdeemph[1:0],ch3_txpd[1:0],ch3_txresetmode[1:0],ch3_txmstreset,ch3_txmstdatapathreset,ch3_txmstresetdone,ch3_txmargin[2:0],ch3_txpmaresetmask[2:0],ch3_txprbssel[3:0],ch3_txdiffctrl[4:0],ch3_txpippmstepsize[4:0],ch3_txpostcursor[4:0],ch3_txprecursor[4:0],ch3_txmaincursor[6:0],ch3_txctrl2[7:0],ch3_txrate[7:0],ch3_txprogdivresetdone,ch3_txpmaresetdone,ch3_txresetdone,ch3_txdataextendrsvd[7:0],ch3_txoutclk,ch3_txusrclk,ch0_rxdata[127:0],ch0_rxdatavalid[1:0],ch0_rxheader[5:0],ch0_rxgearboxslip,ch0_rxlatclk,ch0_gtrxreset,ch0_rxprogdivreset,ch0_rxuserrdy,ch0_rxprogdivresetdone,ch0_rxpmaresetdone,ch0_rxresetdone,ch0_rx10gstat[7:0],ch0_rxbufstatus[2:0],ch0_rxbyteisaligned,ch0_rxbyterealign,ch0_rxcdrhold,ch0_rxcdrlock,ch0_rxcdrovrden,ch0_rxcdrphdone,ch0_rxcdrreset,ch0_rxchanbondseq,ch0_rxchanisaligned,ch0_rxchanrealign,ch0_rxchbondi[4:0],ch0_rxchbondo[4:0],ch0_rxclkcorcnt[1:0],ch0_rxcominitdet,ch0_rxcommadet,ch0_rxcomsasdet,ch0_rxcomwakedet,ch0_rxctrl0[15:0],ch0_rxctrl1[15:0],ch0_rxctrl2[7:0],ch0_rxctrl3[7:0],ch0_rxdapicodeovrden,ch0_rxdapicodereset,ch0_rxdlyalignerr,ch0_rxdlyalignprog,ch0_rxdlyalignreq,ch0_rxelecidle,ch0_rxeqtraining,ch0_rxfinealigndone,ch0_rxheadervalid[1:0],ch0_rxlpmen,ch0_rxmldchaindone,ch0_rxmldchainreq,ch0_rxmlfinealignreq,ch0_rxoobreset,ch0_rxosintdone,ch0_rxpcsresetmask[4:0],ch0_rxpd[1:0],ch0_rxphaligndone,ch0_rxphalignerr,ch0_rxphalignreq,ch0_rxphalignresetmask[1:0],ch0_rxphdlypd,ch0_rxphdlyreset,ch0_rxphdlyresetdone,ch0_rxphsetinitdone,ch0_rxphsetinitreq,ch0_rxphshift180,ch0_rxphshift180done,ch0_rxpmaresetmask[6:0],ch0_rxpolarity,ch0_rxprbscntreset,ch0_rxprbserr,ch0_rxprbslocked,ch0_rxprbssel[3:0],ch0_rxrate[7:0],ch0_rxresetmode[1:0],ch0_rxmstreset,ch0_rxmstdatapathreset,ch0_rxmstresetdone,ch0_rxslide,ch0_rxsliderdy,ch0_rxstartofseq[1:0],ch0_rxstatus[2:0],ch0_rxsyncallin,ch0_rxsyncdone,ch0_rxtermination,ch0_rxvalid,ch0_cdrbmcdrreq,ch0_cdrfreqos,ch0_cdrincpctrl,ch0_cdrstepdir,ch0_cdrstepsq,ch0_cdrstepsx,ch0_eyescanreset,ch0_eyescantrigger,ch0_eyescandataerror,ch0_cfokovrdrdy0,ch0_cfokovrdrdy1,ch0_rxdataextendrsvd[7:0],ch0_rxdccdone,ch0_rxosintstarted,ch0_rxosintstrobedone,ch0_rxosintstrobestarted,ch0_cfokovrdfinish,ch0_cfokovrdpulse,ch0_cfokovrdstart,ch0_rxoutclk,ch0_rxusrclk,ch1_rxdata[127:0],ch1_rxdatavalid[1:0],ch1_rxheader[5:0],ch1_rxgearboxslip,ch1_rxlatclk,ch1_gtrxreset,ch1_rxprogdivreset,ch1_rxuserrdy,ch1_rxprogdivresetdone,ch1_rxpmaresetdone,ch1_rxresetdone,ch1_rx10gstat[7:0],ch1_rxbufstatus[2:0],ch1_rxbyteisaligned,ch1_rxbyterealign,ch1_rxcdrhold,ch1_rxcdrlock,ch1_rxcdrovrden,ch1_rxcdrphdone,ch1_rxcdrreset,ch1_rxchanbondseq,ch1_rxchanisaligned,ch1_rxchanrealign,ch1_rxchbondi[4:0],ch1_rxchbondo[4:0],ch1_rxclkcorcnt[1:0],ch1_rxcominitdet,ch1_rxcommadet,ch1_rxcomsasdet,ch1_rxcomwakedet,ch1_rxctrl0[15:0],ch1_rxctrl1[15:0],ch1_rxctrl2[7:0],ch1_rxctrl3[7:0],ch1_rxdapicodeovrden,ch1_rxdapicodereset,ch1_rxdlyalignerr,ch1_rxdlyalignprog,ch1_rxdlyalignreq,ch1_rxelecidle,ch1_rxeqtraining,ch1_rxfinealigndone,ch1_rxheadervalid[1:0],ch1_rxlpmen,ch1_rxmldchaindone,ch1_rxmldchainreq,ch1_rxmlfinealignreq,ch1_rxoobreset,ch1_rxosintdone,ch1_rxpcsresetmask[4:0],ch1_rxpd[1:0],ch1_rxphaligndone,ch1_rxphalignerr,ch1_rxphalignreq,ch1_rxphalignresetmask[1:0],ch1_rxphdlypd,ch1_rxphdlyreset,ch1_rxphdlyresetdone,ch1_rxphsetinitdone,ch1_rxphsetinitreq,ch1_rxphshift180,ch1_rxphshift180done,ch1_rxpmaresetmask[6:0],ch1_rxpolarity,ch1_rxprbscntreset,ch1_rxprbserr,ch1_rxprbslocked,ch1_rxprbssel[3:0],ch1_rxrate[7:0],ch1_rxresetmode[1:0],ch1_rxmstreset,ch1_rxmstdatapathreset,ch1_rxmstresetdone,ch1_rxslide,ch1_rxsliderdy,ch1_rxstartofseq[1:0],ch1_rxstatus[2:0],ch1_rxsyncallin,ch1_rxsyncdone,ch1_rxtermination,ch1_rxvalid,ch1_cdrbmcdrreq,ch1_cdrfreqos,ch1_cdrincpctrl,ch1_cdrstepdir,ch1_cdrstepsq,ch1_cdrstepsx,ch1_eyescanreset,ch1_eyescantrigger,ch1_eyescandataerror,ch1_cfokovrdrdy0,ch1_cfokovrdrdy1,ch1_rxdataextendrsvd[7:0],ch1_rxdccdone,ch1_rxosintstarted,ch1_rxosintstrobedone,ch1_rxosintstrobestarted,ch1_cfokovrdfinish,ch1_cfokovrdpulse,ch1_cfokovrdstart,ch1_rxoutclk,ch1_rxusrclk,ch2_rxdata[127:0],ch2_rxdatavalid[1:0],ch2_rxheader[5:0],ch2_rxgearboxslip,ch2_rxlatclk,ch2_gtrxreset,ch2_rxprogdivreset,ch2_rxuserrdy,ch2_rxprogdivresetdone,ch2_rxpmaresetdone,ch2_rxresetdone,ch2_rx10gstat[7:0],ch2_rxbufstatus[2:0],ch2_rxbyteisaligned,ch2_rxbyterealign,ch2_rxcdrhold,ch2_rxcdrlock,ch2_rxcdrovrden,ch2_rxcdrphdone,ch2_rxcdrreset,ch2_rxchanbondseq,ch2_rxchanisaligned,ch2_rxchanrealign,ch2_rxchbondi[4:0],ch2_rxchbondo[4:0],ch2_rxclkcorcnt[1:0],ch2_rxcominitdet,ch2_rxcommadet,ch2_rxcomsasdet,ch2_rxcomwakedet,ch2_rxctrl0[15:0],ch2_rxctrl1[15:0],ch2_rxctrl2[7:0],ch2_rxctrl3[7:0],ch2_rxdapicodeovrden,ch2_rxdapicodereset,ch2_rxdlyalignerr,ch2_rxdlyalignprog,ch2_rxdlyalignreq,ch2_rxelecidle,ch2_rxeqtraining,ch2_rxfinealigndone,ch2_rxheadervalid[1:0],ch2_rxlpmen,ch2_rxmldchaindone,ch2_rxmldchainreq,ch2_rxmlfinealignreq,ch2_rxoobreset,ch2_rxosintdone,ch2_rxpcsresetmask[4:0],ch2_rxpd[1:0],ch2_rxphaligndone,ch2_rxphalignerr,ch2_rxphalignreq,ch2_rxphalignresetmask[1:0],ch2_rxphdlypd,ch2_rxphdlyreset,ch2_rxphdlyresetdone,ch2_rxphsetinitdone,ch2_rxphsetinitreq,ch2_rxphshift180,ch2_rxphshift180done,ch2_rxpmaresetmask[6:0],ch2_rxpolarity,ch2_rxprbscntreset,ch2_rxprbserr,ch2_rxprbslocked,ch2_rxprbssel[3:0],ch2_rxrate[7:0],ch2_rxresetmode[1:0],ch2_rxmstreset,ch2_rxmstdatapathreset,ch2_rxmstresetdone,ch2_rxslide,ch2_rxsliderdy,ch2_rxstartofseq[1:0],ch2_rxstatus[2:0],ch2_rxsyncallin,ch2_rxsyncdone,ch2_rxtermination,ch2_rxvalid,ch2_cdrbmcdrreq,ch2_cdrfreqos,ch2_cdrincpctrl,ch2_cdrstepdir,ch2_cdrstepsq,ch2_cdrstepsx,ch2_eyescanreset,ch2_eyescantrigger,ch2_eyescandataerror,ch2_cfokovrdrdy0,ch2_cfokovrdrdy1,ch2_rxdataextendrsvd[7:0],ch2_rxdccdone,ch2_rxosintstarted,ch2_rxosintstrobedone,ch2_rxosintstrobestarted,ch2_cfokovrdfinish,ch2_cfokovrdpulse,ch2_cfokovrdstart,ch2_rxoutclk,ch2_rxusrclk,ch3_rxdata[127:0],ch3_rxdatavalid[1:0],ch3_rxheader[5:0],ch3_rxgearboxslip,ch3_rxlatclk,ch3_gtrxreset,ch3_rxprogdivreset,ch3_rxuserrdy,ch3_rxprogdivresetdone,ch3_rxpmaresetdone,ch3_rxresetdone,ch3_rx10gstat[7:0],ch3_rxbufstatus[2:0],ch3_rxbyteisaligned,ch3_rxbyterealign,ch3_rxcdrhold,ch3_rxcdrlock,ch3_rxcdrovrden,ch3_rxcdrphdone,ch3_rxcdrreset,ch3_rxchanbondseq,ch3_rxchanisaligned,ch3_rxchanrealign,ch3_rxchbondi[4:0],ch3_rxchbondo[4:0],ch3_rxclkcorcnt[1:0],ch3_rxcominitdet,ch3_rxcommadet,ch3_rxcomsasdet,ch3_rxcomwakedet,ch3_rxctrl0[15:0],ch3_rxctrl1[15:0],ch3_rxctrl2[7:0],ch3_rxctrl3[7:0],ch3_rxdapicodeovrden,ch3_rxdapicodereset,ch3_rxdlyalignerr,ch3_rxdlyalignprog,ch3_rxdlyalignreq,ch3_rxelecidle,ch3_rxeqtraining,ch3_rxfinealigndone,ch3_rxheadervalid[1:0],ch3_rxlpmen,ch3_rxmldchaindone,ch3_rxmldchainreq,ch3_rxmlfinealignreq,ch3_rxoobreset,ch3_rxosintdone,ch3_rxpcsresetmask[4:0],ch3_rxpd[1:0],ch3_rxphaligndone,ch3_rxphalignerr,ch3_rxphalignreq,ch3_rxphalignresetmask[1:0],ch3_rxphdlypd,ch3_rxphdlyreset,ch3_rxphdlyresetdone,ch3_rxphsetinitdone,ch3_rxphsetinitreq,ch3_rxphshift180,ch3_rxphshift180done,ch3_rxpmaresetmask[6:0],ch3_rxpolarity,ch3_rxprbscntreset,ch3_rxprbserr,ch3_rxprbslocked,ch3_rxprbssel[3:0],ch3_rxrate[7:0],ch3_rxresetmode[1:0],ch3_rxmstreset,ch3_rxmstdatapathreset,ch3_rxmstresetdone,ch3_rxslide,ch3_rxsliderdy,ch3_rxstartofseq[1:0],ch3_rxstatus[2:0],ch3_rxsyncallin,ch3_rxsyncdone,ch3_rxtermination,ch3_rxvalid,ch3_cdrbmcdrreq,ch3_cdrfreqos,ch3_cdrincpctrl,ch3_cdrstepdir,ch3_cdrstepsq,ch3_cdrstepsx,ch3_eyescanreset,ch3_eyescantrigger,ch3_eyescandataerror,ch3_cfokovrdrdy0,ch3_cfokovrdrdy1,ch3_rxdataextendrsvd[7:0],ch3_rxdccdone,ch3_rxosintstarted,ch3_rxosintstrobedone,ch3_rxosintstrobestarted,ch3_cfokovrdfinish,ch3_cfokovrdpulse,ch3_cfokovrdstart,ch3_rxoutclk,ch3_rxusrclk,ch0_bufgtce,ch0_bufgtrst,ch0_bufgtcemask[3:0],ch0_bufgtrstmask[3:0],ch0_bufgtdiv[11:0],ch0_clkrsvd0,ch0_clkrsvd1,ch0_dmonitorclk,ch0_phyesmadaptsave,ch0_iloresetmask,ch0_loopback[2:0],ch0_dmonfiforeset,ch0_pcsrsvdin[15:0],ch0_gtrsvd[15:0],ch0_tstin[19:0],ch0_pcsrsvdout[15:0],ch0_pinrsvdas[15:0],ch0_dmonitoroutclk,ch0_resetexception,ch0_dmonitorout[31:0],ch0_phyready,ch0_hsdppcsreset,ch1_bufgtce,ch1_bufgtrst,ch1_bufgtcemask[3:0],ch1_bufgtrstmask[3:0],ch1_bufgtdiv[11:0],ch1_clkrsvd0,ch1_clkrsvd1,ch1_dmonitorclk,ch1_phyesmadaptsave,ch1_iloresetmask,ch1_loopback[2:0],ch1_dmonfiforeset,ch1_pcsrsvdin[15:0],ch1_gtrsvd[15:0],ch1_tstin[19:0],ch1_pcsrsvdout[15:0],ch1_pinrsvdas[15:0],ch1_dmonitoroutclk,ch1_resetexception,ch1_dmonitorout[31:0],ch1_phyready,ch1_hsdppcsreset,ch2_bufgtce,ch2_bufgtrst,ch2_bufgtcemask[3:0],ch2_bufgtrstmask[3:0],ch2_bufgtdiv[11:0],ch2_clkrsvd0,ch2_clkrsvd1,ch2_dmonitorclk,ch2_phyesmadaptsave,ch2_iloresetmask,ch2_loopback[2:0],ch2_dmonfiforeset,ch2_pcsrsvdin[15:0],ch2_gtrsvd[15:0],ch2_tstin[19:0],ch2_pcsrsvdout[15:0],ch2_pinrsvdas[15:0],ch2_dmonitoroutclk,ch2_resetexception,ch2_dmonitorout[31:0],ch2_phyready,ch2_hsdppcsreset,ch3_bufgtce,ch3_bufgtrst,ch3_bufgtcemask[3:0],ch3_bufgtrstmask[3:0],ch3_bufgtdiv[11:0],ch3_clkrsvd0,ch3_clkrsvd1,ch3_dmonitorclk,ch3_phyesmadaptsave,ch3_iloresetmask,ch3_loopback[2:0],ch3_dmonfiforeset,ch3_pcsrsvdin[15:0],ch3_gtrsvd[15:0],ch3_tstin[19:0],ch3_pcsrsvdout[15:0],ch3_pinrsvdas[15:0],ch3_dmonitoroutclk,ch3_resetexception,ch3_dmonitorout[31:0],ch3_phyready,ch3_hsdppcsreset,resetdone_northin[1:0],resetdone_southin[1:0],resetdone_northout[1:0],resetdone_southout[1:0],txpinorthin[3:0],rxpinorthin[3:0],txpisouthin[3:0],rxpisouthin[3:0],pipenorthin[5:0],pipesouthin[5:0],txpinorthout[3:0],txpisouthout[3:0],rxpinorthout[3:0],rxpisouthout[3:0],pipenorthout[5:0],pipesouthout[5:0],GT_REFCLK0,bgbypassb,bgmonitorenb,bgpdb,bgrcalovrdenb,bgrcalovrd[4:0],debugtraceready,debugtraceclk,rcalenb,trigackout0,trigin0,ubenable,ubiolmbrst,ubmbrst,ubintr[11:0],ubrxuart,ctrlrsvdin0[15:0],ctrlrsvdin1[13:0],gpi[15:0],refclk0_clktestsig,refclk1_clktestsig,correcterr,debugtracetvalid,debugtracetdata[15:0],refclk0_gtrefclkpdint,refclk0_clktestsigint,refclk1_gtrefclkpdint,refclk1_clktestsigint,trigackin0,trigout0,ubinterrupt,ubtxuart,uncorrecterr,ctrlrsvdout[31:0],gpo[15:0],hsclk0_rxrecclksel[1:0],hsclk1_rxrecclksel[1:0],altclk,hsclk0_lcpllclkrsvd0,hsclk0_lcpllclkrsvd1,hsclk0_rpllclkrsvd0,hsclk0_rpllclkrsvd1,hsclk1_lcpllclkrsvd0,hsclk1_lcpllclkrsvd1,hsclk1_rpllclkrsvd0,hsclk1_rpllclkrsvd1,hsclk0_lcpllrsvd0[7:0],hsclk0_lcpllrsvd1[7:0],hsclk0_rpllrsvd0[7:0],hsclk0_rpllrsvd1[7:0],hsclk1_lcpllrsvd0[7:0],hsclk1_lcpllrsvd1[7:0],hsclk1_rpllrsvd0[7:0],hsclk1_rpllrsvd1[7:0],hsclk0_lcpllrsvdout[7:0],hsclk1_lcpllrsvdout[7:0],hsclk0_rpllrsvdout[7:0],hsclk1_rpllrsvdout[7:0],apb3clk,apb3paddr[15:0],apb3penable,apb3presetn,apb3prdata[31:0],apb3psel,apb3pslverr,apb3pready,apb3pwdata[31:0],apb3pwrite,rxp[3:0],rxn[3:0],txp[3:0],txn[3:0]";
attribute X_CORE_INFO : string;
attribute X_CORE_INFO of stub : architecture is "system_gt_quad_base_0_0_inst,Vivado 2022.2";
begin
end;
