# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.srcs/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/design_1_axi_noc_0_0.xci
# IP: The module: 'design_1_axi_noc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/bd_8be5.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5 || ORIG_REF_NAME==bd_8be5} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/bd_8be5_S01_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_S01_AXI_nmu_0 || ORIG_REF_NAME==bd_8be5_S01_AXI_nmu_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_1/bd_8be5_const_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_const_0_0 || ORIG_REF_NAME==bd_8be5_const_0_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/bd_8be5_S06_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_S06_AXI_nmu_0 || ORIG_REF_NAME==bd_8be5_S06_AXI_nmu_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_3/bd_8be5_S00_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_S00_AXI_nmu_0 || ORIG_REF_NAME==bd_8be5_S00_AXI_nmu_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_4/bd_8be5_S02_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_S02_AXI_nmu_0 || ORIG_REF_NAME==bd_8be5_S02_AXI_nmu_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_5/bd_8be5_S07_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_S07_AXI_nmu_0 || ORIG_REF_NAME==bd_8be5_S07_AXI_nmu_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_6/bd_8be5_S03_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_S03_AXI_nmu_0 || ORIG_REF_NAME==bd_8be5_S03_AXI_nmu_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/bd_8be5_S05_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_S05_AXI_nmu_0 || ORIG_REF_NAME==bd_8be5_S05_AXI_nmu_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_8/bd_8be5_S04_AXI_rpu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_S04_AXI_rpu_0 || ORIG_REF_NAME==bd_8be5_S04_AXI_rpu_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/bd_8be5_MC0_ddrc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_MC0_ddrc_0 || ORIG_REF_NAME==bd_8be5_MC0_ddrc_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/bd_8be5_MC0_ddrc_0_phy.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_MC0_ddrc_0_phy || ORIG_REF_NAME==bd_8be5_MC0_ddrc_0_phy} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_10/bd_8be5_S01_AXI_nsw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_S01_AXI_nsw_0 || ORIG_REF_NAME==bd_8be5_S01_AXI_nsw_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_11/bd_8be5_MC1_nsw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_MC1_nsw_0 || ORIG_REF_NAME==bd_8be5_MC1_nsw_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_12/bd_8be5_S06_AXI_nsw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_S06_AXI_nsw_0 || ORIG_REF_NAME==bd_8be5_S06_AXI_nsw_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_13/bd_8be5_MC2_nsw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_MC2_nsw_0 || ORIG_REF_NAME==bd_8be5_MC2_nsw_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_14/bd_8be5_S00_AXI_nsw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_S00_AXI_nsw_0 || ORIG_REF_NAME==bd_8be5_S00_AXI_nsw_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_15/bd_8be5_MC0_nsw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_MC0_nsw_0 || ORIG_REF_NAME==bd_8be5_MC0_nsw_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_16/bd_8be5_S02_AXI_nsw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_S02_AXI_nsw_0 || ORIG_REF_NAME==bd_8be5_S02_AXI_nsw_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_17/bd_8be5_S07_AXI_nsw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_S07_AXI_nsw_0 || ORIG_REF_NAME==bd_8be5_S07_AXI_nsw_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_18/bd_8be5_MC3_nsw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_MC3_nsw_0 || ORIG_REF_NAME==bd_8be5_MC3_nsw_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_19/bd_8be5_S03_AXI_nsw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_S03_AXI_nsw_0 || ORIG_REF_NAME==bd_8be5_S03_AXI_nsw_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_20/bd_8be5_S05_AXI_nsw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_S05_AXI_nsw_0 || ORIG_REF_NAME==bd_8be5_S05_AXI_nsw_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_21/bd_8be5_S04_AXI_nsw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_S04_AXI_nsw_0 || ORIG_REF_NAME==bd_8be5_S04_AXI_nsw_0} -quiet] -quiet

# XDC: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/xdc/bd_8be5_S01_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8be5_S01_AXI_nmu_0 || ORIG_REF_NAME==bd_8be5_S01_AXI_nmu_0} -quiet] {/bd_8be5_S01_AXI_nmu_0_top_INST } ]/bd_8be5_S01_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/xdc/bd_8be5_S06_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8be5_S06_AXI_nmu_0 || ORIG_REF_NAME==bd_8be5_S06_AXI_nmu_0} -quiet] {/bd_8be5_S06_AXI_nmu_0_top_INST } ]/bd_8be5_S06_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_3/xdc/bd_8be5_S00_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8be5_S00_AXI_nmu_0 || ORIG_REF_NAME==bd_8be5_S00_AXI_nmu_0} -quiet] {/bd_8be5_S00_AXI_nmu_0_top_INST } ]/bd_8be5_S00_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_4/xdc/bd_8be5_S02_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8be5_S02_AXI_nmu_0 || ORIG_REF_NAME==bd_8be5_S02_AXI_nmu_0} -quiet] {/bd_8be5_S02_AXI_nmu_0_top_INST } ]/bd_8be5_S02_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_5/xdc/bd_8be5_S07_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8be5_S07_AXI_nmu_0 || ORIG_REF_NAME==bd_8be5_S07_AXI_nmu_0} -quiet] {/bd_8be5_S07_AXI_nmu_0_top_INST } ]/bd_8be5_S07_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_6/xdc/bd_8be5_S03_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8be5_S03_AXI_nmu_0 || ORIG_REF_NAME==bd_8be5_S03_AXI_nmu_0} -quiet] {/bd_8be5_S03_AXI_nmu_0_top_INST } ]/bd_8be5_S03_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/xdc/bd_8be5_S05_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8be5_S05_AXI_nmu_0 || ORIG_REF_NAME==bd_8be5_S05_AXI_nmu_0} -quiet] {/bd_8be5_S05_AXI_nmu_0_top_INST } ]/bd_8be5_S05_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_8/xdc/bd_8be5_S04_AXI_rpu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8be5_S04_AXI_rpu_0 || ORIG_REF_NAME==bd_8be5_S04_AXI_rpu_0} -quiet] {/bd_8be5_S04_AXI_rpu_0_top_INST } ]/bd_8be5_S04_AXI_rpu_0_top_INST ] -quiet] -quiet

# XDC: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/hdl/par/bd_8be5_MC0_ddrc_0_ip.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8be5_MC0_ddrc_0 || ORIG_REF_NAME==bd_8be5_MC0_ddrc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/design_1_axi_noc_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_noc_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/design_1_axi_noc_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_noc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/design_1_axi_noc_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_noc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.srcs/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/design_1_axi_noc_0_0.xci
# IP: The module: 'design_1_axi_noc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/bd_8be5.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5 || ORIG_REF_NAME==bd_8be5} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/bd_8be5_S01_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_S01_AXI_nmu_0 || ORIG_REF_NAME==bd_8be5_S01_AXI_nmu_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_1/bd_8be5_const_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_const_0_0 || ORIG_REF_NAME==bd_8be5_const_0_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/bd_8be5_S06_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_S06_AXI_nmu_0 || ORIG_REF_NAME==bd_8be5_S06_AXI_nmu_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_3/bd_8be5_S00_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_S00_AXI_nmu_0 || ORIG_REF_NAME==bd_8be5_S00_AXI_nmu_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_4/bd_8be5_S02_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_S02_AXI_nmu_0 || ORIG_REF_NAME==bd_8be5_S02_AXI_nmu_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_5/bd_8be5_S07_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_S07_AXI_nmu_0 || ORIG_REF_NAME==bd_8be5_S07_AXI_nmu_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_6/bd_8be5_S03_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_S03_AXI_nmu_0 || ORIG_REF_NAME==bd_8be5_S03_AXI_nmu_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/bd_8be5_S05_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_S05_AXI_nmu_0 || ORIG_REF_NAME==bd_8be5_S05_AXI_nmu_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_8/bd_8be5_S04_AXI_rpu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_S04_AXI_rpu_0 || ORIG_REF_NAME==bd_8be5_S04_AXI_rpu_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/bd_8be5_MC0_ddrc_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_MC0_ddrc_0 || ORIG_REF_NAME==bd_8be5_MC0_ddrc_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/ip_0/bd_8be5_MC0_ddrc_0_phy.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_MC0_ddrc_0_phy || ORIG_REF_NAME==bd_8be5_MC0_ddrc_0_phy} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_10/bd_8be5_S01_AXI_nsw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_S01_AXI_nsw_0 || ORIG_REF_NAME==bd_8be5_S01_AXI_nsw_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_11/bd_8be5_MC1_nsw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_MC1_nsw_0 || ORIG_REF_NAME==bd_8be5_MC1_nsw_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_12/bd_8be5_S06_AXI_nsw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_S06_AXI_nsw_0 || ORIG_REF_NAME==bd_8be5_S06_AXI_nsw_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_13/bd_8be5_MC2_nsw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_MC2_nsw_0 || ORIG_REF_NAME==bd_8be5_MC2_nsw_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_14/bd_8be5_S00_AXI_nsw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_S00_AXI_nsw_0 || ORIG_REF_NAME==bd_8be5_S00_AXI_nsw_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_15/bd_8be5_MC0_nsw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_MC0_nsw_0 || ORIG_REF_NAME==bd_8be5_MC0_nsw_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_16/bd_8be5_S02_AXI_nsw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_S02_AXI_nsw_0 || ORIG_REF_NAME==bd_8be5_S02_AXI_nsw_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_17/bd_8be5_S07_AXI_nsw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_S07_AXI_nsw_0 || ORIG_REF_NAME==bd_8be5_S07_AXI_nsw_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_18/bd_8be5_MC3_nsw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_MC3_nsw_0 || ORIG_REF_NAME==bd_8be5_MC3_nsw_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_19/bd_8be5_S03_AXI_nsw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_S03_AXI_nsw_0 || ORIG_REF_NAME==bd_8be5_S03_AXI_nsw_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_20/bd_8be5_S05_AXI_nsw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_S05_AXI_nsw_0 || ORIG_REF_NAME==bd_8be5_S05_AXI_nsw_0} -quiet] -quiet

# IP: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_21/bd_8be5_S04_AXI_nsw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8be5_S04_AXI_nsw_0 || ORIG_REF_NAME==bd_8be5_S04_AXI_nsw_0} -quiet] -quiet

# XDC: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/xdc/bd_8be5_S01_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8be5_S01_AXI_nmu_0 || ORIG_REF_NAME==bd_8be5_S01_AXI_nmu_0} -quiet] {/bd_8be5_S01_AXI_nmu_0_top_INST } ]/bd_8be5_S01_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/xdc/bd_8be5_S06_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8be5_S06_AXI_nmu_0 || ORIG_REF_NAME==bd_8be5_S06_AXI_nmu_0} -quiet] {/bd_8be5_S06_AXI_nmu_0_top_INST } ]/bd_8be5_S06_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_3/xdc/bd_8be5_S00_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8be5_S00_AXI_nmu_0 || ORIG_REF_NAME==bd_8be5_S00_AXI_nmu_0} -quiet] {/bd_8be5_S00_AXI_nmu_0_top_INST } ]/bd_8be5_S00_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_4/xdc/bd_8be5_S02_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8be5_S02_AXI_nmu_0 || ORIG_REF_NAME==bd_8be5_S02_AXI_nmu_0} -quiet] {/bd_8be5_S02_AXI_nmu_0_top_INST } ]/bd_8be5_S02_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_5/xdc/bd_8be5_S07_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8be5_S07_AXI_nmu_0 || ORIG_REF_NAME==bd_8be5_S07_AXI_nmu_0} -quiet] {/bd_8be5_S07_AXI_nmu_0_top_INST } ]/bd_8be5_S07_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_6/xdc/bd_8be5_S03_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8be5_S03_AXI_nmu_0 || ORIG_REF_NAME==bd_8be5_S03_AXI_nmu_0} -quiet] {/bd_8be5_S03_AXI_nmu_0_top_INST } ]/bd_8be5_S03_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_7/xdc/bd_8be5_S05_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8be5_S05_AXI_nmu_0 || ORIG_REF_NAME==bd_8be5_S05_AXI_nmu_0} -quiet] {/bd_8be5_S05_AXI_nmu_0_top_INST } ]/bd_8be5_S05_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_8/xdc/bd_8be5_S04_AXI_rpu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8be5_S04_AXI_rpu_0 || ORIG_REF_NAME==bd_8be5_S04_AXI_rpu_0} -quiet] {/bd_8be5_S04_AXI_rpu_0_top_INST } ]/bd_8be5_S04_AXI_rpu_0_top_INST ] -quiet] -quiet

# XDC: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_9/hdl/par/bd_8be5_MC0_ddrc_0_ip.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8be5_MC0_ddrc_0 || ORIG_REF_NAME==bd_8be5_MC0_ddrc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/design_1_axi_noc_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_noc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/design_1_axi_noc_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_noc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/dewsjoe/Desktop/projects_2022.1/projects_ldg/project_3.1/project_3.1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/design_1_axi_noc_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_noc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
