typedef class nmu_write_tracker;
typedef class nmu_rate_limiter;

class nmu_write_fe;

int VERBOSITY_EN;
nmu_reg_class p_nmu_reg;

nmu_axi_ctrl u_nmu_axi_ctrl;
nmu_addr_map u_nmu_addr_map;
nmu_axi_req_write_data_conversion u_nmu_axi_req_write_data_conversion;
nmu_async_fifos p_nmu_async_fifos;

nmu_write_tracker p_nmu_write_tracker;
//nmu_write_buffer p_nmu_write_buffer;
nmu_rate_limiter p_nmu_rate_limiter;

bit axi_stream,axi3,axi4;

typedef struct packed {
   int awid;
   longint awaddr;
   int awlen;
   int awsize;
   int awburst;
   int awlock;
   int awcache;
   int awprot;
   int awqos;
   int awuser; 
   int nmu_wr_usr_dst;
   int nmu_wr_dest_mode;
} noc_axi_aw_t;
typedef struct packed {
   int wid;
   bit [`NOC_AXDATA512_WIDTH-1:0] wdata;
   bit [`NOC_AXSTRB64_WIDTH-1:0] wstrb;
   int wlast;
   int wuser;
   int nmu_wr_usr_dst;
   int nmu_wr_dest_mode;
} noc_axi_w_t;

//internal variables for write
bit send_first_npp_pkt;
bit last_wr_data_flit;
bit wr_transaction_ongoing;
int aw_total_flit_length;
longint wr_transaction_flit_addr;
int wr_transaction_flit_len;
int wr_transaction_flit_size;
int wr_transaction_flit_burst;
int cumulative_wr_transaction_flit_len; 

//write channel
int awid;
longint awaddr;
int awlen;
int awsize;
int awburst;
int awlock;
int awcache;
int awprot;
int awqos;
int awuser;
int nmu_wr_usr_dst;
int nmu_wr_dest_mode;
int dest_id;
bit pending_ssid_check; //when asserted means that req is generated by needs ssid_check to pass before pushing to wrtrk/imiter
bit ssid_check_passed;

bit valid_from_wr_axi_conversion; //when asserted means that write_fe send a hdr flit to rate limiter and is waiting for ack
bit awready;
bit wready;

bit [`NOC_NPP_WIDTH -1:0] flit;

   int wr_transaction_flit_len_r;
   bit [`NOC_NPP_WIDTH -1:0] flit_r;
   int dest_id_r;
   int awid_r;
   int aw_total_flit_length_r;
   int cumulative_wr_transaction_flit_len_r; 
bit wr_fe_ff_en, wr_trk_ff_en; 

function new (nmu_reg_class nmu_reg, int verbosity_en);
  p_nmu_reg = nmu_reg;
  VERBOSITY_EN = verbosity_en;
  u_nmu_axi_ctrl = new(nmu_reg,1,verbosity_en);
  u_nmu_addr_map = new(nmu_reg,1,verbosity_en);
  u_nmu_axi_req_write_data_conversion = new(nmu_reg,verbosity_en);
endfunction

function void update_registers();
  axi_stream = (p_nmu_reg.REG_MODE_SELECT[1:0] == 2)?1:0; //FIXME: will cause problem if partial reconfig
  axi3 = (p_nmu_reg.REG_MODE_SELECT[1:0] == 1)?1:0;
  axi4 = (p_nmu_reg.REG_MODE_SELECT[1:0] == 0)?1:0;
  if(axi_stream) begin awready =0; wready =1; end
  else begin awready =1; wready =0; end
  u_nmu_axi_req_write_data_conversion.update_registers();
endfunction

function void update_new_waddr(noc_axi_aw_t noc_axi_aw_t_temp);
  this.awid=noc_axi_aw_t_temp.awid;
  this.awaddr=noc_axi_aw_t_temp.awaddr;
  this.awlen=noc_axi_aw_t_temp.awlen;
  this.awsize=noc_axi_aw_t_temp.awsize;
  this.awburst=noc_axi_aw_t_temp.awburst;
  this.awlock=noc_axi_aw_t_temp.awlock;
  this.awcache=noc_axi_aw_t_temp.awcache;
  this.awprot=noc_axi_aw_t_temp.awprot;
  this.awqos=noc_axi_aw_t_temp.awqos;
  this.awuser=noc_axi_aw_t_temp.awuser;
  this.nmu_wr_usr_dst=noc_axi_aw_t_temp.nmu_wr_usr_dst;
  this.nmu_wr_dest_mode=noc_axi_aw_t_temp.nmu_wr_dest_mode;
  u_nmu_addr_map.update_new_aaddr(awaddr, nmu_wr_dest_mode, nmu_wr_usr_dst);
  u_nmu_axi_ctrl.determine_total_flit_len_size_burst(u_nmu_addr_map.dst_ddr,u_nmu_addr_map.pkt_chopsize,awaddr,awlen,awsize,awburst,awlock,awcache,1);
  aw_total_flit_length = u_nmu_axi_ctrl.total_flit_length;
  wr_transaction_flit_size = u_nmu_axi_ctrl.flit_size;
  wr_transaction_flit_burst = u_nmu_axi_ctrl.flit_burst;
  send_first_npp_pkt = 1; last_wr_data_flit = 0;
  wr_transaction_ongoing=1;
  cumulative_wr_transaction_flit_len = 0;
  awready =0; wready =0;
//  for wrap txn of size<4, wrap is converted to incr; hence sending modified addr to axi_conversion block
  u_nmu_axi_req_write_data_conversion.update_new_axi_addr(awaddr,awsize,awlen,awburst,u_nmu_axi_ctrl.flit_start_addr,wr_transaction_flit_size,wr_transaction_flit_burst,aw_total_flit_length);
endfunction

function void update(); //executes every noc clk

  //check if anything needs to be read from afifo
  if(awready && ~p_nmu_async_fifos.aw_afifo_empty) update_new_waddr(p_nmu_async_fifos.read_from_aw_fifo());
  if(wready && ~p_nmu_async_fifos.w_afifo_empty) update_new_wdata(p_nmu_async_fifos.read_from_w_fifo());
  //check if flits need to be sent
  if(wr_transaction_ongoing && (send_first_npp_pkt || last_wr_data_flit) && !valid_from_wr_axi_conversion && !pending_ssid_check) begin //new axi transaction started or the last flit of chopped transaction was sent;so need to send new addr flit now
    u_nmu_axi_ctrl.get_addr_flit(awaddr,cumulative_wr_transaction_flit_len,awsize,awburst,awlock,awcache);
    wr_transaction_flit_addr = u_nmu_axi_ctrl.flit_addr;
    wr_transaction_flit_len = u_nmu_axi_ctrl.flit_len;
    dest_id = u_nmu_addr_map.get_dest_id(wr_transaction_flit_addr);
   `PRINT_MODEL(VERBOSITY_EN,$sformatf("REG_SRC =%0d DESTINATION_ID =%0d",p_nmu_reg.REG_SRC,dest_id),DBG);
    u_nmu_axi_req_write_data_conversion.update_new_npp_addr(dest_id, wr_transaction_flit_len);
    pending_ssid_check = 1;
    do_ssid_check();
  end
  if(pending_ssid_check && ssid_check_passed && !p_nmu_write_tracker.full()) begin
    pending_ssid_check = 0;
    flit=convert_to_ctrl_flit(1,awid,u_nmu_addr_map.get_remapped_addr(wr_transaction_flit_addr),wr_transaction_flit_len,wr_transaction_flit_size,wr_transaction_flit_burst,awlock,awcache,awprot,awqos,awuser,dest_id);
   `PRINT_MODEL(VERBOSITY_EN,$sformatf("REG_SRC =%0d WRITE pushing back addr %16h len=%0d",p_nmu_reg.REG_SRC,wr_transaction_flit_addr,wr_transaction_flit_len),DBG)
    cumulative_wr_transaction_flit_len += (wr_transaction_flit_len+1);
    //p_nmu_rate_limiter.add_flit(1,wr_transaction_flit_len,flit); 
    p_nmu_rate_limiter.add_flit(1,wr_transaction_flit_len,flit_gen_with_ecc(flit));  // Added FLIT with ECC
    p_nmu_write_tracker.add_flit(dest_id,awid,((aw_total_flit_length+1) == cumulative_wr_transaction_flit_len),awlock);
    valid_from_wr_axi_conversion=1;
    wready = 0;
  end
endfunction

function void grant();
  if(valid_from_wr_axi_conversion) begin  //if wr req hdr was sent
    valid_from_wr_axi_conversion =0;
    wready = 1;
    send_first_npp_pkt = 0;
    last_wr_data_flit=0;
  end
  else if(u_nmu_axi_req_write_data_conversion.valid_from_wr_data_conversion)begin //if grant is for data flit
    void'(u_nmu_axi_req_write_data_conversion.flit_tmp_q.pop_front());
    if(u_nmu_axi_req_write_data_conversion.flit_tmp_q.size() == 0) begin //all received wdata flits are converted and sent to rate limiter
      u_nmu_axi_req_write_data_conversion.valid_from_wr_data_conversion =0; 
      if(axi_stream) begin
        wready = 1;
      end  
      else begin //axi-mm
        if((aw_total_flit_length+1) == u_nmu_axi_req_write_data_conversion.cumulative_num_of_wrdata_flits_sent) begin //all data flits are processed for the chop
          wr_transaction_ongoing = 0;
          awready =1; //can take next new axi transaction
          wready = 0;
        end
        else begin
          last_wr_data_flit = u_nmu_axi_req_write_data_conversion.last_wr_data_flit; //after every chop, deassert wready to send header flit
          wready = ~last_wr_data_flit;
        end  
      end  
    end
    else begin //still have pending flits to send to next stage; send them before asserting wready on axi if
       p_nmu_rate_limiter.add_flit(0,0,u_nmu_axi_req_write_data_conversion.flit_tmp_q[0]);
    end  
  end
endfunction

function void update_new_wdata(noc_axi_w_t noc_axi_w_t_temp);
  u_nmu_axi_req_write_data_conversion.update_new_wdata(noc_axi_w_t_temp);
  if(u_nmu_axi_req_write_data_conversion.valid_from_wr_data_conversion) wready = 0;//deasserting wready as we are not sure if the flits were successfully saved in wbuf or not. This will be updated after the grant is received from the wbuf . If axi_size< npp_size, collect atleast 1 flit of data before deasserting wready
endfunction

function bit [`NOC_NPP_WIDTH-1:0] convert_to_ctrl_flit(bit wr,int aid,longint aaddr,int alen,int asize,int aburst,int alock,int acache,int aprot,int aqos,int auser,int dst);
  bit [`NOC_NPP_WIDTH-1:0] flit;
  flit[`NOC_NPP_AXADDR] = aaddr;
  flit[`NOC_NPP_AXLEN] = alen;
  flit[`NOC_NPP_AXSIZE] = asize;
  flit[`NOC_NPP_AXBURST] = aburst;
  flit[`NOC_NPP_AXLOCK] = alock;
  if (p_nmu_reg.REG_AXI_NON_MOD_DISABLE[0] == 1 ) acache[1] =1;
  flit[`NOC_NPP_AXCACHE] = acache;
  flit[`NOC_NPP_AXPROT] = aprot;
  flit[`NOC_NPP_AXQOS] = aqos;
  flit[`NOC_NPP_AXID] = aid;
  flit[`NOC_NPP_AXUSER] = auser;
  flit[`NOC_NPP_SMID] = ((p_nmu_reg.REG_SMID_SEL[9:0] & p_nmu_reg.REG_SMID_SEL[19:10]) | (~p_nmu_reg.REG_SMID_SEL[9:0] & auser[9:0]));
   `PRINT_MODEL(VERBOSITY_EN,$sformatf("REG_SRC =%0d NPP USER_BITS 'h%10h, SMID_EN 'h%0x, SMID_VAL 'h%0x, AXI USER_BITS 'h%0x",p_nmu_reg.REG_SRC,flit[`NOC_NPP_SMID],p_nmu_reg.REG_SMID_SEL[9:0],p_nmu_reg.REG_SMID_SEL[19:10],auser[9:0]),DBG)
  if(wr) flit[`NOC_NPP_PKT_TYPE] = `NOC_NPP_PKT_TYPE_WRITE_REQ;
  else flit[`NOC_NPP_PKT_TYPE] = `NOC_NPP_PKT_TYPE_READ_REQ;
  flit[`NOC_NPP_MISC_CTRL] = 0;
  if(wr) flit[`NOC_NPP_TAG] = 0;
  flit[`NOC_NPP_SRC] = p_nmu_reg.REG_SRC;
  flit[`NOC_NPP_DST] = dst;
  flit[`NOC_NPP_DST_PAR] = 0;
  flit[`NOC_NPP_PRI] = p_nmu_reg.REG_PRIORITY[1];
  if(wr) flit[`NOC_NPP_LAST] = 0; else flit[`NOC_NPP_LAST] = 1;
  flit[`NOC_NPP_ECC] = 0;
  return flit;
endfunction

function void do_ssid_check();
  if(pending_ssid_check) ssid_check_passed = ssid_check(awid,dest_id);
endfunction

function int ssid_check (int axi_id, int dest_id);
  for(int i=0; i<p_nmu_write_tracker.wr_resp_tracker.size();i++) begin
    if((axi_id == p_nmu_write_tracker.wr_resp_tracker[i].axi_id)  && (p_nmu_write_tracker.wr_resp_tracker[i].num_chops != 0)) begin
      //entry exists with matching axi_id and entry is also expecting some npp_responses
      if(dest_id== p_nmu_write_tracker.wr_resp_tracker[i].dest_id) begin
        return 1; //same axi id same dest. can proceed to send addr
      end 
      else begin //same axi but going to different dest. pull a/wready low
        return 0;
      end  
    end 
  end  
  //matching entry not found;so no id check necessary
  return 1;
endfunction

function bit [`NOC_NPP_WIDTH-1:0] flit_gen_with_ecc (bit [`NOC_NPP_WIDTH-1:0] din);

bit [246:0] C_XOR_EN_P1   = 247'h55555555555555555555555555555555aaaaaaaaaaaaaaab55555556aaad5b;
bit [246:0] C_XOR_EN_P2   = 247'h66666666666666666666666666666666cccccccccccccccd9999999b33366d;
bit [246:0] C_XOR_EN_P4   = 247'h78787878787878787878787878787878f0f0f0f0f0f0f0f1e1e1e1e3c3c78e;
bit [246:0] C_XOR_EN_P8   = 247'h7f807f807f807f807f807f807f807f80ff00ff00ff00ff01fe01fe03fc07f0;
bit [246:0] C_XOR_EN_P16  = 247'h7fff80007fff80007fff80007fff8000ffff0000ffff0001fffe0003fff800;
bit [246:0] C_XOR_EN_P32  = 247'h7fffffff800000007fffffff80000000ffffffff00000001fffffffc000000;
bit [246:0] C_XOR_EN_P64  = 247'h7fffffffffffffff8000000000000000fffffffffffffffe00000000000000;
bit [246:0] C_XOR_EN_P128 = 247'h7fffffffffffffffffffffffffffffff000000000000000000000000000000;
bit [246:0] C_XOR_EN_PAR  = 247'h4b34b4cb34cb4b34b4cb4b34cb34b4cb69969669966969972cd2d32da65cb7;

logic 		      p1, p2, p4, p8, p16, p32, p64, p128, pp1;
logic [`NOC_NPP_ECC_WIDTH-1:0]         ecc_gen;
logic [246:0] din_w;

 din_w = {{(247-`NOC_NPP_WIDTH_WO_ECC){1'b0}},din[171:0]};

 p1   = ^(din_w & C_XOR_EN_P1);
 p2   = ^(din_w & C_XOR_EN_P2);
 p4   = ^(din_w & C_XOR_EN_P4);
 p8   = ^(din_w & C_XOR_EN_P8);
 p16  = ^(din_w & C_XOR_EN_P16);
 p32  = ^(din_w & C_XOR_EN_P32);
 p64  = ^(din_w & C_XOR_EN_P64);
 p128 = ^(din_w & C_XOR_EN_P128);
 pp1  = ^(din_w & C_XOR_EN_PAR);

 ecc_gen = {1'b0,pp1,p128,p64,p32,p16,p8,p4,p2,p1};

return {ecc_gen, din[171:0]};
endfunction
endclass
